#!/usr/bin/env python

import json
import sys


def parse_pod_output():
    out = sys.stdin.readlines()
    foo = json.loads(' '.join(out))
    for item in foo['items']:
        name_slugs = set(item['metadata']['name'].split('-'))
        if 'fectrl' in name_slugs:
            if item['status']['phase'] == "Running":
                print item['status']['podIP']

if __name__ == "__main__":
        parse_pod_output()
