package httpheader

const (
	Accept            = "Accept"
	AcceptCharset     = "Accept-Charset"
	AcceptEncoding    = "Accept-Encoding"
	AcceptLanguage    = "Accept-Language"
	Authorization     = "Authorization"
	CacheControl      = "Cache-Control"
	ContentEncoding   = "Content-Encoding"
	ContentLanguage   = "Content-Language"
	ContentLength     = "Content-Length"
	ContentLocation   = "Content-Location"
	ContentType       = "Content-Type"
	Cookie            = "Cookie"
	Date              = "Date"
	ETag              = "ETag"
	Expires           = "Expires"
	Host              = "Host"
	IfMatch           = "If-Match"
	IfModifiedSince   = "If-Modified-Since"
	IfNoneMatch       = "If-None-Match"
	IfUnmodifiedSince = "If-Unmodified-Since"
	LastModified      = "Last-Modified"
	Location          = "Location"
	RetryAfter        = "Retry-After"
	SetCookie         = "Set-Cookie"
	UserAgent         = "User-Agent"
	Vary              = "Vary"
	WWWAuthenticate   = "WWW-Authenticate"
)
