{
  "basePath": "",
  "documentationLink": "https://developers.google.com/sheets/",
  "revision": "20170907",
  "id": "sheets:v4",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Sheets",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "View the files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "View and manage the files in your Google Drive"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "View and manage your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        }
      }
    }
  },
  "rootUrl": "https://sheets.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "sheets",
  "batchPath": "batch",
  "title": "Google Sheets API",
  "ownerName": "Google",
  "resources": {
    "spreadsheets": {
      "methods": {
        "get": {
          "description": "Returns the spreadsheet at the given ID.\nThe caller must specify the spreadsheet ID.\n\nBy default, data within grids will not be returned.\nYou can include grid data one of two ways:\n\n* Specify a field mask listing your desired fields using the `fields` URL\nparameter in HTTP\n\n* Set the includeGridData\nURL parameter to true.  If a field mask is set, the `includeGridData`\nparameter is ignored\n\nFor large spreadsheets, it is recommended to retrieve only the speci[...]",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "flatPath": "v4/spreadsheets/{spreadsheetId}",
          "path": "v4/spreadsheets/{spreadsheetId}",
          "id": "sheets.spreadsheets.get"
        },
        "batchUpdate": {
          "id": "sheets.spreadsheets.batchUpdate",
          "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
          "description": "Applies one or more updates to the spreadsheet.\n\nEach request is validated before\nbeing applied. If any request is not valid then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how\nthey are applied. The replies will mirror the requests.  For example,\nif you applied 4 updates and the 3rd one had a reply, then the\nresponse will have 2 empty replies, the actual reply, and another empty\nrep[...]",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "flatPath": "v4/spreadsheets/{spreadsheetId}:batchUpdate"
        },
        "create": {
          "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "flatPath": "v4/spreadsheets",
          "id": "sheets.spreadsheets.create",
          "path": "v4/spreadsheets"
        }
      },
      "resources": {
        "values": {
          "methods": {
            "batchUpdate": {
              "id": "sheets.spreadsheets.values.batchUpdate",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
              "description": "Sets values in one or more ranges of a spreadsheet.\nThe caller must specify the spreadsheet ID,\na valueInputOption, and one or more\nValueRanges.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate"
            },
            "batchGet": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
              "id": "sheets.spreadsheets.values.batchGet",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
              "description": "Returns one or more ranges of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and one or more ranges."
            },
            "clear": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "id": "sheets.spreadsheets.values.clear",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "description": "Clears values from a spreadsheet.\nThe caller must specify the spreadsheet ID and range.\nOnly values are cleared -- all other properties of the cell (such as\nformatting, data validation, etc..) are kept.",
              "httpMethod": "POST"
            },
            "append": {
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
              "id": "sheets.spreadsheets.values.append",
              "description": "Appends values to a spreadsheet. The input range is used to search for\nexisting data and find a \"table\" within that range. Values will be\nappended to the next row of the table, starting with the first column of\nthe table. See the\n[guide](/sheets/api/guides/values#appending_values)\nand\n[sample code](/sheets/api/samples/writing#append_values)\nfor specific details of how tables are detected and data is appended.\n\nThe caller must specify the spreadsheet ID, r[...]",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:append"
            },
            "batchClear": {
              "id": "sheets.spreadsheets.values.batchClear",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
              "description": "Clears one or more ranges of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and one or more ranges.\nOnly values are cleared -- all other properties of the cell (such as\nformatting, data validation, etc..) are kept.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClear"
            },
            "get": {
              "description": "Returns a range of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and a range.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "id": "sheets.spreadsheets.values.get",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "id": "sheets.spreadsheets.values.update",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "description": "Sets values in a range of a spreadsheet.\nThe caller must specify the spreadsheet ID, range, and\na valueInputOption.",
              "httpMethod": "PUT"
            }
          }
        },
        "sheets": {
          "methods": {
            "copyTo": {
              "description": "Copies a single sheet from a spreadsheet to another spreadsheet.\nReturns the properties of the newly created sheet.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "id": "sheets.spreadsheets.sheets.copyTo",
              "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo"
            }
          }
        }
      }
    }
  },
  "version": "v4",
  "baseUrl": "https://sheets.googleapis.com/",
  "servicePath": "",
  "description": "Reads and writes Google Sheets.",
  "kind": "discovery#restDescription"
}
