{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "YouTube Analytics",
  "description": "Retrieves your YouTube Analytics data.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "fullyEncodeReservedExpansion": true,
  "id": "youtubeAnalytics:v2",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "name": "youtubeAnalytics",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "groupItems": {
      "methods": {
        "delete": {
          "description": "Removes an item from a group.",
          "flatPath": "v2/groupItems",
          "httpMethod": "DELETE",
          "id": "youtubeAnalytics.groupItems.delete",
          "path": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "insert": {
          "description": "Creates a group item.",
          "flatPath": "v2/groupItems",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groupItems.insert",
          "path": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "description": "Returns a collection of group items that match the API request parameters.",
          "flatPath": "v2/groupItems",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groupItems.list",
          "path": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    },
    "groups": {
      "methods": {
        "delete": {
          "description": "Deletes a group.",
          "flatPath": "v2/groups",
          "httpMethod": "DELETE",
          "id": "youtubeAnalytics.groups.delete",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "insert": {
          "description": "Creates a group.",
          "flatPath": "v2/groups",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groups.insert",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "description": "Returns a collection of groups that match the API request parameters. For\nexample, you can retrieve all groups that the authenticated user owns,\nor you can retrieve one or more groups by their unique IDs.",
          "flatPath": "v2/groups",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groups.list",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "update": {
          "description": "Modifies a group. For example, you could change a group's title.",
          "flatPath": "v2/groups",
          "httpMethod": "PUT",
          "id": "youtubeAnalytics.groups.update",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "description": "Retrieve your YouTube Analytics reports.",
          "flatPath": "v2/reports",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.reports.query",
          "path": "v2/reports",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "revision": "20200215",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "servicePath": "",
  "title": "YouTube Analytics API",
  "version": "v2",
  "version_module": true
}