{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/deWKWLiFywg1_Xne7G92xyJt8HA\"",
 "discoveryVersion": "v1",
 "id": "analytics:v2.4",
 "name": "analytics",
 "version": "v2.4",
 "revision": "20150115",
 "title": "Google Analytics API",
 "description": "View and manage your Google Analytics data",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/analytics/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/analytics/v2.4/",
 "basePath": "/analytics/v2.4/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "analytics/v2.4/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/analytics": {
     "description": "View and manage your Google Analytics data"
    },
    "https://www.googleapis.com/auth/analytics.readonly": {
     "description": "View your Google Analytics data"
    }
   }
  }
 },
 "resources": {
  "data": {
   "methods": {
    "get": {
     "id": "analytics.data.get",
     "path": "data",
     "httpMethod": "GET",
     "description": "Returns Analytics report data for a view (profile).",
     "scopes": [
      "https://www.googleapis.com/auth/analytics",
      "https://www.googleapis.com/auth/analytics.readonly"
     ]
    }
   }
  },
  "management": {
   "resources": {
    "accounts": {
     "methods": {
      "list": {
       "id": "analytics.management.accounts.list",
       "path": "management/accounts",
       "httpMethod": "GET",
       "description": "Lists all accounts to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "goals": {
     "methods": {
      "list": {
       "id": "analytics.management.goals.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "httpMethod": "GET",
       "description": "Lists goals to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "profiles": {
     "methods": {
      "list": {
       "id": "analytics.management.profiles.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "httpMethod": "GET",
       "description": "Lists views (profiles) to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "segments": {
     "methods": {
      "list": {
       "id": "analytics.management.segments.list",
       "path": "management/segments",
       "httpMethod": "GET",
       "description": "Lists advanced segments to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "webproperties": {
     "methods": {
      "list": {
       "id": "analytics.management.webproperties.list",
       "path": "management/accounts/{accountId}/webproperties",
       "httpMethod": "GET",
       "description": "Lists web properties to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
