filegroup(
    name = "package-srcs",
    srcs = glob(["**"]),
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)

filegroup(
    name = "all-srcs",
    srcs = [
        ":package-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/api/apitesting:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/api/equality:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/api/errors:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/api/meta:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/api/resource:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/api/validation:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/fuzzer:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/internalversion:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/v1:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/v1beta1:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/testapigroup:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/conversion:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/fields:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/labels:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/runtime:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/selection:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/test:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/types:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/cache:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/clock:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/diff:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/duration:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/errors:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/framer:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/httpstream:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/intstr:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/json:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/mergepatch:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/naming:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/net:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/proxy:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/rand:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/remotecommand:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/runtime:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/sets:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/strategicpatch:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/uuid:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/validation:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/version:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/wait:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/waitgroup:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/webhook:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/util/yaml:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/version:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/watch:all-srcs",
        "//staging/src/k8s.io/apimachinery/third_party/forked/golang/json:all-srcs",
        "//staging/src/k8s.io/apimachinery/third_party/forked/golang/netutil:all-srcs",
        "//staging/src/k8s.io/apimachinery/third_party/forked/golang/reflect:all-srcs",
    ],
    tags = ["automanaged"],
    visibility = ["//visibility:public"],
)
