{
 "kind": "discovery#restDescription",
 "etag": "\"BgGnx7p-6wsAbOn4St99QhtBGbA/TKLTAqrqg3ZwD--yrgL0HXd_jYw\"",
 "discoveryVersion": "v1",
 "id": "latitude:v1",
 "name": "latitude",
 "version": "v1",
 "revision": "20120710",
 "title": "Google Latitude API",
 "description": "Lets you read and update your current location and work with your location history",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/latitude/v1/using",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/latitude/v1/",
 "basePath": "/latitude/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "latitude/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/latitude.all.best": {
     "description": "Manage your best-available location and location history"
    },
    "https://www.googleapis.com/auth/latitude.all.city": {
     "description": "Manage your city-level location and location history"
    },
    "https://www.googleapis.com/auth/latitude.current.best": {
     "description": "Manage your best-available location"
    },
    "https://www.googleapis.com/auth/latitude.current.city": {
     "description": "Manage your city-level location"
    }
   }
  }
 },
 "features": [
  "dataWrapper"
 ],
 "resources": {
  "currentLocation": {
   "methods": {
    "delete": {
     "id": "latitude.currentLocation.delete",
     "path": "currentLocation",
     "httpMethod": "DELETE",
     "description": "Deletes the authenticated user's current location.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city",
      "https://www.googleapis.com/auth/latitude.current.best",
      "https://www.googleapis.com/auth/latitude.current.city"
     ]
    },
    "get": {
     "id": "latitude.currentLocation.get",
     "path": "currentLocation",
     "httpMethod": "GET",
     "description": "Returns the authenticated user's current location.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city",
      "https://www.googleapis.com/auth/latitude.current.best",
      "https://www.googleapis.com/auth/latitude.current.city"
     ]
    },
    "insert": {
     "id": "latitude.currentLocation.insert",
     "path": "currentLocation",
     "httpMethod": "POST",
     "description": "Updates or creates the user's current location.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city",
      "https://www.googleapis.com/auth/latitude.current.best",
      "https://www.googleapis.com/auth/latitude.current.city"
     ]
    }
   }
  },
  "location": {
   "methods": {
    "delete": {
     "id": "latitude.location.delete",
     "path": "location/{locationId}",
     "httpMethod": "DELETE",
     "description": "Deletes a location from the user's location history.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city"
     ]
    },
    "get": {
     "id": "latitude.location.get",
     "path": "location/{locationId}",
     "httpMethod": "GET",
     "description": "Reads a location from the user's location history.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city"
     ]
    },
    "insert": {
     "id": "latitude.location.insert",
     "path": "location",
     "httpMethod": "POST",
     "description": "Inserts or updates a location in the user's location history.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city"
     ]
    },
    "list": {
     "id": "latitude.location.list",
     "path": "location",
     "httpMethod": "GET",
     "description": "Lists the user's location history.",
     "scopes": [
      "https://www.googleapis.com/auth/latitude.all.best",
      "https://www.googleapis.com/auth/latitude.all.city"
     ]
    }
   }
  }
 }
}
