{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/documents": {
          "description": "View and manage your Google Docs documents"
        },
        "https://www.googleapis.com/auth/documents.readonly": {
          "description": "View your Google Docs documents"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://docs.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Docs",
  "description": "Reads and writes Google Docs documents.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/docs/",
  "fullyEncodeReservedExpansion": true,
  "id": "docs:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://docs.mtls.googleapis.com/",
  "name": "docs",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "documents": {
      "methods": {
        "batchUpdate": {
          "description": "Applies one or more updates to the document.\n\nEach request is validated before\nbeing applied. If any request is not valid, then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how they are applied. Other requests do\nnot need to return information; these each return an empty reply.\nThe order of replies matches that of the requests.\n\nFor example, suppose you call batchUpdate with four upda[...]",
          "flatPath": "v1/documents/{documentId}:batchUpdate",
          "httpMethod": "POST",
          "id": "docs.documents.batchUpdate",
          "path": "v1/documents/{documentId}:batchUpdate",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "create": {
          "description": "Creates a blank document using the title given in the request. Other fields\nin the request, including any provided content, are ignored.\n\nReturns the created document.",
          "flatPath": "v1/documents",
          "httpMethod": "POST",
          "id": "docs.documents.create",
          "path": "v1/documents",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets the latest version of the specified document.",
          "flatPath": "v1/documents/{documentId}",
          "httpMethod": "GET",
          "id": "docs.documents.get",
          "path": "v1/documents/{documentId}",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/documents.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    }
  },
  "revision": "20200221",
  "rootUrl": "https://docs.googleapis.com/",
  "servicePath": "",
  "title": "Google Docs API",
  "version": "v1",
  "version_module": true
}