{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/BNuyD_NaVAV3W_hswlv4FqnMld8\"",
 "discoveryVersion": "v1",
 "id": "admin:datatransfer_v1",
 "name": "admin",
 "canonicalName": "DataTransfer",
 "version": "datatransfer_v1",
 "revision": "20151124",
 "title": "Admin Data Transfer API",
 "description": "Admin Data Transfer API lets you transfer user data from one user to another.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": "admin",
 "documentationLink": "https://developers.google.com/admin-sdk/data-transfer/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/admin/datatransfer/v1/",
 "basePath": "/admin/datatransfer/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "admin/datatransfer/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/admin.datatransfer": {
     "description": "View and manage data transfers between users in your organization"
    },
    "https://www.googleapis.com/auth/admin.datatransfer.readonly": {
     "description": "View data transfers between users in your organization"
    }
   }
  }
 },
 "resources": {
  "applications": {
   "methods": {
    "get": {
     "id": "datatransfer.applications.get",
     "path": "applications/{applicationId}",
     "httpMethod": "GET",
     "description": "Retrieves information about an application for the given application ID.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ]
    },
    "list": {
     "id": "datatransfer.applications.list",
     "path": "applications",
     "httpMethod": "GET",
     "description": "Lists the applications available for data transfer for a customer.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ]
    }
   }
  },
  "transfers": {
   "methods": {
    "get": {
     "id": "datatransfer.transfers.get",
     "path": "transfers/{dataTransferId}",
     "httpMethod": "GET",
     "description": "Retrieves a data transfer request by its resource ID.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ]
    },
    "insert": {
     "id": "datatransfer.transfers.insert",
     "path": "transfers",
     "httpMethod": "POST",
     "description": "Inserts a data transfer request.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer"
     ]
    },
    "list": {
     "id": "datatransfer.transfers.list",
     "path": "transfers",
     "httpMethod": "GET",
     "description": "Lists the transfers for a customer by source user, destination user, or status.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ]
    }
   }
  }
 }
}
