{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/RNf67Qs-KGgGShWEZ1M0BbfJUQg\"",
 "discoveryVersion": "v1",
 "id": "coordinate:v1",
 "name": "coordinate",
 "version": "v1",
 "revision": "20150811",
 "title": "Google Maps Coordinate API",
 "description": "Lets you view and manage jobs in a Coordinate team.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/coordinate/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/coordinate/v1/",
 "basePath": "/coordinate/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "coordinate/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/coordinate": {
     "description": "View and manage your Google Maps Coordinate jobs"
    },
    "https://www.googleapis.com/auth/coordinate.readonly": {
     "description": "View your Google Coordinate jobs"
    }
   }
  }
 },
 "resources": {
  "customFieldDef": {
   "methods": {
    "list": {
     "id": "coordinate.customFieldDef.list",
     "path": "teams/{teamId}/custom_fields",
     "httpMethod": "GET",
     "description": "Retrieves a list of custom field definitions for a team.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    }
   }
  },
  "jobs": {
   "methods": {
    "get": {
     "id": "coordinate.jobs.get",
     "path": "teams/{teamId}/jobs/{jobId}",
     "httpMethod": "GET",
     "description": "Retrieves a job, including all the changes made to the job.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    },
    "insert": {
     "id": "coordinate.jobs.insert",
     "path": "teams/{teamId}/jobs",
     "httpMethod": "POST",
     "description": "Inserts a new job. Only the state field of the job should be set.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate"
     ]
    },
    "list": {
     "id": "coordinate.jobs.list",
     "path": "teams/{teamId}/jobs",
     "httpMethod": "GET",
     "description": "Retrieves jobs created or modified since the given timestamp.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    },
    "patch": {
     "id": "coordinate.jobs.patch",
     "path": "teams/{teamId}/jobs/{jobId}",
     "httpMethod": "PATCH",
     "description": "Updates a job. Fields that are set in the job state will be updated. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate"
     ]
    },
    "update": {
     "id": "coordinate.jobs.update",
     "path": "teams/{teamId}/jobs/{jobId}",
     "httpMethod": "PUT",
     "description": "Updates a job. Fields that are set in the job state will be updated.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate"
     ]
    }
   }
  },
  "location": {
   "methods": {
    "list": {
     "id": "coordinate.location.list",
     "path": "teams/{teamId}/workers/{workerEmail}/locations",
     "httpMethod": "GET",
     "description": "Retrieves a list of locations for a worker.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    }
   }
  },
  "schedule": {
   "methods": {
    "get": {
     "id": "coordinate.schedule.get",
     "path": "teams/{teamId}/jobs/{jobId}/schedule",
     "httpMethod": "GET",
     "description": "Retrieves the schedule for a job.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    },
    "patch": {
     "id": "coordinate.schedule.patch",
     "path": "teams/{teamId}/jobs/{jobId}/schedule",
     "httpMethod": "PATCH",
     "description": "Replaces the schedule of a job with the provided schedule. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate"
     ]
    },
    "update": {
     "id": "coordinate.schedule.update",
     "path": "teams/{teamId}/jobs/{jobId}/schedule",
     "httpMethod": "PUT",
     "description": "Replaces the schedule of a job with the provided schedule.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate"
     ]
    }
   }
  },
  "team": {
   "methods": {
    "list": {
     "id": "coordinate.team.list",
     "path": "teams",
     "httpMethod": "GET",
     "description": "Retrieves a list of teams for a user.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    }
   }
  },
  "worker": {
   "methods": {
    "list": {
     "id": "coordinate.worker.list",
     "path": "teams/{teamId}/workers",
     "httpMethod": "GET",
     "description": "Retrieves a list of workers in a team.",
     "scopes": [
      "https://www.googleapis.com/auth/coordinate",
      "https://www.googleapis.com/auth/coordinate.readonly"
     ]
    }
   }
  }
 }
}
