{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/RGkzhqSB3FajvpNvflV8YsVuejw\"",
 "discoveryVersion": "v1",
 "id": "youtubereporting:v1",
 "name": "youtubereporting",
 "canonicalName": "YouTube Reporting",
 "version": "v1",
 "revision": "20151026",
 "title": "YouTube Reporting API",
 "description": "An API to schedule reporting jobs and download the resulting bulk data reports about YouTube channels, videos etc. in the form of CSV files.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/youtube/reporting/v1/reports/",
 "protocol": "rest",
 "baseUrl": "https://youtubereporting.googleapis.com/",
 "basePath": "/",
 "rootUrl": "https://youtubereporting.googleapis.com/",
 "servicePath": "",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
     "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
    },
    "https://www.googleapis.com/auth/yt-analytics.readonly": {
     "description": "View YouTube Analytics reports for your YouTube content"
    }
   }
  }
 },
 "resources": {
  "media": {
   "methods": {
    "download": {
     "id": "youtubereporting.media.download",
     "path": "v1/media/{+resourceName}",
     "httpMethod": "GET",
     "description": "Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": true
    }
   }
  },
  "reportTypes": {
   "methods": {
    "list": {
     "id": "youtubereporting.reportTypes.list",
     "path": "v1/reportTypes",
     "httpMethod": "GET",
     "description": "Lists report types.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    }
   }
  },
  "jobs": {
   "methods": {
    "create": {
     "id": "youtubereporting.jobs.create",
     "path": "v1/jobs",
     "httpMethod": "POST",
     "description": "Creates a job and returns it.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    },
    "list": {
     "id": "youtubereporting.jobs.list",
     "path": "v1/jobs",
     "httpMethod": "GET",
     "description": "Lists jobs.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    },
    "get": {
     "id": "youtubereporting.jobs.get",
     "path": "v1/jobs/{jobId}",
     "httpMethod": "GET",
     "description": "Gets a job.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    },
    "delete": {
     "id": "youtubereporting.jobs.delete",
     "path": "v1/jobs/{jobId}",
     "httpMethod": "DELETE",
     "description": "Deletes a job.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    }
   },
   "resources": {
    "reports": {
     "methods": {
      "list": {
       "id": "youtubereporting.jobs.reports.list",
       "path": "v1/jobs/{jobId}/reports",
       "httpMethod": "GET",
       "description": "Lists reports created by a specific job. Returns NOT_FOUND if the job does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
        "https://www.googleapis.com/auth/yt-analytics.readonly"
       ]
      },
      "get": {
       "id": "youtubereporting.jobs.reports.get",
       "path": "v1/jobs/{jobId}/reports/{reportId}",
       "httpMethod": "GET",
       "description": "Gets the metadata of a specific report.",
       "scopes": [
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
        "https://www.googleapis.com/auth/yt-analytics.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
