{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/_HDQvvrmU1Cf0bBIzjf-H39NJ10\"",
 "discoveryVersion": "v1",
 "id": "fusiontables:v1",
 "name": "fusiontables",
 "version": "v1",
 "revision": "20150226",
 "title": "Fusion Tables API",
 "description": "API for working with Fusion Tables data.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/fusiontables",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/fusiontables/v1/",
 "basePath": "/fusiontables/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "fusiontables/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/fusiontables": {
     "description": "Manage your Fusion Tables"
    },
    "https://www.googleapis.com/auth/fusiontables.readonly": {
     "description": "View your Fusion Tables"
    }
   }
  }
 },
 "resources": {
  "column": {
   "methods": {
    "delete": {
     "id": "fusiontables.column.delete",
     "path": "tables/{tableId}/columns/{columnId}",
     "httpMethod": "DELETE",
     "description": "Deletes the column.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "get": {
     "id": "fusiontables.column.get",
     "path": "tables/{tableId}/columns/{columnId}",
     "httpMethod": "GET",
     "description": "Retrieves a specific column by its id.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "insert": {
     "id": "fusiontables.column.insert",
     "path": "tables/{tableId}/columns",
     "httpMethod": "POST",
     "description": "Adds a new column to the table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "list": {
     "id": "fusiontables.column.list",
     "path": "tables/{tableId}/columns",
     "httpMethod": "GET",
     "description": "Retrieves a list of columns.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "patch": {
     "id": "fusiontables.column.patch",
     "path": "tables/{tableId}/columns/{columnId}",
     "httpMethod": "PATCH",
     "description": "Updates the name or type of an existing column. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "update": {
     "id": "fusiontables.column.update",
     "path": "tables/{tableId}/columns/{columnId}",
     "httpMethod": "PUT",
     "description": "Updates the name or type of an existing column.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    }
   }
  },
  "query": {
   "methods": {
    "sql": {
     "id": "fusiontables.query.sql",
     "path": "query",
     "httpMethod": "POST",
     "description": "Executes an SQL SELECT/INSERT/UPDATE/DELETE/SHOW/DESCRIBE/CREATE statement.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ],
     "supportsMediaDownload": true
    },
    "sqlGet": {
     "id": "fusiontables.query.sqlGet",
     "path": "query",
     "httpMethod": "GET",
     "description": "Executes an SQL SELECT/SHOW/DESCRIBE statement.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ],
     "supportsMediaDownload": true
    }
   }
  },
  "style": {
   "methods": {
    "delete": {
     "id": "fusiontables.style.delete",
     "path": "tables/{tableId}/styles/{styleId}",
     "httpMethod": "DELETE",
     "description": "Deletes a style.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "get": {
     "id": "fusiontables.style.get",
     "path": "tables/{tableId}/styles/{styleId}",
     "httpMethod": "GET",
     "description": "Gets a specific style.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "insert": {
     "id": "fusiontables.style.insert",
     "path": "tables/{tableId}/styles",
     "httpMethod": "POST",
     "description": "Adds a new style for the table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "list": {
     "id": "fusiontables.style.list",
     "path": "tables/{tableId}/styles",
     "httpMethod": "GET",
     "description": "Retrieves a list of styles.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "patch": {
     "id": "fusiontables.style.patch",
     "path": "tables/{tableId}/styles/{styleId}",
     "httpMethod": "PATCH",
     "description": "Updates an existing style. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "update": {
     "id": "fusiontables.style.update",
     "path": "tables/{tableId}/styles/{styleId}",
     "httpMethod": "PUT",
     "description": "Updates an existing style.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    }
   }
  },
  "table": {
   "methods": {
    "copy": {
     "id": "fusiontables.table.copy",
     "path": "tables/{tableId}/copy",
     "httpMethod": "POST",
     "description": "Copies a table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "delete": {
     "id": "fusiontables.table.delete",
     "path": "tables/{tableId}",
     "httpMethod": "DELETE",
     "description": "Deletes a table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "get": {
     "id": "fusiontables.table.get",
     "path": "tables/{tableId}",
     "httpMethod": "GET",
     "description": "Retrieves a specific table by its id.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "importRows": {
     "id": "fusiontables.table.importRows",
     "path": "tables/{tableId}/import",
     "httpMethod": "POST",
     "description": "Import more rows into a table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ],
     "supportsMediaUpload": true
    },
    "importTable": {
     "id": "fusiontables.table.importTable",
     "path": "tables/import",
     "httpMethod": "POST",
     "description": "Import a new table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ],
     "supportsMediaUpload": true
    },
    "insert": {
     "id": "fusiontables.table.insert",
     "path": "tables",
     "httpMethod": "POST",
     "description": "Creates a new table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "list": {
     "id": "fusiontables.table.list",
     "path": "tables",
     "httpMethod": "GET",
     "description": "Retrieves a list of tables a user owns.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "patch": {
     "id": "fusiontables.table.patch",
     "path": "tables/{tableId}",
     "httpMethod": "PATCH",
     "description": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "update": {
     "id": "fusiontables.table.update",
     "path": "tables/{tableId}",
     "httpMethod": "PUT",
     "description": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    }
   }
  },
  "task": {
   "methods": {
    "delete": {
     "id": "fusiontables.task.delete",
     "path": "tables/{tableId}/tasks/{taskId}",
     "httpMethod": "DELETE",
     "description": "Deletes the task, unless already started.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "get": {
     "id": "fusiontables.task.get",
     "path": "tables/{tableId}/tasks/{taskId}",
     "httpMethod": "GET",
     "description": "Retrieves a specific task by its id.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "list": {
     "id": "fusiontables.task.list",
     "path": "tables/{tableId}/tasks",
     "httpMethod": "GET",
     "description": "Retrieves a list of tasks.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    }
   }
  },
  "template": {
   "methods": {
    "delete": {
     "id": "fusiontables.template.delete",
     "path": "tables/{tableId}/templates/{templateId}",
     "httpMethod": "DELETE",
     "description": "Deletes a template",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "get": {
     "id": "fusiontables.template.get",
     "path": "tables/{tableId}/templates/{templateId}",
     "httpMethod": "GET",
     "description": "Retrieves a specific template by its id",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "insert": {
     "id": "fusiontables.template.insert",
     "path": "tables/{tableId}/templates",
     "httpMethod": "POST",
     "description": "Creates a new template for the table.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "list": {
     "id": "fusiontables.template.list",
     "path": "tables/{tableId}/templates",
     "httpMethod": "GET",
     "description": "Retrieves a list of templates.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables",
      "https://www.googleapis.com/auth/fusiontables.readonly"
     ]
    },
    "patch": {
     "id": "fusiontables.template.patch",
     "path": "tables/{tableId}/templates/{templateId}",
     "httpMethod": "PATCH",
     "description": "Updates an existing template. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    },
    "update": {
     "id": "fusiontables.template.update",
     "path": "tables/{tableId}/templates/{templateId}",
     "httpMethod": "PUT",
     "description": "Updates an existing template",
     "scopes": [
      "https://www.googleapis.com/auth/fusiontables"
     ]
    }
   }
  }
 }
}
