{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Cloud Search",
  "description": "Cloud Search provides cloud-based search capabilities over G Suite data.  The Cloud Search API allows indexing of non-G Suite data into Cloud Search.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "fullyEncodeReservedExpansion": true,
  "id": "cloudsearch:v1",
  "kind": "discovery#restDescription",
  "name": "cloudsearch",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "checkAccess": {
                  "description": "Checks whether an item is accessible by specified principal.\n\n**Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "httpMethod": "POST",
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                },
                "searchByViewUrl": {
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided\nin the request.\n\n**Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "httpMethod": "POST",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              },
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "description": "List all unmapped identities for a specific item.\n\n**Note:** This API requires an admin account to execute.",
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "httpMethod": "GET",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "path": "v1/debug/{+parent}/unmappedids",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "description": "Lists names of items associated with an unmapped identity.\n\n**Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "httpMethod": "GET",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            },
            "unmappedids": {
              "methods": {
                "list": {
                  "description": "Lists unmapped user identities for an identity source.\n\n**Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "httpMethod": "GET",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "path": "v1/debug/{+parent}/unmappedids",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "deleteSchema": {
              "description": "Deletes the schema of a data source.\n\n**Note:** This API requires an admin or service account to execute.",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "DELETE",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "getSchema": {
              "description": "Gets the schema of a data source.\n\n**Note:** This API requires an admin or service account to execute.",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "GET",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "updateSchema": {
              "description": "Updates the schema of a data source. This method does not perform\nincremental updates to the schema. Instead, this method updates the schema\nby overwriting the entire schema.\n\n**Note:** This API requires an admin or service account to execute.",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "PUT",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          },
          "resources": {
            "items": {
              "methods": {
                "delete": {
                  "description": "Deletes Item resource for the\nspecified resource name. This API requires an admin or service account\nto execute. The service account used is the one whitelisted in the\ncorresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "httpMethod": "DELETE",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "deleteQueueItems": {
                  "description": "Deletes all items in a queue. This method is useful for deleting stale\nitems.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "get": {
                  "description": "Gets Item resource by item name.\n\nThis API requires an admin or service account to execute.  The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "index": {
                  "description": "Updates Item ACL, metadata, and\ncontent. It will insert the Item if it\ndoes not exist.\nThis method does not support partial updates.  Fields with no provided\nvalues are cleared out in the Cloud Search index.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "path": "v1/indexing/{+name}:index",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "list": {
                  "description": "Lists all or a subset of Item resources.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "path": "v1/indexing/{+name}/items",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "poll": {
                  "description": "Polls for unreserved items from the indexing queue and marks a\nset as reserved, starting with items that have\nthe oldest timestamp from the highest priority\nItemStatus.\nThe priority order is as follows: \u003cbr /\u003e\nERROR\n\u003cbr /\u003e\nMODIFIED\n\u003cbr /\u003e\nNEW_ITEM\n\u003cbr /\u003e\nACCEPTED\n\u003cbr /\u003e\nReserving items ensures that polling from other threads\ncannot create overlapping sets.\n\nAfter handling the reserved items, the c[...]",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1/indexing/{+name}/items:poll",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "push": {
                  "description": "Pushes an item onto a queue for later polling and updating.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "path": "v1/indexing/{+name}:push",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "unreserve": {
                  "description": "Unreserves all items from a queue, making them all eligible to be\npolled.  This method is useful for resetting the indexing queue\nafter a connector has been restarted.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "upload": {
                  "description": "Creates an upload session for uploading item content. For items smaller\nthan 100 KB, it's easier to embed the content\ninline within\nan index request.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "path": "v1/indexing/{+name}:upload",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "description": "Uploads media for indexing.\n\nThe upload endpoint supports direct and resumable upload protocols and\nis intended for large items that can not be\n[inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent).\nTo index large content:\n\n1. Call\n   indexing.datasources.items.upload\n   with the resource name to begin an upload session and retrieve the\n   UploadItemRef.\n1. Call media.upload t[...]",
          "flatPath": "v1/media/{mediaId}",
          "httpMethod": "POST",
          "id": "cloudsearch.media.upload",
          "path": "v1/media/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "supportsMediaUpload": true
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "description": "Gets the latest state of a long-running operation.  Clients can use this\nmethod to poll the operation result at intervals as recommended by the API\nservice.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "id": "cloudsearch.operations.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ]
        }
      }
    },
    "query": {
      "methods": {
        "search": {
          "description": "The Cloud Search Query API provides the search method, which returns\nthe most relevant results from a user query.  The results can come from\nG Suite Apps, such as Gmail or Google Drive, or they can come from data\nthat you have indexed from a third party.\n\n**Note:** This API requires a standard end user account to execute.\nA service account can't perform Query API requests directly; to use a\nservice account to perform queries, set up [G Suite domain-wide delegatio[...]",
          "flatPath": "v1/query/search",
          "httpMethod": "POST",
          "id": "cloudsearch.query.search",
          "path": "v1/query/search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        },
        "suggest": {
          "description": "Provides suggestions for autocompleting the query.\n\n**Note:** This API requires a standard end user account to execute.\nA service account can't perform Query API requests directly; to use a\nservice account to perform queries, set up [G Suite domain-wide delegation\nof\nauthority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "flatPath": "v1/query/suggest",
          "httpMethod": "POST",
          "id": "cloudsearch.query.suggest",
          "path": "v1/query/suggest",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "description": "Returns list of sources that user can use for Search and Suggest APIs.\n\n**Note:** This API requires a standard end user account to execute.\nA service account can't perform Query API requests directly; to use a\nservice account to perform queries, set up [G Suite domain-wide delegation\nof\nauthority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
              "flatPath": "v1/query/sources",
              "httpMethod": "GET",
              "id": "cloudsearch.query.sources.list",
              "path": "v1/query/sources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ]
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "datasources": {
          "methods": {
            "create": {
              "description": "Creates a datasource.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.datasources.create",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "delete": {
              "description": "Deletes a datasource.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "DELETE",
              "id": "cloudsearch.settings.datasources.delete",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "get": {
              "description": "Gets a datasource.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.datasources.get",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "list": {
              "description": "Lists datasources.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.datasources.list",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "update": {
              "description": "Updates a datasource.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "PUT",
              "id": "cloudsearch.settings.datasources.update",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          }
        },
        "searchapplications": {
          "methods": {
            "create": {
              "description": "Creates a search application.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.searchapplications.create",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "delete": {
              "description": "Deletes a search application.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "DELETE",
              "id": "cloudsearch.settings.searchapplications.delete",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "get": {
              "description": "Gets the specified search application.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.get",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "list": {
              "description": "Lists all search applications.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.list",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "reset": {
              "description": "Resets a search application to default settings. This will return an empty\nresponse.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.searchapplications.reset",
              "path": "v1/settings/{+name}:reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "update": {
              "description": "Updates a search application.\n\n**Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "PUT",
              "id": "cloudsearch.settings.searchapplications.update",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            }
          }
        }
      }
    },
    "stats": {
      "methods": {
        "getIndex": {
          "description": "Gets indexed item statistics aggreggated across all data sources. This\nAPI only returns statistics for previous dates; it doesn't return\nstatistics for the current day.\n\n**Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/index",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getIndex",
          "path": "v1/stats/index",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getQuery": {
          "description": "Get the query statistics for customer.\n\n**Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/query",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getQuery",
          "path": "v1/stats/query",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getSession": {
          "description": "Get the # of search sessions, % of successful sessions with a click query\nstatistics for customer.\n\n**Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/session",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getSession",
          "path": "v1/stats/session",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getUser": {
          "description": "Get the users statistics for customer.\n\n**Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/user",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getUser",
          "path": "v1/stats/user",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        }
      },
      "resources": {
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "description": "Gets indexed item statistics for a single data source.\n\n**Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "path": "v1/stats/index/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the query statistics for search application.\n\n**Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "path": "v1/stats/query/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the # of search sessions, % of successful sessions with a click query\nstatistics for search application.\n\n**Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "path": "v1/stats/session/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        },
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the users statistics for search application.\n\n**Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.user.searchapplications.get",
                  "path": "v1/stats/user/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "revision": "20200212",
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "schemas": {
    "BooleanOperatorOptions": {
      "description": "Used to provide a search operator for boolean properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "id": "BooleanOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nboolean property. For example, if operatorName is *closed* and the\nproperty's name is *isClosed*, then queries like\n*closed:\u0026lt;value\u0026gt;* will show results only where the value of the\nproperty named *isClosed* matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;value\u0026gt;* without an operator will return\nall items where *\u0026lt;value\u0026gt[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "BooleanPropertyOptions": {
      "description": "Options for boolean properties.",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "BooleanOperatorOptions",
          "description": "If set, describes how the boolean should be used as a search operator."
        }
      },
      "type": "object"
    },
    "CheckAccessResponse": {
      "id": "CheckAccessResponse",
      "properties": {
        "hasAccess": {
          "description": "Returns true if principal has access.  Returns false otherwise.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "CompositeFilter": {
      "id": "CompositeFilter",
      "properties": {
        "logicOperator": {
          "description": "The logic operator of the sub filter.",
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "type": "string"
        },
        "subFilters": {
          "description": "Sub filters.",
          "items": {
            "$ref": "Filter"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CustomerIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "CustomerIndexStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which statistics were calculated."
        },
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CustomerQueryStats": {
      "id": "CustomerQueryStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CustomerUserStats": {
      "id": "CustomerUserStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "format": "int64",
          "type": "string"
        },
        "sevenDaysActiveUsersCount": {
          "description": "The count of unique active users in the past seven days",
          "format": "int64",
          "type": "string"
        },
        "thirtyDaysActiveUsersCount": {
          "description": "The count of unique active users in the past thirty days",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DataSource": {
      "description": "Datasource is a logical namespace for items to be indexed.\nAll items must belong to a datasource.  This is the prerequisite before\nitems can be indexed into Cloud Search.",
      "id": "DataSource",
      "properties": {
        "disableModifications": {
          "description": "If true, Indexing API rejects any modification calls to this datasource\nsuch as create, update, and delete.\nDisabling this does not imply halting process of previously\naccepted data.",
          "type": "boolean"
        },
        "disableServing": {
          "description": "Disable serving any search or assist results.",
          "type": "boolean"
        },
        "displayName": {
          "description": "Required. Display name of the datasource\nThe maximum length is 300 characters.",
          "type": "string"
        },
        "indexingServiceAccounts": {
          "description": "List of service accounts that have indexing access.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "itemsVisibility": {
          "description": "This field restricts visibility to items at the datasource level. Items\nwithin the datasource are restricted to the union of users and groups\nincluded in this field. Note that, this does not ensure access to a\nspecific item, as users need to have ACL permissions on the contained\nitems. This ensures a high level access on the entire datasource, and\nthat the individual items are not shared outside this visibility.",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "type": "array"
        },
        "name": {
          "description": "Name of the datasource resource.\nFormat: datasources/{source_id}.\n\u003cbr /\u003eThe name is ignored when creating a datasource.",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "shortName": {
          "description": "A short name or alias for the source.  This value will be used to match the\n'source' operator. For example, if the short name is *\u0026lt;value\u0026gt;* then\nqueries like *source:\u0026lt;value\u0026gt;* will only return results for this\nsource. The value must be unique across all datasources. The value must\nonly contain alphanumeric characters (a-zA-Z0-9). The value cannot start\nwith 'google' and cannot be one of the following: mail, gmail, docs, drive,\ngroups,[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DataSourceIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "DataSourceIndexStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which index stats were calculated. If the date of request is not\nthe current date then stats calculated on the next day are returned. Stats\nare calculated close to mid night in this case. If date of request is\ncurrent date, then real time stats are returned."
        },
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DataSourceRestriction": {
      "description": "Restriction on Datasource.",
      "id": "DataSourceRestriction",
      "properties": {
        "filterOptions": {
          "description": "Filter options restricting the results. If multiple filters\nare present, they are grouped by object type before joining.\nFilters with the same object type are joined conjunctively, then\nthe resulting expressions are joined disjunctively.\n\nThe maximum number of elements is 20.\n\nNOTE: Suggest API supports only few filters at the moment:\n  \"objecttype\", \"type\" and \"mimetype\".\nFor now, schema specific filters cannot be used to filter suggestions.",
          "items": {
            "$ref": "FilterOptions"
          },
          "type": "array"
        },
        "source": {
          "$ref": "Source",
          "description": "The source of restriction."
        }
      },
      "type": "object"
    },
    "Date": {
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "id": "Date",
      "properties": {
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "format": "int32",
          "type": "integer"
        },
        "month": {
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32",
          "type": "integer"
        },
        "year": {
          "description": "Year of date. Must be from 1 to 9999.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "DateOperatorOptions": {
      "description": "Optional. Provides a search operator for date properties.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "id": "DateOperatorOptions",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ndate property using the greater-than operator. For example, if\ngreaterThanOperatorName is *closedafter* and the property's name is\n*closeDate*, then queries like *closedafter:\u0026lt;value\u0026gt;* will\nshow results only where the value of the property named *closeDate* is\nlater than *\u0026lt;value\u0026gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length [...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ndate property using the less-than operator. For example, if\nlessThanOperatorName is *closedbefore* and the property's name is\n*closeDate*, then queries like *closedbefore:\u0026lt;value\u0026gt;* will\nshow results only where the value of the property named *closeDate* is\nearlier than *\u0026lt;value\u0026gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is[...]",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the actual string required in the query in order to isolate the\ndate property. For example, suppose an issue tracking schema object\nhas a property named *closeDate* that specifies an operator with an\noperatorName of *closedon*. For searches on that data, queries like\n*closedon:\u0026lt;value\u0026gt;* will show results only where the value of the\n*closeDate* property matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;va[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DatePropertyOptions": {
      "description": "Options for date properties.",
      "id": "DatePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DateOperatorOptions",
          "description": "If set, describes how the date should be used as a search operator."
        }
      },
      "type": "object"
    },
    "DateValues": {
      "description": "List of date values.",
      "id": "DateValues",
      "properties": {
        "values": {
          "items": {
            "$ref": "Date"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DebugOptions": {
      "description": "Shared request debug options for all cloudsearch RPC methods.",
      "id": "DebugOptions",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field.\nOtherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "queue": {
          "description": "Name of a queue to delete items from.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DisplayedProperty": {
      "description": "A reference to a top-level property within the object that should be\ndisplayed in search results. The values of the chosen properties will be\ndisplayed in the search results along with the\ndislpay label\nfor that property if one is specified. If a display label is not specified,\nonly the values will be shown.",
      "id": "DisplayedProperty",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition\nfor the object. If the name is not a defined property in the schema, an\nerror will be given when attempting to update the schema.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DoubleOperatorOptions": {
      "description": "Used to provide a search operator for double properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "id": "DoubleOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to use the\ndouble property in sorting or as a facet.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DoublePropertyOptions": {
      "description": "Options for double properties.",
      "id": "DoublePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DoubleOperatorOptions",
          "description": "If set, describes how the double should be used as a search operator."
        }
      },
      "type": "object"
    },
    "DoubleValues": {
      "description": "List of double values.",
      "id": "DoubleValues",
      "properties": {
        "values": {
          "items": {
            "format": "double",
            "type": "number"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DriveFollowUpRestrict": {
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "id": "DriveFollowUpRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "DriveLocationRestrict": {
      "description": "Drive location search restricts (e.g. \"is:starred\").",
      "id": "DriveLocationRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "DriveMimeTypeRestrict": {
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
      "id": "DriveMimeTypeRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "DriveTimeSpanRestrict": {
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "id": "DriveTimeSpanRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EmailAddress": {
      "description": "A person's email address.",
      "id": "EmailAddress",
      "properties": {
        "emailAddress": {
          "description": "The email address.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumOperatorOptions": {
      "description": "Used to provide a search operator for enum properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched. For example, if you provide no\noperator for a *priority* enum property with possible values *p0* and *p1*,\na query that contains the term *p0* will return items that have *p0* as the\nvalue of the *priority* property, as well as any items that contain the\nstring *p0* in other fields. If yo[...]",
      "id": "EnumOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nenum property. For example, if operatorName is *priority* and the\nproperty's name is *priorityVal*, then queries like\n*priority:\u0026lt;value\u0026gt;* will show results only where the value of the\nproperty named *priorityVal* matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;value\u0026gt;* without an operator will return\nall items where *\u0026lt;value\[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumPropertyOptions": {
      "description": "Options for enum properties, which allow you to define a restricted set of\nstrings to match user queries, set rankings for those string values, and\ndefine an operator name to be paired with those strings so that users can\nnarrow results to only items with a specific value. For example, for items in\na request tracking system with priority information, you could define *p0* as\nan allowable enum value and tie this enum to the operator name *priority* so\nthat search users[...]",
      "id": "EnumPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        },
        "orderedRanking": {
          "description": "Used to specify the ordered ranking for the enumeration that determines how\nthe integer values provided in the possible EnumValuePairs are used to rank\nresults. If specified, integer values must be provided for all possible\nEnumValuePair values given for this property. Can only be used if\nisRepeatable\nis false.",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "enumDescriptions": [
            "There is no ranking order for the property. Results will not be adjusted\nby this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower\nranking.",
            "This property is ranked in descending order. Lower values indicate\nhigher ranking."
          ],
          "type": "string"
        },
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All\nEnumValuePairs must provide a string value. If you specify an integer value\nfor one EnumValuePair, then all possible EnumValuePairs must provide an\ninteger value. Both the string value and integer value must be unique over\nall possible values. Once set, possible values cannot be removed or\nmodified. If you supply an ordered ranking and think you might insert\nadditional enum values in the future, leave g[...]",
          "items": {
            "$ref": "EnumValuePair"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnumValuePair": {
      "description": "The enumeration value pair defines two things: a required string value and\nan optional integer value. The string value defines the necessary query\nterm required to retrieve that item, such as *p0* for a priority item.\nThe integer value determines the ranking of that string value relative\nto other enumerated values for the same property. For example, you might\nassociate *p0* with *0* and define another enum pair such as *p1* and *1*.\nYou must use the integer value in c[...]",
      "id": "EnumValuePair",
      "properties": {
        "integerValue": {
          "description": "The integer value of the EnumValuePair which must be non-negative.\nOptional.",
          "format": "int32",
          "type": "integer"
        },
        "stringValue": {
          "description": "The string value of the EnumValuePair.\nThe maximum length is 32 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumValues": {
      "description": "List of enum values.",
      "id": "EnumValues",
      "properties": {
        "values": {
          "description": "The maximum allowable length for string values is 32 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ErrorInfo": {
      "description": "Error information about the response.",
      "id": "ErrorInfo",
      "properties": {
        "errorMessages": {
          "items": {
            "$ref": "ErrorMessage"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ErrorMessage": {
      "description": "Error message per source response.",
      "id": "ErrorMessage",
      "properties": {
        "errorMessage": {
          "type": "string"
        },
        "source": {
          "$ref": "Source"
        }
      },
      "type": "object"
    },
    "FacetBucket": {
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise\neither a single value OR a contiguous range of values, depending on the\ntype of the field bucketed.\nFacetBucket is currently used only for returning the response object.",
      "id": "FacetBucket",
      "properties": {
        "count": {
          "description": "Number of results that match the bucket value. Counts are only returned\nfor searches when count accuracy is ensured. Can be empty.",
          "format": "int32",
          "type": "integer"
        },
        "percentage": {
          "description": "Percent of results that match the bucket value. This value is between\n(0-100]. Percentages are returned for all searches, but are an estimate.\nBecause percentages are always returned, you should render percentages\ninstead of counts.",
          "format": "int32",
          "type": "integer"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "type": "object"
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one\nFacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "properties": {
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet.\nDefaults to 10.\nMaximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "objectType": {
          "description": "If object_type is set, only those objects of that type will be used to\ncompute facets. If empty, then all objects will be used to compute facets.",
          "type": "string"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see\ncloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id}\nIf empty, all data sources will be used.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "FacetResult": {
      "description": "Source specific facet response",
      "id": "FacetResult",
      "properties": {
        "buckets": {
          "description": "FacetBuckets for values in response containing at least a single result.",
          "items": {
            "$ref": "FacetBucket"
          },
          "type": "array"
        },
        "objectType": {
          "description": "Object type for which facet results are returned. Can be empty.",
          "type": "string"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see\ncloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name for which facet results are returned. Will not be empty.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "FieldViolation": {
      "id": "FieldViolation",
      "properties": {
        "description": {
          "description": "Description of the error.",
          "type": "string"
        },
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Filter": {
      "description": "A generic way of expressing filters in a query, which supports two\napproaches: \u003cbr/\u003e\u003cbr/\u003e\n**1. Setting a ValueFilter.** The name must match an operator_name defined in\nthe schema for your data source.\n\u003cbr/\u003e\n**2. Setting a CompositeFilter.** The filters are evaluated\nusing the logical operator. The top-level operators can only be either an AND\nor a NOT. AND can appear only at the top-most level. OR can appear only under\na top-level AND."[...]",
      "id": "Filter",
      "properties": {
        "compositeFilter": {
          "$ref": "CompositeFilter"
        },
        "valueFilter": {
          "$ref": "ValueFilter"
        }
      },
      "type": "object"
    },
    "FilterOptions": {
      "description": "Filter options to be applied on query.",
      "id": "FilterOptions",
      "properties": {
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        },
        "objectType": {
          "description": "If object_type is set, only objects of that type are returned. This should\ncorrespond to the name of the object that was registered within the\ndefinition of schema. The maximum length is 256 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "FreshnessOptions": {
      "description": "Indicates which freshness property to use when adjusting search ranking for\nan item. Fresher, more recent dates indicate higher quality. Use the\nfreshness option property that best works with your data. For fileshare\ndocuments, last modified time is most relevant. For calendar event data,\nthe time when the event occurs is a more relevant freshness indicator. In\nthis way, calendar events that occur closer to the time of the search query\nare considered higher quality an[...]",
      "id": "FreshnessOptions",
      "properties": {
        "freshnessDuration": {
          "description": "The duration after which an object should be considered\nstale. The default value is 180 days (in seconds).",
          "format": "google-duration",
          "type": "string"
        },
        "freshnessProperty": {
          "description": "This property indicates the freshness level of the object in the index.\nIf set, this property must be a top-level property within the\nproperty definitions\nand it must be a\ntimestamp type\nor\ndate type.\nOtherwise, the Indexing API uses\nupdateTime\nas the freshness indicator.\nThe maximum length is 256 characters.\n\nWhen a property is used to calculate fresheness, the value defaults\nto 2 years from the current time.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "GSuitePrincipal": {
      "id": "GSuitePrincipal",
      "properties": {
        "gsuiteDomain": {
          "description": "This principal represents all users of the G Suite domain of the\ncustomer.",
          "type": "boolean"
        },
        "gsuiteGroupEmail": {
          "description": "This principal references a G Suite group account",
          "type": "string"
        },
        "gsuiteUserEmail": {
          "description": "This principal references a G Suite user account",
          "type": "string"
        }
      },
      "type": "object"
    },
    "GetCustomerIndexStatsResponse": {
      "id": "GetCustomerIndexStatsResponse",
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "items": {
            "$ref": "CustomerIndexStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetCustomerQueryStatsResponse": {
      "id": "GetCustomerQueryStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerQueryStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetCustomerSessionStatsResponse": {
      "id": "GetCustomerSessionStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerSessionStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetCustomerUserStatsResponse": {
      "id": "GetCustomerUserStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerUserStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetDataSourceIndexStatsResponse": {
      "id": "GetDataSourceIndexStatsResponse",
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "items": {
            "$ref": "DataSourceIndexStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetSearchApplicationQueryStatsResponse": {
      "id": "GetSearchApplicationQueryStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationQueryStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetSearchApplicationSessionStatsResponse": {
      "id": "GetSearchApplicationSessionStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationSessionStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetSearchApplicationUserStatsResponse": {
      "id": "GetSearchApplicationUserStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationUserStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "HtmlOperatorOptions": {
      "description": "Used to provide a search operator for html properties. This is optional.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "id": "HtmlOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nhtml property. For example, if operatorName is *subject* and the\nproperty's name is *subjectLine*, then queries like\n*subject:\u0026lt;value\u0026gt;* will show results only where the value of the\nproperty named *subjectLine* matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;value\u0026gt;* without an operator will return\nall items where *\u0026lt;value\u0[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "HtmlPropertyOptions": {
      "description": "Options for html properties.",
      "id": "HtmlPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "HtmlOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        },
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the\nfield when used for retrieval. Can only be set to DEFAULT or NONE."
        }
      },
      "type": "object"
    },
    "HtmlValues": {
      "description": "List of html values.",
      "id": "HtmlValues",
      "properties": {
        "values": {
          "description": "The maximum allowable length for html values is 2048 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "IndexItemOptions": {
      "id": "IndexItemOptions",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow gsuite principals that do not\nexist or are deleted in the index request.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "IndexItemRequest": {
      "id": "IndexItemRequest",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        },
        "item": {
          "$ref": "Item",
          "description": "Name of the item.  Format:\ndatasources/{source_id}/items/{item_id}"
        },
        "mode": {
          "description": "Required. The RequestMode for this request.",
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ],
          "enumDescriptions": [
            "Priority is not specified in the update request.\nLeaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the\ncaller."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "IntegerOperatorOptions": {
      "description": "Used to provide a search operator for integer properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "id": "IntegerOperatorOptions",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property using the greater-than operator. For example, if\ngreaterThanOperatorName is *priorityabove* and the property's name is\n*priorityVal*, then queries like *priorityabove:\u0026lt;value\u0026gt;* will\nshow results only where the value of the property named *priorityVal* is\ngreater than *\u0026lt;value\u0026gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe ma[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property using the less-than operator. For example, if\nlessThanOperatorName is *prioritybelow* and the property's name is\n*priorityVal*, then queries like *prioritybelow:\u0026lt;value\u0026gt;* will\nshow results only where the value of the property named *priorityVal* is\nless than *\u0026lt;value\u0026gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum len[...]",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property. For example, if operatorName is *priority* and the\nproperty's name is *priorityVal*, then queries like\n*priority:\u0026lt;value\u0026gt;* will show results only where the value of the\nproperty named *priorityVal* matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;value\u0026gt;* without an operator will return\nall items where *\u0026lt;val[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "IntegerPropertyOptions": {
      "description": "Options for integer properties.",
      "id": "IntegerPropertyOptions",
      "properties": {
        "maximumValue": {
          "description": "The maximum value of the property. The minimum and maximum values for the\nproperty are used to rank results according to the\nordered ranking.\nIndexing requests with values greater than the maximum are accepted and\nranked with the same weight as items indexed with the maximum value.",
          "format": "int64",
          "type": "string"
        },
        "minimumValue": {
          "description": "The minimum value of the property. The minimum and maximum values for the\nproperty are used to rank results according to the\nordered ranking.\nIndexing requests with values less than the minimum are accepted and\nranked with the same weight as items indexed with the minimum value.",
          "format": "int64",
          "type": "string"
        },
        "operatorOptions": {
          "$ref": "IntegerOperatorOptions",
          "description": "If set, describes how the integer should be used as a search operator."
        },
        "orderedRanking": {
          "description": "Used to specify the ordered ranking for the integer. Can only be used if\nisRepeatable\nis false.",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "enumDescriptions": [
            "There is no ranking order for the property. Results will not be adjusted\nby this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower\nranking.",
            "This property is ranked in descending order. Lower values indicate\nhigher ranking."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "IntegerValues": {
      "description": "List of integer values.",
      "id": "IntegerValues",
      "properties": {
        "values": {
          "items": {
            "format": "int64",
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Interaction": {
      "description": "Represents an interaction between a user and an item.",
      "id": "Interaction",
      "properties": {
        "interactionTime": {
          "description": "The time when the user acted on the item.  If multiple actions of the same\ntype exist for a single user, only the most recent action is recorded.",
          "format": "google-datetime",
          "type": "string"
        },
        "principal": {
          "$ref": "Principal",
          "description": "The user that acted on the item."
        },
        "type": {
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "Item": {
      "description": "Represents a single object that is an item in the search index, such as a\nfile, folder, or a database record.",
      "id": "Item",
      "properties": {
        "acl": {
          "$ref": "ItemAcl",
          "description": "Access control list for this item."
        },
        "content": {
          "$ref": "ItemContent",
          "description": "Item content to be indexed and made text searchable."
        },
        "itemType": {
          "description": "Type for this item.",
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information.\nThese items cannot be referred in\ncontainerName\nor inheritAclFrom\nfields.",
            "An item that gets indexed and whose purpose is to supply other items\nwith ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose\nas CONTAINER_ITEM."
          ],
          "type": "string"
        },
        "metadata": {
          "$ref": "ItemMetadata",
          "description": "Metadata information."
        },
        "name": {
          "description": "Name of the Item. Format:\ndatasources/{source_id}/items/{item_id}\n\u003cbr /\u003eThis is a required field.\nThe maximum length is 1536 characters.",
          "type": "string"
        },
        "payload": {
          "description": "Additional state connector can store for this item.\nThe maximum length is 10000 bytes.",
          "format": "byte",
          "type": "string"
        },
        "queue": {
          "description": "Queue this item belongs to.\nThe maximum length is 100 characters.",
          "type": "string"
        },
        "status": {
          "$ref": "ItemStatus",
          "description": "Status of the item.\nOutput only field."
        },
        "structuredData": {
          "$ref": "ItemStructuredData",
          "description": "The structured data for the item that should conform to a registered\nobject definition in the schema for the data source."
        },
        "version": {
          "description": "Required. The indexing system stores the version from the datasource as a\nbyte string and compares the Item version in the index\nto the version of the queued Item using lexical ordering.\n\u003cbr /\u003e\u003cbr /\u003e\nCloud Search Indexing won't index or delete any queued item with\na version value that is less than or equal to the version of the\ncurrently indexed item.\nThe maximum length for this field is 1024 bytes.",
          "format": "byte",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ItemAcl": {
      "description": "Access control list information for the item. For more information see\nhttps://developers.google.com/cloud-search/docs/guides/index-your-data#acls",
      "id": "ItemAcl",
      "properties": {
        "aclInheritanceType": {
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a\nparent. This should always be set in tandem with the\ninheritAclFrom\nfield. Also, when the\ninheritAclFrom field\nis set, this field should be set to a valid AclInheritanceType.",
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ],
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL.\nUse NOT_APPLICABLE when\ninheritAclFrom\nis empty.  An item without ACL inheritance can still have ACLs supplied\nby its own readers and\ndeniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines\nits read access.",
            "During an authorization conflict, the ACL of the parent item\nspecified in the\ninheritAclFrom\nfield determines read access.",
            "Access is granted only if this item and the parent item specified in\nthe inheritAclFrom\nfield both permit read access."
          ],
          "type": "string"
        },
        "deniedReaders": {
          "description": "List of principals who are explicitly denied access to the item in search\nresults. While principals are denied access by default, use denied readers\nto handle exceptions and override the list allowed readers.\nThe maximum number of elements is 100.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        },
        "inheritAclFrom": {
          "description": "Name of the item to inherit the Access Permission List (ACL) from.\nNote: ACL inheritance *only* provides access permissions\nto child items and does not define structural relationships, nor does it\nprovide convenient ways to delete large groups of items.\nDeleting an ACL parent from the index only alters the access permissions of\nchild items that reference the parent in the\ninheritAclFrom\nfield. The item is still in the index, but may not\nvisible in search results[...]",
          "type": "string"
        },
        "owners": {
          "description": "Optional. List of owners for the item. This field has no bearing on\ndocument access permissions. It does, however, offer\na slight ranking boosts items where the querying user is an owner.\nThe maximum number of elements is 5.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        },
        "readers": {
          "description": "List of principals who are allowed to see the item in search results.\nOptional if inheriting permissions from another item or if the item\nis not intended to be visible, such as\nvirtual\ncontainers.\nThe maximum number of elements is 1000.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ItemContent": {
      "description": "Content of an item to be indexed and surfaced by Cloud Search.",
      "id": "ItemContent",
      "properties": {
        "contentDataRef": {
          "$ref": "UploadItemRef",
          "description": "Upload reference ID of a previously uploaded content via write method."
        },
        "contentFormat": {
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "type": "string"
        },
        "hash": {
          "description": "Hashing info calculated and provided by the API client for content.\nCan be used with the items.push method to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "inlineContent": {
          "description": "Content that is supplied inlined within the update method.\nThe maximum length is 102400 bytes (100 KiB).",
          "format": "byte",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ItemCountByStatus": {
      "id": "ItemCountByStatus",
      "properties": {
        "count": {
          "description": "Number of items matching the status code.",
          "format": "int64",
          "type": "string"
        },
        "statusCode": {
          "description": "Status of the items.",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "ItemMetadata": {
      "description": "Available metadata fields for the item.",
      "id": "ItemMetadata",
      "properties": {
        "containerName": {
          "description": "The name of the container for this item.\nDeletion of the container item leads to automatic deletion of this\nitem.  Note: ACLs are not inherited from a container item.\nTo provide ACL inheritance for an item, use the\ninheritAclFrom\nfield. The maximum length is 1536 characters.",
          "type": "string"
        },
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For\nmore information, see\nhttp://www.unicode.org/reports/tr35/#Unicode_locale_identifier.\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "createTime": {
          "description": "The time when the item was created in the source repository.",
          "format": "google-datetime",
          "type": "string"
        },
        "hash": {
          "description": "Hashing value provided by the API caller.\nThis can be used with the\nitems.push\nmethod to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "interactions": {
          "description": "A list of interactions for the item.  Interactions are used to improve\nSearch quality, but are not exposed to end users.\nThe maximum number of elements is 1000.",
          "items": {
            "$ref": "Interaction"
          },
          "type": "array"
        },
        "keywords": {
          "description": "Additional keywords or phrases that should match the item.\nUsed internally for user generated content.\nThe maximum number of elements is 100.\nThe maximum length is 8192 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "mimeType": {
          "description": "The original mime-type of\nItemContent.content\nin the source repository.\nThe maximum length is 256 characters.",
          "type": "string"
        },
        "objectType": {
          "description": "The type of the item.  This should correspond to the name of an object\ndefinition in the schema registered for the data source.  For example, if\nthe schema for the data source contains an object definition with name\n'document', then item indexing requests for objects of that type should set\nobjectType to 'document'.\nThe maximum length is 256 characters.",
          "type": "string"
        },
        "searchQualityMetadata": {
          "$ref": "SearchQualityMetadata",
          "description": "Additional search quality metadata of the item"
        },
        "sourceRepositoryUrl": {
          "description": "Link to the source repository serving the data.  \u0026#83;earch results apply\nthis link to the title.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "title": {
          "description": "The title of the item.  If given, this will be the displayed title of the\nSearch result.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "updateTime": {
          "description": "The time when the item was last modified in the source repository.",
          "format": "google-datetime",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ItemStatus": {
      "description": "This contains item's status and any errors.",
      "id": "ItemStatus",
      "properties": {
        "code": {
          "description": "Status code.",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "type": "string"
        },
        "processingErrors": {
          "description": "Error details in case the item is in ERROR state.",
          "items": {
            "$ref": "ProcessingError"
          },
          "type": "array"
        },
        "repositoryErrors": {
          "description": "Repository error reported by connector.",
          "items": {
            "$ref": "RepositoryError"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ItemStructuredData": {
      "description": "Available structured data fields for the item.",
      "id": "ItemStructuredData",
      "properties": {
        "hash": {
          "description": "Hashing value provided by the API caller.\nThis can be used with the\nitems.push\nmethod to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "object": {
          "$ref": "StructuredDataObject",
          "description": "The structured data object that should conform to a registered object\ndefinition in the schema for the data source."
        }
      },
      "type": "object"
    },
    "ListDataSourceResponse": {
      "id": "ListDataSourceResponse",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "sources": {
          "items": {
            "$ref": "DataSource"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "id": "ListItemNamesForUnmappedIdentityResponse",
      "properties": {
        "itemNames": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ListItemsResponse": {
      "id": "ListItemsResponse",
      "properties": {
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ListQuerySourcesResponse": {
      "description": "List sources response.",
      "id": "ListQuerySourcesResponse",
      "properties": {
        "nextPageToken": {
          "type": "string"
        },
        "sources": {
          "items": {
            "$ref": "QuerySource"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ListSearchApplicationsResponse": {
      "id": "ListSearchApplicationsResponse",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "searchApplications": {
          "items": {
            "$ref": "SearchApplication"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ListUnmappedIdentitiesResponse": {
      "id": "ListUnmappedIdentitiesResponse",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "unmappedIdentities": {
          "items": {
            "$ref": "UnmappedIdentity"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "MatchRange": {
      "description": "Matched range of a snippet [start, end).",
      "id": "MatchRange",
      "properties": {
        "end": {
          "description": "End of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        },
        "start": {
          "description": "Starting position of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "Media": {
      "description": "Media resource.",
      "id": "Media",
      "properties": {
        "resourceName": {
          "description": "Name of the media resource.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Metadata": {
      "description": "Metadata of a matched search result.",
      "id": "Metadata",
      "properties": {
        "createTime": {
          "description": "The creation time for this document or object in the search result.",
          "format": "google-datetime",
          "type": "string"
        },
        "displayOptions": {
          "$ref": "ResultDisplayMetadata",
          "description": "Options that specify how to display a structured data search result."
        },
        "fields": {
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "items": {
            "$ref": "NamedProperty"
          },
          "type": "array"
        },
        "mimeType": {
          "description": "Mime type of the search result.",
          "type": "string"
        },
        "objectType": {
          "description": "Object type of the search result.",
          "type": "string"
        },
        "owner": {
          "$ref": "Person",
          "description": "Owner (usually creator) of the document or object of the search result."
        },
        "source": {
          "$ref": "Source",
          "description": "The named source for the result, such as Gmail."
        },
        "updateTime": {
          "description": "The last modified date for the object in the search result. If not\nset in the item, the value returned here is empty. When\n`updateTime` is used for calculating freshness and is not set, this\nvalue defaults to 2 years from the current time.",
          "format": "google-datetime",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Metaline": {
      "description": "A metaline is a list of properties that are displayed along with the search\nresult to provide context.",
      "id": "Metaline",
      "properties": {
        "properties": {
          "description": "The list of displayed properties for the metaline. The maxiumum number of\nproperties is 5.",
          "items": {
            "$ref": "DisplayedProperty"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Name": {
      "description": "A person's name.",
      "id": "Name",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by\nthe viewer's account or the \u003ccode\u003eAccept-Language\u003c/code\u003e HTTP header.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "NamedProperty": {
      "description": "A typed name-value pair for structured data.  The type of the value should\nbe the same as the registered type for the `name` property in the object\ndefinition of `objectType`.",
      "id": "NamedProperty",
      "properties": {
        "booleanValue": {
          "type": "boolean"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        },
        "name": {
          "description": "The name of the property.  This name should correspond to the name of the\nproperty that was registered for object definition in the schema.\nThe maximum allowable length for this property is 256 characters.",
          "type": "string"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "textValues": {
          "$ref": "TextValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        }
      },
      "type": "object"
    },
    "ObjectDefinition": {
      "description": "The definition for an object within a data source.",
      "id": "ObjectDefinition",
      "properties": {
        "name": {
          "description": "Name for the object, which then defines its type. Item indexing requests\nshould set the\nobjectType field\nequal to this value. For example, if *name* is *Document*, then indexing\nrequests for items of type Document should set\nobjectType equal to\n*Document*. Each object definition must be uniquely named within a schema.\nThe name must start with a letter and can only contain letters (A-Z, a-z)\nor numbers (0-9).\nThe maximum length is 256 characters.",
          "type": "string"
        },
        "options": {
          "$ref": "ObjectOptions",
          "description": "The optional object-specific options."
        },
        "propertyDefinitions": {
          "description": "The property definitions for the object.\nThe maximum number of elements is 1000.",
          "items": {
            "$ref": "PropertyDefinition"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ObjectDisplayOptions": {
      "description": "The display options for an object.",
      "id": "ObjectDisplayOptions",
      "properties": {
        "metalines": {
          "description": "Defines the properties that will be displayed in the metalines of the\nsearch results. The property values will be displayed in the order given\nhere. If a property holds multiple values, all of the values will be\ndiplayed before the next properties. For this reason, it is a good practice\nto specify singular properties before repeated properties in this list. All\nof the properties must set\nis_returnable\nto true. The maximum number of metalines is 3.",
          "items": {
            "$ref": "Metaline"
          },
          "type": "array"
        },
        "objectDisplayLabel": {
          "description": "The user friendly label to display in the search result to inidicate the\ntype of the item. This is OPTIONAL; if not given, an object label will not\nbe displayed on the context line of the search results. The maximum length\nis 32 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ObjectOptions": {
      "description": "The options for an object.",
      "id": "ObjectOptions",
      "properties": {
        "displayOptions": {
          "$ref": "ObjectDisplayOptions",
          "description": "Options that determine how the object is displayed in the Cloud Search\nresults page."
        },
        "freshnessOptions": {
          "$ref": "FreshnessOptions",
          "description": "The freshness options for an object."
        }
      },
      "type": "object"
    },
    "ObjectPropertyOptions": {
      "description": "Options for object properties.",
      "id": "ObjectPropertyOptions",
      "properties": {
        "subobjectProperties": {
          "description": "The properties of the sub-object. These properties represent a nested\nobject. For example, if this property represents a postal address, the\nsubobjectProperties might be named *street*, *city*, and *state*.\nThe maximum number of elements is 1000.",
          "items": {
            "$ref": "PropertyDefinition"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ObjectValues": {
      "description": "List of object values.",
      "id": "ObjectValues",
      "properties": {
        "values": {
          "items": {
            "$ref": "StructuredDataObject"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Operation": {
      "description": "This resource represents a long-running operation that is the result of a\nnetwork API call.",
      "id": "Operation",
      "properties": {
        "done": {
          "description": "If the value is `false`, it means the operation is still in progress.\nIf `true`, the operation is completed, and either `error` or `response` is\navailable.",
          "type": "boolean"
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        },
        "metadata": {
          "additionalProperties": {
            "description": "Properties of the object. Contains field @type with type URL.",
            "type": "any"
          },
          "description": "Service-specific metadata associated with the operation.  It typically\ncontains progress information and common metadata such as create time.\nSome services might not provide such metadata.  Any method that returns a\nlong-running operation should document the metadata type, if any.",
          "type": "object"
        },
        "name": {
          "description": "The server-assigned name, which is only unique within the same service that\noriginally returns it. If you use the default HTTP mapping, the\n`name` should be a resource name ending with `operations/{unique_id}`.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "PeopleSuggestion": {
      "description": "This field contains information about the person being suggested.",
      "id": "PeopleSuggestion",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Suggested person. All fields of the person object might not be populated."
        }
      },
      "type": "object"
    },
    "Person": {
      "description": "Object to represent a person.",
      "id": "Person",
      "properties": {
        "emailAddresses": {
          "description": "The person's email addresses",
          "items": {
            "$ref": "EmailAddress"
          },
          "type": "array"
        },
        "name": {
          "description": "The resource name of the person to provide information about.\nSee \u003ca href=\"https://developers.google.com/people/api/rest/v1/people/get\"\u003e\nPeople.get\u003c/a\u003e from Google People API.",
          "type": "string"
        },
        "obfuscatedId": {
          "description": "Obfuscated ID of a person.",
          "type": "string"
        },
        "personNames": {
          "description": "The person's name",
          "items": {
            "$ref": "Name"
          },
          "type": "array"
        },
        "photos": {
          "description": "A person's read-only photo. A picture shown next to the person's name to\nhelp others recognize the person in search results.",
          "items": {
            "$ref": "Photo"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Photo": {
      "description": "A person's photo.",
      "id": "Photo",
      "properties": {
        "url": {
          "description": "The URL of the photo.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "PollItemsRequest": {
      "id": "PollItemsRequest",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "limit": {
          "description": "Maximum number of items to return.\n\u003cbr /\u003eThe maximum value is 100 and the default value is 20.",
          "format": "int32",
          "type": "integer"
        },
        "queue": {
          "description": "Queue name to fetch items from.  If unspecified, PollItems will\nfetch from 'default' queue.\nThe maximum length is 100 characters.",
          "type": "string"
        },
        "statusCodes": {
          "description": "Limit the items polled to the ones with these statuses.",
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "items": {
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ],
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "PollItemsResponse": {
      "id": "PollItemsResponse",
      "properties": {
        "items": {
          "description": "Set of items from the queue available for connector to process.\n\u003cbr /\u003eThese items have the following subset of fields populated: \u003cbr /\u003e\n\u003cbr /\u003eversion\n\u003cbr /\u003emetadata.hash\n\u003cbr /\u003estructured_data.hash\n\u003cbr /\u003econtent.hash\n\u003cbr /\u003epayload\n\u003cbr /\u003estatus\n\u003cbr /\u003equeue",
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Principal": {
      "description": "Reference to a user, group, or domain.",
      "id": "Principal",
      "properties": {
        "groupResourceName": {
          "description": "This principal is a group identified using an external identity.\nThe name field must specify the group resource name with this format:\nidentitysources/{source_id}/groups/{ID}",
          "type": "string"
        },
        "gsuitePrincipal": {
          "$ref": "GSuitePrincipal",
          "description": "This principal is a GSuite user, group or domain."
        },
        "userResourceName": {
          "description": "This principal is a user identified using an external identity.\nThe name field must specify the user resource name with this format:\nidentitysources/{source_id}/users/{ID}",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ProcessingError": {
      "id": "ProcessingError",
      "properties": {
        "code": {
          "description": "Error code indicating the nature of the error.",
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "enumDescriptions": [
            "Input only value.  Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state.\nFieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other\nitems with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ],
          "type": "string"
        },
        "errorMessage": {
          "description": "Description of the error.",
          "type": "string"
        },
        "fieldViolations": {
          "description": "In case the item fields are invalid, this field contains the details\nabout the validation errors.",
          "items": {
            "$ref": "FieldViolation"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "PropertyDefinition": {
      "description": "The definition of a property within an object.",
      "id": "PropertyDefinition",
      "properties": {
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "displayOptions": {
          "$ref": "PropertyDisplayOptions",
          "description": "Options that determine how the property is displayed in the Cloud Search\nresults page if it is specified to be displayed in the object's\ndisplay options\n."
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "isFacetable": {
          "description": "Indicates that the property can be used for generating facets. Cannot be\ntrue for properties whose type is object. IsReturnable must be true to set\nthis option.\nOnly supported for Boolean, Enum, and Text properties.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a\ndocument only has one description but can have multiple comments. Cannot be\ntrue for properties whose type is a boolean.\nIf set to false, properties that contain more than one value will cause the\nindexing request for that item to be rejected.",
          "type": "boolean"
        },
        "isReturnable": {
          "description": "Indicates that the property identifies data that should be returned in\nsearch results via the Query API. If set to *true*, indicates that Query\nAPI users can use matching property fields in results. However, storing\nfields requires more space allocation and uses more bandwidth for search\nqueries, which impacts performance over large datasets. Set to *true* here\nonly if the field is needed for search results. Cannot be true for\nproperties whose type is an object.",
          "type": "boolean"
        },
        "isSortable": {
          "description": "Indicates that the property can be used for sorting. Cannot be true for\nproperties that are repeatable. Cannot be true for properties whose type\nis object or user identifier. IsReturnable must be true to set this option.\nOnly supported for Boolean, Date, Double, Integer, and Timestamp\nproperties.",
          "type": "boolean"
        },
        "isSuggestable": {
          "description": "Indicates that the property can be used for generating query suggestions.",
          "type": "boolean"
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this\nproperty. Only supported for Text properties. IsReturnable must be true to\nset this option. In a given datasource maximum of 5 properties can be\nmarked as is_wildcard_searchable.",
          "type": "boolean"
        },
        "name": {
          "description": "The name of the property. Item indexing requests sent to the Indexing API\nshould set the property name\nequal to this value. For example, if name is *subject_line*, then indexing\nrequests for document items with subject fields should set the\nname for that field equal to\n*subject_line*. Use the name as the identifier for the object property.\nOnce registered as a property for an object, you cannot re-use this name\nfor another property within that object.\nThe name m[...]",
          "type": "string"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        }
      },
      "type": "object"
    },
    "PropertyDisplayOptions": {
      "description": "The display options for a property.",
      "id": "PropertyDisplayOptions",
      "properties": {
        "displayLabel": {
          "description": "The user friendly label for the property that will be used if the property\nis specified to be displayed in ObjectDisplayOptions. If given, the display\nlabel will be shown in front of the property values when the property is\npart of the object display options. For example, if the property value is\n'1', the value by itself may not be useful context for the user. If the\ndisplay name given was 'priority', then the user will see 'priority : 1' in\nthe search results whi[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "PushItem": {
      "description": "Represents an item to be pushed to the indexing queue.",
      "id": "PushItem",
      "properties": {
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is\nused to determine how to modify this\nitem's status. Setting this field and the\ntype field results in argument\nerror.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "metadataHash": {
          "description": "Metadata hash of the item according to the repository. If specified, this\nis used to determine how to modify this\nitem's status. Setting this field and the\ntype field results in argument\nerror.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "payload": {
          "description": "Provides additional document state information for the connector,\nsuch as an alternate repository ID and other metadata.\nThe maximum length is 8192 bytes.",
          "format": "byte",
          "type": "string"
        },
        "queue": {
          "description": "Queue to which this item belongs to.  The \u003ccode\u003edefault\u003c/code\u003e queue is\nchosen if this field is not specified. The maximum length is\n512 characters.",
          "type": "string"
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details.\nThis information is displayed in the Admin Console.\nThis field may only be populated when the\nType is\nREPOSITORY_ERROR."
        },
        "structuredDataHash": {
          "description": "Structured data hash of the item according to the repository. If specified,\nthis is used to determine how to modify this item's status. Setting this\nfield and the type field\nresults in argument error.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "type": {
          "description": "The type of the push operation that defines the push behavior.",
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ],
          "enumDescriptions": [
            "Default UNSPECIFIED.  Specifies that the push operation should not modify\nItemStatus",
            "Indicates that the repository document has been modified or updated since\nthe previous\nupdate\ncall. This changes status to\nMODIFIED state for\nan existing item. If this is called on a non existing item, the status is\nchanged to\nNEW_ITEM.",
            "Item in the repository has not been modified since the last update\ncall.  This push operation will set status to\nACCEPTED state.",
            "Connector is facing a repository error regarding this item.  Change\nstatus to\nREPOSITORY_ERROR\nstate. Item is unreserved and rescheduled at a future time determined by\nexponential backoff.",
            "Call push with REQUEUE only for items that have been reserved.\nThis action unreserves the item and resets its available time to the\nwall clock time."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "PushItemRequest": {
      "id": "PushItemRequest",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "item": {
          "$ref": "PushItem",
          "description": "Item to push onto the queue."
        }
      },
      "type": "object"
    },
    "QueryCountByStatus": {
      "id": "QueryCountByStatus",
      "properties": {
        "count": {
          "format": "int64",
          "type": "string"
        },
        "statusCode": {
          "description": "This represents the http status code.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "QueryInterpretation": {
      "id": "QueryInterpretation",
      "properties": {
        "interpretationType": {
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ],
          "enumDescriptions": [
            "Neither the natural language interpretation, nor a broader version of the\nquery is used to fetch the search results.",
            "The results from original query are blended with other results. The\nreason for blending these other results with the results from original\nquery is populated in the 'Reason' field below.",
            "The results from original query are replaced. The reason for replacing\nthe results from original query is populated in the 'Reason' field below."
          ],
          "type": "string"
        },
        "interpretedQuery": {
          "description": "The interpretation of the query used in search. For example, queries with\nnatural language intent like \"email from john\" will be interpreted as\n\"from:john source:mail\". This field will not be filled when the reason is\nNOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY.",
          "type": "string"
        },
        "reason": {
          "description": "The reason for interpretation of the query. This field will not be\nUNSPECIFIED if the interpretation type is not NONE.",
          "enum": [
            "UNSPECIFIED",
            "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
            "NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY"
          ],
          "enumDescriptions": [
            "",
            "Natural language interpretation of the query is used to fetch the search\nresults.",
            "Query and document terms similarity is used to selectively broaden the\nquery to retrieve additional search results since enough results were not\nfound for the user query.\nInterpreted query will be empty for this case."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "QueryInterpretationOptions": {
      "description": "Options to interpret user query.",
      "id": "QueryInterpretationOptions",
      "properties": {
        "disableNlInterpretation": {
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is\nfalse, Set to true to disable natural language interpretation. NL\ninterpretation only applies to predefined datasources.",
          "type": "boolean"
        },
        "enableVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural\nlanguage (NL) interpretation of queries, supplemental result retrieval,\nand usage of synonyms including custom ones.\nNl interpretation will be disabled if either one of the two flags is true.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "QueryItem": {
      "description": "Information relevant only to a query entry.",
      "id": "QueryItem",
      "properties": {
        "isSynthetic": {
          "description": "True if the text was generated by means other than a previous user search.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "QueryOperator": {
      "description": "The definition of a operator that can be used in a Search/Suggest request.",
      "id": "QueryOperator",
      "properties": {
        "displayName": {
          "description": "Display name of the operator",
          "type": "string"
        },
        "enumValues": {
          "description": "Potential list of values for the opeatror field. This field is only filled\nwhen we can safely enumerate all the possible values of this operator.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name that can be used to  isolate the property using\nthe greater-than operator.",
          "type": "string"
        },
        "isFacetable": {
          "description": "Can this operator be used to get facets.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates if multiple values can be set for this property.",
          "type": "boolean"
        },
        "isReturnable": {
          "description": "Will the property associated with this facet be returned as part of search\nresults.",
          "type": "boolean"
        },
        "isSortable": {
          "description": "Can this operator be used to sort results.",
          "type": "boolean"
        },
        "isSuggestable": {
          "description": "Can get suggestions for this field.",
          "type": "boolean"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name that can be used to  isolate the property using\nthe less-than operator.",
          "type": "string"
        },
        "objectType": {
          "description": "Name of the object corresponding to the operator. This field is only filled\nfor schema-specific operators, and is unset for common operators.",
          "type": "string"
        },
        "operatorName": {
          "description": "The name of the operator.",
          "type": "string"
        },
        "type": {
          "description": "Type of the operator.",
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "QuerySource": {
      "description": "List of sources that the user can search using the query API.",
      "id": "QuerySource",
      "properties": {
        "displayName": {
          "description": "Display name of the data source.",
          "type": "string"
        },
        "operators": {
          "description": "List of all operators applicable for this source.",
          "items": {
            "$ref": "QueryOperator"
          },
          "type": "array"
        },
        "shortName": {
          "description": "A short name or alias for the source.  This value can be used with the\n'source' operator.",
          "type": "string"
        },
        "source": {
          "$ref": "Source",
          "description": "Name of the source"
        }
      },
      "type": "object"
    },
    "QuerySuggestion": {
      "description": "This field does not contain anything as of now and is just used as an\nindicator that the suggest result was a phrase completion.",
      "id": "QuerySuggestion",
      "properties": {},
      "type": "object"
    },
    "RepositoryError": {
      "description": "Errors when the connector is communicating to the source repository.",
      "id": "RepositoryError",
      "properties": {
        "errorMessage": {
          "description": "Message that describes the error. The maximum allowable length\nof the message is 8192 characters.",
          "type": "string"
        },
        "httpStatusCode": {
          "description": "Error codes.  Matches the definition of HTTP status codes.",
          "format": "int32",
          "type": "integer"
        },
        "type": {
          "description": "Type of error.",
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to\nthe repository server."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "RequestOptions": {
      "description": "Shared request options for all RPC methods.",
      "id": "RequestOptions",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Debug options of the request"
        },
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\".\nFor more information, see\nhttp://www.unicode.org/reports/tr35/#Unicode_locale_identifier.\nFor translations.\n\nSet this field using the language set in browser or for the page. In the\nevent that the user's language preference is known, set this field to the\nknown user language.\n\nWhen specified, the documents in search results are biased towards the\nspecified language.\n\nThe suggest API does not use thi[...]",
          "type": "string"
        },
        "searchApplicationId": {
          "description": "Id of the application created using SearchApplicationsService.",
          "type": "string"
        },
        "timeZone": {
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or\n\"Australia/Sydney\". These IDs are defined by\n[Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/)\nproject, and currently available in the file\n[timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml).\nThis field is used to correctly interpret date and time queries.\nIf this field is not specified, the default time zone (UTC) is used.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ResetSearchApplicationRequest": {
      "id": "ResetSearchApplicationRequest",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object"
    },
    "ResponseDebugInfo": {
      "description": "Debugging information about the response.",
      "id": "ResponseDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "RestrictItem": {
      "description": "Information relevant only to a restrict entry.\nNextId: 12",
      "id": "RestrictItem",
      "properties": {
        "driveFollowUpRestrict": {
          "$ref": "DriveFollowUpRestrict",
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/search/quality/itemsuggest/utils/SubtypeRerankingUtils.java)"
        },
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "driveMimeTypeRestrict": {
          "$ref": "DriveMimeTypeRestrict",
          "description": "LINT.IfChange\nDrive Types."
        },
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        },
        "searchOperator": {
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ResultCounts": {
      "description": "Result count information",
      "id": "ResultCounts",
      "properties": {
        "sourceResultCounts": {
          "description": "Result count information for each source with results.",
          "items": {
            "$ref": "SourceResultCount"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ResultDebugInfo": {
      "description": "Debugging information about the result.",
      "id": "ResultDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ResultDisplayField": {
      "description": "Display Fields for Search Results",
      "id": "ResultDisplayField",
      "properties": {
        "label": {
          "description": "The display label for the property.",
          "type": "string"
        },
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        }
      },
      "type": "object"
    },
    "ResultDisplayLine": {
      "description": "The collection of fields that make up a displayed line",
      "id": "ResultDisplayLine",
      "properties": {
        "fields": {
          "items": {
            "$ref": "ResultDisplayField"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ResultDisplayMetadata": {
      "id": "ResultDisplayMetadata",
      "properties": {
        "metalines": {
          "description": "The metalines content to be displayed with the result.",
          "items": {
            "$ref": "ResultDisplayLine"
          },
          "type": "array"
        },
        "objectTypeLabel": {
          "description": "The display label for the object.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "RetrievalImportance": {
      "id": "RetrievalImportance",
      "properties": {
        "importance": {
          "description": "Indicates the ranking importance given to property when it is matched\nduring retrieval. Once set, the token importance of a property cannot be\nchanged.",
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ],
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still\nbe used for operator matching, faceting, and suggest if\ndesired."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "Schema": {
      "description": "The schema definition for a data source.",
      "id": "Schema",
      "properties": {
        "objectDefinitions": {
          "description": "The list of top-level objects for the data source.\nThe maximum number of elements is 10.",
          "items": {
            "$ref": "ObjectDefinition"
          },
          "type": "array"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema. After modifying the schema, wait for operations to complete\nbefore indexing additional content.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ScoringConfig": {
      "description": "Scoring configurations for a source while processing a\nSearch or\nSuggest request.",
      "id": "ScoringConfig",
      "properties": {
        "disableFreshness": {
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used\nas a ranking signal. Note that this setting is not available in the Admin\nUI.",
          "type": "boolean"
        },
        "disablePersonalization": {
          "description": "Whether to personalize the results. By default, personal signals will\nbe used to boost results.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "SearchApplication": {
      "description": "SearchApplication",
      "id": "SearchApplication",
      "properties": {
        "dataSourceRestrictions": {
          "description": "Retrictions applied to the configurations.\nThe maximum number of elements is 10.",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "defaultFacetOptions": {
          "description": "The default fields for returning facet results.\nThe sources specified here also have been included in\ndata_source_restrictions\nabove.",
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array"
        },
        "defaultSortOptions": {
          "$ref": "SortOptions",
          "description": "The default options for sorting the search results"
        },
        "displayName": {
          "description": "Display name of the Search Application.\nThe maximum length is 300 characters.",
          "type": "string"
        },
        "name": {
          "description": "Name of the Search Application.\n\u003cbr /\u003eFormat: searchapplications/{application_id}.",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema. Output only field.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        },
        "sourceConfig": {
          "description": "Configuration for a sources specified in data_source_restrictions.",
          "items": {
            "$ref": "SourceConfig"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "SearchApplicationQueryStats": {
      "id": "SearchApplicationQueryStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "SearchApplicationSessionStats": {
      "id": "SearchApplicationSessionStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SearchApplicationUserStats": {
      "id": "SearchApplicationUserStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "format": "int64",
          "type": "string"
        },
        "sevenDaysActiveUsersCount": {
          "description": "The count of unique active users in the past seven days",
          "format": "int64",
          "type": "string"
        },
        "thirtyDaysActiveUsersCount": {
          "description": "The count of unique active users in the past thirty days",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SearchItemsByViewUrlRequest": {
      "id": "SearchItemsByViewUrlRequest",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "pageToken": {
          "description": "The next_page_token value returned from a previous request, if any.",
          "type": "string"
        },
        "viewUrl": {
          "description": "Specify the full view URL to find the corresponding item.\nThe maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SearchItemsByViewUrlResponse": {
      "id": "SearchItemsByViewUrlResponse",
      "properties": {
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SearchQualityMetadata": {
      "description": "Additional search quality metadata of the item.",
      "id": "SearchQualityMetadata",
      "properties": {
        "quality": {
          "description": "An indication of the quality of the item, used to influence search quality.\nValue should be between 0.0 (lowest quality) and 1.0 (highest quality). The\ndefault value is 0.0.",
          "format": "double",
          "type": "number"
        }
      },
      "type": "object"
    },
    "SearchRequest": {
      "description": "The search API request.",
      "id": "SearchRequest",
      "properties": {
        "dataSourceRestrictions": {
          "description": "The sources to use for querying. If not specified, all data sources\nfrom the current search application are used.",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "facetOptions": {
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array"
        },
        "pageSize": {
          "description": "Maximum number of search results to return in one page.\nValid values are between 1 and 100, inclusive.\nDefault value is 10.",
          "format": "int32",
          "type": "integer"
        },
        "query": {
          "description": "The raw query string.\nSee supported search operators in the [Cloud search\nCheat\nSheet](https://gsuite.google.com/learning-center/products/cloudsearch/cheat-sheet/)",
          "type": "string"
        },
        "queryInterpretationOptions": {
          "$ref": "QueryInterpretationOptions",
          "description": "Options to interpret the user query."
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "start": {
          "description": "Starting index of the results.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "SearchResponse": {
      "description": "The search API response.",
      "id": "SearchResponse",
      "properties": {
        "debugInfo": {
          "$ref": "ResponseDebugInfo",
          "description": "Debugging information about the response."
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "facetResults": {
          "description": "Repeated facet results.",
          "items": {
            "$ref": "FacetResult"
          },
          "type": "array"
        },
        "hasMoreResults": {
          "description": "Whether there are more search results matching the query.",
          "type": "boolean"
        },
        "queryInterpretation": {
          "$ref": "QueryInterpretation",
          "description": "Query interpretation result for user query. Empty if query interpretation\nis disabled."
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "resultCountExact": {
          "description": "The exact result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "resultCounts": {
          "$ref": "ResultCounts",
          "description": "Expanded result count information."
        },
        "results": {
          "description": "Results from a search query.",
          "items": {
            "$ref": "SearchResult"
          },
          "type": "array"
        },
        "spellResults": {
          "description": "Suggested spelling for the query.",
          "items": {
            "$ref": "SpellResult"
          },
          "type": "array"
        },
        "structuredResults": {
          "description": "Structured results for the user query. These results are not counted\nagainst the page_size.",
          "items": {
            "$ref": "StructuredResult"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "SearchResult": {
      "description": "Results containing indexed information for a document.",
      "id": "SearchResult",
      "properties": {
        "clusteredResults": {
          "description": "If source is clustered, provide list of clustered results. There will only\nbe one level of clustered results. If current source is not enabled for\nclustering, this field will be empty.",
          "items": {
            "$ref": "SearchResult"
          },
          "type": "array"
        },
        "debugInfo": {
          "$ref": "ResultDebugInfo",
          "description": "Debugging information about this search result."
        },
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        },
        "snippet": {
          "$ref": "Snippet",
          "description": "The concatenation of all snippets (summaries) available for this result."
        },
        "title": {
          "description": "Title of the search result.",
          "type": "string"
        },
        "url": {
          "description": "The URL of the search result. The URL contains a Google redirect to the\nactual item. This URL is signed and shouldn't be changed.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Snippet": {
      "description": "Snippet of the search result, which summarizes the content of the resulting\npage.",
      "id": "Snippet",
      "properties": {
        "matchRanges": {
          "description": "The matched ranges in the snippet.",
          "items": {
            "$ref": "MatchRange"
          },
          "type": "array"
        },
        "snippet": {
          "description": "The snippet of the document.\nThe snippet of the document. May contain escaped HTML character that\nshould be unescaped prior to rendering.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SortOptions": {
      "id": "SortOptions",
      "properties": {
        "operatorName": {
          "description": "Name of the operator corresponding to the field to sort on.\nThe corresponding property must be marked as\nsortable.",
          "type": "string"
        },
        "sortOrder": {
          "description": "Ascending is the default sort order",
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ],
          "enumDescriptions": [
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "Source": {
      "description": "Defines sources for the suggest/search APIs.",
      "id": "Source",
      "properties": {
        "name": {
          "description": "Source name for content indexed by the\nIndexing API.",
          "type": "string"
        },
        "predefinedSource": {
          "description": "Predefined content source for Google Apps.",
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used\nwith the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used\nwith the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "SourceConfig": {
      "description": "Configurations for a source while processing a\nSearch or\nSuggest request.",
      "id": "SourceConfig",
      "properties": {
        "crowdingConfig": {
          "$ref": "SourceCrowdingConfig",
          "description": "The crowding configuration for the source."
        },
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        },
        "source": {
          "$ref": "Source",
          "description": "The source for which this configuration is to be used."
        }
      },
      "type": "object"
    },
    "SourceCrowdingConfig": {
      "description": "Set search results crowding limits. Crowding is a situation in which\nmultiple results from the same source or host \"crowd out\" other results,\ndiminishing the quality of search for users. To foster better search quality\nand source diversity in search results, you can set a condition to reduce\nrepetitive results by source.",
      "id": "SourceCrowdingConfig",
      "properties": {
        "numResults": {
          "description": "Maximum number of results allowed from a source.\nNo limits will be set on results if this value is less than or equal to 0.",
          "format": "int32",
          "type": "integer"
        },
        "numSuggestions": {
          "description": "Maximum number of suggestions allowed from a source.\nNo limits will be set on results if this value is less than or equal to 0.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "SourceResultCount": {
      "description": "Per source result count information.",
      "id": "SourceResultCount",
      "properties": {
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this source.",
          "format": "int64",
          "type": "string"
        },
        "resultCountExact": {
          "description": "The exact result count for this source.",
          "format": "int64",
          "type": "string"
        },
        "source": {
          "$ref": "Source",
          "description": "The source the result count information is associated with."
        }
      },
      "type": "object"
    },
    "SourceScoringConfig": {
      "description": "Set the scoring configuration. This allows modifying the ranking of results\nfor a source.",
      "id": "SourceScoringConfig",
      "properties": {
        "sourceImportance": {
          "description": "Importance of the source.",
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "SpellResult": {
      "id": "SpellResult",
      "properties": {
        "suggestedQuery": {
          "description": "The suggested spelling of the query.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "StartUploadItemRequest": {
      "description": "Start upload file request.",
      "id": "StartUploadItemRequest",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object"
    },
    "Status": {
      "description": "The `Status` type defines a logical error model that is suitable for\ndifferent programming environments, including REST APIs and RPC APIs. It is\nused by [gRPC](https://github.com/grpc). Each `Status` message contains\nthree pieces of data: error code, error message, and error details.\n\nYou can find out more about this error model and how to work with it in the\n[API Design Guide](https://cloud.google.com/apis/design/errors).",
      "id": "Status",
      "properties": {
        "code": {
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "format": "int32",
          "type": "integer"
        },
        "details": {
          "description": "A list of messages that carry the error details.  There is a common set of\nmessage types for APIs to use.",
          "items": {
            "additionalProperties": {
              "description": "Properties of the object. Contains field @type with type URL.",
              "type": "any"
            },
            "type": "object"
          },
          "type": "array"
        },
        "message": {
          "description": "A developer-facing error message, which should be in English. Any\nuser-facing error message should be localized and sent in the\ngoogle.rpc.Status.details field, or localized by the client.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "StructuredDataObject": {
      "description": "A structured data object consisting of named properties.",
      "id": "StructuredDataObject",
      "properties": {
        "properties": {
          "description": "The properties for the object.\nThe maximum number of elements is 1000.",
          "items": {
            "$ref": "NamedProperty"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "StructuredResult": {
      "description": "Structured results that are returned as part of search request.",
      "id": "StructuredResult",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Representation of a person"
        }
      },
      "type": "object"
    },
    "SuggestRequest": {
      "description": "Request of suggest API.",
      "id": "SuggestRequest",
      "properties": {
        "dataSourceRestrictions": {
          "description": "The sources to use for suggestions. If not specified, the data sources\nare taken from the current search application.\n\nNOTE: Suggestions are supported only for third party data sources and\npeople (i.e. PredefinedSource.PERSON).",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "query": {
          "description": "Partial query for which autocomplete suggestions will be shown.\nFor example, if the query is \"sea\", then the server might return\n\"season\", \"search\", \"seagull\" and so on.",
          "type": "string"
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        }
      },
      "type": "object"
    },
    "SuggestResponse": {
      "description": "Response of the suggest API.",
      "id": "SuggestResponse",
      "properties": {
        "suggestResults": {
          "description": "List of suggestions.",
          "items": {
            "$ref": "SuggestResult"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "SuggestResult": {
      "description": "One suggestion result.",
      "id": "SuggestResult",
      "properties": {
        "peopleSuggestion": {
          "$ref": "PeopleSuggestion",
          "description": "This is present when the suggestion indicates a person. It\ncontains more information about the person - like their email ID,\nname etc."
        },
        "querySuggestion": {
          "$ref": "QuerySuggestion",
          "description": "This field will be present if the suggested query is a word/phrase\ncompletion."
        },
        "source": {
          "$ref": "Source",
          "description": "The source of the suggestion."
        },
        "suggestedQuery": {
          "description": "The suggested query that will be used for search, when the user\nclicks on the suggestion",
          "type": "string"
        }
      },
      "type": "object"
    },
    "TextOperatorOptions": {
      "description": "Used to provide a search operator for text properties. This is optional.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "id": "TextOperatorOptions",
      "properties": {
        "exactMatchWithOperator": {
          "description": "If true, the text value will be tokenized as one atomic value in\noperator searches and facet matches. For example, if the operator name is\n\"genre\" and the value is \"science-fiction\" the query restrictions\n\"genre:science\" and \"genre:fiction\" will not match the item;\n\"genre:science-fiction\" will. Value matching is case-sensitive\nand does not remove special characters.\nIf false, the text will be tokenized. For example, if the value is\n\"science-fiction\" t[...]",
          "type": "boolean"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntext property. For example, if operatorName is *subject* and the\nproperty's name is *subjectLine*, then queries like\n*subject:\u0026lt;value\u0026gt;* will show results only where the value of the\nproperty named *subjectLine* matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;value\u0026gt;* without an operator will return\nall items where *\u0026lt;value\u0[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "TextPropertyOptions": {
      "description": "Options for text properties.",
      "id": "TextPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "TextOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        },
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the\nfield when used for retrieval."
        }
      },
      "type": "object"
    },
    "TextValues": {
      "description": "List of text values.",
      "id": "TextValues",
      "properties": {
        "values": {
          "description": "The maximum allowable length for text values is 2048 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "TimestampOperatorOptions": {
      "description": "Used to provide a search operator for timestamp properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "id": "TimestampOperatorOptions",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property using the greater-than operator. For example, if\ngreaterThanOperatorName is *closedafter* and the property's name is\n*closeDate*, then queries like *closedafter:\u0026lt;value\u0026gt;* will\nshow results only where the value of the property named *closeDate* is\nlater than *\u0026lt;value\u0026gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum le[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property using the less-than operator. For example, if\nlessThanOperatorName is *closedbefore* and the property's name is\n*closeDate*, then queries like *closedbefore:\u0026lt;value\u0026gt;* will\nshow results only where the value of the property named *closeDate* is\nearlier than *\u0026lt;value\u0026gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum leng[...]",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property. For example, if operatorName is *closedon* and the\nproperty's name is *closeDate*, then queries like\n*closedon:\u0026lt;value\u0026gt;* will show results only where the value of the\nproperty named *closeDate* matches *\u0026lt;value\u0026gt;*. By contrast, a\nsearch that uses the same *\u0026lt;value\u0026gt;* without an operator will return\nall items where *\u0026lt;value[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "TimestampPropertyOptions": {
      "description": "Options for timestamp properties.",
      "id": "TimestampPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "TimestampOperatorOptions",
          "description": "If set, describes how the timestamp should be used as a search operator."
        }
      },
      "type": "object"
    },
    "TimestampValues": {
      "description": "List of timestamp values.",
      "id": "TimestampValues",
      "properties": {
        "values": {
          "items": {
            "format": "google-datetime",
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "UnmappedIdentity": {
      "id": "UnmappedIdentity",
      "properties": {
        "externalIdentity": {
          "$ref": "Principal",
          "description": "The resource name for an external user."
        },
        "resolutionStatusCode": {
          "description": "The resolution status for the external identity.",
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ],
          "enumDescriptions": [
            "Input-only value.  Used to list all unmapped identities regardless of\nstatus.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by\nthe user.",
            "The identity source associated with the identity was either not found or\ndeleted.",
            "IDaaS does not understand the identity source, probably because the\nschema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "UnreserveItemsRequest": {
      "id": "UnreserveItemsRequest",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "queue": {
          "description": "Name of a queue to unreserve items from.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "UpdateDataSourceRequest": {
      "id": "UpdateDataSourceRequest",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "source": {
          "$ref": "DataSource"
        }
      },
      "type": "object"
    },
    "UpdateSchemaRequest": {
      "id": "UpdateSchemaRequest",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "schema": {
          "$ref": "Schema",
          "description": "The new schema for the source."
        },
        "validateOnly": {
          "description": "If true, the schema will be checked for validity,\nbut will not be registered with the data source, even if valid.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "UploadItemRef": {
      "description": "Represents an upload session reference.\nThis reference is created via upload\nmethod.\nUpdating of item content may refer to this uploaded content via\ncontentDataRef.",
      "id": "UploadItemRef",
      "properties": {
        "name": {
          "description": "Name of the content reference.\nThe maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Value": {
      "description": "Definition of a single value with generic type.",
      "id": "Value",
      "properties": {
        "booleanValue": {
          "type": "boolean"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "integerValue": {
          "format": "int64",
          "type": "string"
        },
        "stringValue": {
          "type": "string"
        },
        "timestampValue": {
          "format": "google-datetime",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ValueFilter": {
      "id": "ValueFilter",
      "properties": {
        "operatorName": {
          "description": "The `operator_name` applied to the query, such as *price_greater_than*.\nThe filter can work against both types of filters defined in the schema\nfor your data source:\n\u003cbr/\u003e\u003cbr/\u003e\n1. `operator_name`, where the query filters results by the property\nthat matches the value.\n\u003cbr/\u003e\n2. `greater_than_operator_name` or `less_than_operator_name` in your\nschema. The query filters the results for the property values that are\ngreater than or less[...]",
          "type": "string"
        },
        "value": {
          "$ref": "Value",
          "description": "The value to be compared with."
        }
      },
      "type": "object"
    }
  },
  "servicePath": "",
  "title": "Cloud Search API",
  "version": "v1",
  "version_module": true
}