{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/zcpG0fjFy3jg5hXoSMJXXIEGriY\"",
 "discoveryVersion": "v1",
 "id": "youtube:v3",
 "name": "youtube",
 "canonicalName": "YouTube",
 "version": "v3",
 "title": "YouTube Data API",
 "description": "Programmatic access to YouTube features.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/youtube/v3",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/youtube/v3/",
 "basePath": "/youtube/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "youtube/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtube": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.readonly": {
     "description": "View your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.upload": {
     "description": "Manage your YouTube videos"
    },
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    },
    "https://www.googleapis.com/auth/youtubepartner-channel-audit": {
     "description": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
    }
   }
  }
 },
 "resources": {
  "activities": {
   "methods": {
    "insert": {
     "id": "youtube.activities.insert",
     "path": "activities",
     "httpMethod": "POST",
     "description": "Posts a bulletin for a specific channel. (The user submitting the request must be authorized to act on the channel's behalf.)\n\nNote: Even though an activity resource can contain information about actions like a user rating a video or marking a video as a favorite, you need to use other API methods to generate those activity resources. For example, you would use the API's videos.rate() method to rate a video and the playlistItems.insert() method to mark a video as a favorit[...]",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "list": {
     "id": "youtube.activities.list",
     "path": "activities",
     "httpMethod": "GET",
     "description": "Returns a list of channel activity events that match the request criteria. For example, you can retrieve events associated with a particular channel, events associated with the user's subscriptions and Google+ friends, or the YouTube home page feed, which is customized for each user.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly"
     ]
    }
   }
  },
  "channelBanners": {
   "methods": {
    "insert": {
     "id": "youtube.channelBanners.insert",
     "path": "channelBanners/insert",
     "httpMethod": "POST",
     "description": "Uploads a channel banner image to YouTube. This method represents the first two steps in a three-step process to update the banner image for a channel:\n\n- Call the channelBanners.insert method to upload the binary image data to YouTube. The image must have a 16:9 aspect ratio and be at least 2120x1192 pixels.\n- Extract the url property's value from the response that the API returns for step 1.\n- Call the channels.update method to update the channel's branding settings. S[...]",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.upload"
     ],
     "supportsMediaUpload": true
    }
   }
  },
  "channelSections": {
   "methods": {
    "delete": {
     "id": "youtube.channelSections.delete",
     "path": "channelSections",
     "httpMethod": "DELETE",
     "description": "Deletes a channelSection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.channelSections.insert",
     "path": "channelSections",
     "httpMethod": "POST",
     "description": "Adds a channelSection for the authenticated user's channel.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.channelSections.list",
     "path": "channelSections",
     "httpMethod": "GET",
     "description": "Returns channelSection resources that match the API request criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtube.channelSections.update",
     "path": "channelSections",
     "httpMethod": "PUT",
     "description": "Update a channelSection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "channels": {
   "methods": {
    "list": {
     "id": "youtube.channels.list",
     "path": "channels",
     "httpMethod": "GET",
     "description": "Returns a collection of zero or more channel resources that match the request criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner",
      "https://www.googleapis.com/auth/youtubepartner-channel-audit"
     ]
    },
    "update": {
     "id": "youtube.channels.update",
     "path": "channels",
     "httpMethod": "PUT",
     "description": "Updates a channel's metadata.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "guideCategories": {
   "methods": {
    "list": {
     "id": "youtube.guideCategories.list",
     "path": "guideCategories",
     "httpMethod": "GET",
     "description": "Returns a list of categories that can be associated with YouTube channels.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "i18nLanguages": {
   "methods": {
    "list": {
     "id": "youtube.i18nLanguages.list",
     "path": "i18nLanguages",
     "httpMethod": "GET",
     "description": "Returns a list of supported languages.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "i18nRegions": {
   "methods": {
    "list": {
     "id": "youtube.i18nRegions.list",
     "path": "i18nRegions",
     "httpMethod": "GET",
     "description": "Returns a list of supported regions.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "liveBroadcasts": {
   "methods": {
    "bind": {
     "id": "youtube.liveBroadcasts.bind",
     "path": "liveBroadcasts/bind",
     "httpMethod": "POST",
     "description": "Binds a YouTube broadcast to a stream or removes an existing binding between a broadcast and a stream. A broadcast can only be bound to one video stream.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "control": {
     "id": "youtube.liveBroadcasts.control",
     "path": "liveBroadcasts/control",
     "httpMethod": "POST",
     "description": "Controls the settings for a slate that can be displayed in the broadcast stream.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "delete": {
     "id": "youtube.liveBroadcasts.delete",
     "path": "liveBroadcasts",
     "httpMethod": "DELETE",
     "description": "Deletes a broadcast.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "insert": {
     "id": "youtube.liveBroadcasts.insert",
     "path": "liveBroadcasts",
     "httpMethod": "POST",
     "description": "Creates a broadcast.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "list": {
     "id": "youtube.liveBroadcasts.list",
     "path": "liveBroadcasts",
     "httpMethod": "GET",
     "description": "Returns a list of YouTube broadcasts that match the API request parameters.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly"
     ]
    },
    "transition": {
     "id": "youtube.liveBroadcasts.transition",
     "path": "liveBroadcasts/transition",
     "httpMethod": "POST",
     "description": "Changes the status of a YouTube live broadcast and initiates any processes associated with the new status. For example, when you transition a broadcast's status to testing, YouTube starts to transmit video to that broadcast's monitor stream. Before calling this method, you should confirm that the value of the status.streamStatus property for the stream bound to your broadcast is active.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "update": {
     "id": "youtube.liveBroadcasts.update",
     "path": "liveBroadcasts",
     "httpMethod": "PUT",
     "description": "Updates a broadcast. For example, you could modify the broadcast settings defined in the liveBroadcast resource's contentDetails object.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    }
   }
  },
  "liveStreams": {
   "methods": {
    "delete": {
     "id": "youtube.liveStreams.delete",
     "path": "liveStreams",
     "httpMethod": "DELETE",
     "description": "Deletes a video stream.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "insert": {
     "id": "youtube.liveStreams.insert",
     "path": "liveStreams",
     "httpMethod": "POST",
     "description": "Creates a video stream. The stream enables you to send your video to YouTube, which can then broadcast the video to your audience.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "list": {
     "id": "youtube.liveStreams.list",
     "path": "liveStreams",
     "httpMethod": "GET",
     "description": "Returns a list of video streams that match the API request parameters.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly"
     ]
    },
    "update": {
     "id": "youtube.liveStreams.update",
     "path": "liveStreams",
     "httpMethod": "PUT",
     "description": "Updates a video stream. If the properties that you want to change cannot be updated, then you need to create a new stream with the proper settings.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    }
   }
  },
  "playlistItems": {
   "methods": {
    "delete": {
     "id": "youtube.playlistItems.delete",
     "path": "playlistItems",
     "httpMethod": "DELETE",
     "description": "Deletes a playlist item.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.playlistItems.insert",
     "path": "playlistItems",
     "httpMethod": "POST",
     "description": "Adds a resource to a playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.playlistItems.list",
     "path": "playlistItems",
     "httpMethod": "GET",
     "description": "Returns a collection of playlist items that match the API request parameters. You can retrieve all of the playlist items in a specified playlist or retrieve one or more playlist items by their unique IDs.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsSubscription": true
    },
    "update": {
     "id": "youtube.playlistItems.update",
     "path": "playlistItems",
     "httpMethod": "PUT",
     "description": "Modifies a playlist item. For example, you could update the item's position in the playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "playlists": {
   "methods": {
    "delete": {
     "id": "youtube.playlists.delete",
     "path": "playlists",
     "httpMethod": "DELETE",
     "description": "Deletes a playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.playlists.insert",
     "path": "playlists",
     "httpMethod": "POST",
     "description": "Creates a playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.playlists.list",
     "path": "playlists",
     "httpMethod": "GET",
     "description": "Returns a collection of playlists that match the API request parameters. For example, you can retrieve all playlists that the authenticated user owns, or you can retrieve one or more playlists by their unique IDs.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtube.playlists.update",
     "path": "playlists",
     "httpMethod": "PUT",
     "description": "Modifies a playlist. For example, you could change a playlist's title, description, or privacy status.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "search": {
   "methods": {
    "list": {
     "id": "youtube.search.list",
     "path": "search",
     "httpMethod": "GET",
     "description": "Returns a collection of search results that match the query parameters specified in the API request. By default, a search result set identifies matching video, channel, and playlist resources, but you can also configure queries to only retrieve a specific type of resource.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "subscriptions": {
   "methods": {
    "delete": {
     "id": "youtube.subscriptions.delete",
     "path": "subscriptions",
     "httpMethod": "DELETE",
     "description": "Deletes a subscription.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.subscriptions.insert",
     "path": "subscriptions",
     "httpMethod": "POST",
     "description": "Adds a subscription for the authenticated user's channel.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.subscriptions.list",
     "path": "subscriptions",
     "httpMethod": "GET",
     "description": "Returns subscription resources that match the API request criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "thumbnails": {
   "methods": {
    "set": {
     "id": "youtube.thumbnails.set",
     "path": "thumbnails/set",
     "httpMethod": "POST",
     "description": "Uploads a custom video thumbnail to YouTube and sets it for a video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaUpload": true
    }
   }
  },
  "videoCategories": {
   "methods": {
    "list": {
     "id": "youtube.videoCategories.list",
     "path": "videoCategories",
     "httpMethod": "GET",
     "description": "Returns a list of categories that can be associated with YouTube videos.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "videos": {
   "methods": {
    "delete": {
     "id": "youtube.videos.delete",
     "path": "videos",
     "httpMethod": "DELETE",
     "description": "Deletes a YouTube video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "getRating": {
     "id": "youtube.videos.getRating",
     "path": "videos/getRating",
     "httpMethod": "GET",
     "description": "Retrieves the ratings that the authorized user gave to a list of specified videos.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.videos.insert",
     "path": "videos",
     "httpMethod": "POST",
     "description": "Uploads a video to YouTube and optionally sets the video's metadata.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaUpload": true
    },
    "list": {
     "id": "youtube.videos.list",
     "path": "videos",
     "httpMethod": "GET",
     "description": "Returns a list of videos that match the API request parameters.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "rate": {
     "id": "youtube.videos.rate",
     "path": "videos/rate",
     "httpMethod": "POST",
     "description": "Add a like or dislike rating to a video or remove a rating from a video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtube.videos.update",
     "path": "videos",
     "httpMethod": "PUT",
     "description": "Updates a video's metadata.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "watermarks": {
   "methods": {
    "set": {
     "id": "youtube.watermarks.set",
     "path": "watermarks/set",
     "httpMethod": "POST",
     "description": "Uploads a watermark image to YouTube and sets it for a channel.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaUpload": true
    },
    "unset": {
     "id": "youtube.watermarks.unset",
     "path": "watermarks/unset",
     "httpMethod": "POST",
     "description": "Deletes a watermark.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  }
 }
}
