{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/5Hs2SYZ6tc8V9isLu4EuE8s9_qg\"",
 "discoveryVersion": "v1",
 "id": "taskqueue:v1beta2",
 "name": "taskqueue",
 "version": "v1beta2",
 "title": "TaskQueue API",
 "description": "Lets you access a Google App Engine Pull Task Queue over REST.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/appengine/docs/python/taskqueue/rest",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/taskqueue/v1beta2/projects/",
 "basePath": "/taskqueue/v1beta2/projects/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "taskqueue/v1beta2/projects/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/taskqueue": {
     "description": "Manage your Tasks and Taskqueues"
    },
    "https://www.googleapis.com/auth/taskqueue.consumer": {
     "description": "Consume Tasks from your Taskqueues"
    }
   }
  }
 },
 "resources": {
  "taskqueues": {
   "methods": {
    "get": {
     "id": "taskqueue.taskqueues.get",
     "path": "{project}/taskqueues/{taskqueue}",
     "httpMethod": "GET",
     "description": "Get detailed information about a TaskQueue.",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    }
   }
  },
  "tasks": {
   "methods": {
    "delete": {
     "id": "taskqueue.tasks.delete",
     "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
     "httpMethod": "DELETE",
     "description": "Delete a task from a TaskQueue.",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    },
    "get": {
     "id": "taskqueue.tasks.get",
     "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
     "httpMethod": "GET",
     "description": "Get a particular task from a TaskQueue.",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    },
    "insert": {
     "id": "taskqueue.tasks.insert",
     "path": "{project}/taskqueues/{taskqueue}/tasks",
     "httpMethod": "POST",
     "description": "Insert a new task in a TaskQueue",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    },
    "lease": {
     "id": "taskqueue.tasks.lease",
     "path": "{project}/taskqueues/{taskqueue}/tasks/lease",
     "httpMethod": "POST",
     "description": "Lease 1 or more tasks from a TaskQueue.",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    },
    "list": {
     "id": "taskqueue.tasks.list",
     "path": "{project}/taskqueues/{taskqueue}/tasks",
     "httpMethod": "GET",
     "description": "List Tasks in a TaskQueue",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    },
    "patch": {
     "id": "taskqueue.tasks.patch",
     "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
     "httpMethod": "PATCH",
     "description": "Update tasks that are leased out of a TaskQueue. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    },
    "update": {
     "id": "taskqueue.tasks.update",
     "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
     "httpMethod": "POST",
     "description": "Update tasks that are leased out of a TaskQueue.",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ]
    }
   }
  }
 }
}
