{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/TO0nvlGiFkC4eBcMUbWL9BiW0xc\"",
 "discoveryVersion": "v1",
 "id": "blogger:v3",
 "name": "blogger",
 "version": "v3",
 "title": "Blogger API",
 "description": "API for access to the data within Blogger.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/blogger/docs/3.0/getting_started",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/blogger/v3/",
 "basePath": "/blogger/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "blogger/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/blogger": {
     "description": "Manage your Blogger account"
    },
    "https://www.googleapis.com/auth/blogger.readonly": {
     "description": "View your Blogger account"
    }
   }
  }
 },
 "resources": {
  "blogUserInfos": {
   "methods": {
    "get": {
     "id": "blogger.blogUserInfos.get",
     "path": "users/{userId}/blogs/{blogId}",
     "httpMethod": "GET",
     "description": "Gets one blog and user info pair by blogId and userId.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    }
   }
  },
  "blogs": {
   "methods": {
    "get": {
     "id": "blogger.blogs.get",
     "path": "blogs/{blogId}",
     "httpMethod": "GET",
     "description": "Gets one blog by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "getByUrl": {
     "id": "blogger.blogs.getByUrl",
     "path": "blogs/byurl",
     "httpMethod": "GET",
     "description": "Retrieve a Blog by URL.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "listByUser": {
     "id": "blogger.blogs.listByUser",
     "path": "users/{userId}/blogs",
     "httpMethod": "GET",
     "description": "Retrieves a list of blogs, possibly filtered.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    }
   }
  },
  "comments": {
   "methods": {
    "approve": {
     "id": "blogger.comments.approve",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/approve",
     "httpMethod": "POST",
     "description": "Marks a comment as not spam.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "delete": {
     "id": "blogger.comments.delete",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}",
     "httpMethod": "DELETE",
     "description": "Delete a comment by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "get": {
     "id": "blogger.comments.get",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}",
     "httpMethod": "GET",
     "description": "Gets one comment by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "list": {
     "id": "blogger.comments.list",
     "path": "blogs/{blogId}/posts/{postId}/comments",
     "httpMethod": "GET",
     "description": "Retrieves the comments for a post, possibly filtered.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "listByBlog": {
     "id": "blogger.comments.listByBlog",
     "path": "blogs/{blogId}/comments",
     "httpMethod": "GET",
     "description": "Retrieves the comments for a blog, across all posts, possibly filtered.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "markAsSpam": {
     "id": "blogger.comments.markAsSpam",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/spam",
     "httpMethod": "POST",
     "description": "Marks a comment as spam.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "removeContent": {
     "id": "blogger.comments.removeContent",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent",
     "httpMethod": "POST",
     "description": "Removes the content of a comment.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    }
   }
  },
  "pageViews": {
   "methods": {
    "get": {
     "id": "blogger.pageViews.get",
     "path": "blogs/{blogId}/pageviews",
     "httpMethod": "GET",
     "description": "Retrieve pageview stats for a Blog.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    }
   }
  },
  "pages": {
   "methods": {
    "delete": {
     "id": "blogger.pages.delete",
     "path": "blogs/{blogId}/pages/{pageId}",
     "httpMethod": "DELETE",
     "description": "Delete a page by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "get": {
     "id": "blogger.pages.get",
     "path": "blogs/{blogId}/pages/{pageId}",
     "httpMethod": "GET",
     "description": "Gets one blog page by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "insert": {
     "id": "blogger.pages.insert",
     "path": "blogs/{blogId}/pages",
     "httpMethod": "POST",
     "description": "Add a page.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "list": {
     "id": "blogger.pages.list",
     "path": "blogs/{blogId}/pages",
     "httpMethod": "GET",
     "description": "Retrieves the pages for a blog, optionally including non-LIVE statuses.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "patch": {
     "id": "blogger.pages.patch",
     "path": "blogs/{blogId}/pages/{pageId}",
     "httpMethod": "PATCH",
     "description": "Update a page. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "update": {
     "id": "blogger.pages.update",
     "path": "blogs/{blogId}/pages/{pageId}",
     "httpMethod": "PUT",
     "description": "Update a page.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    }
   }
  },
  "postUserInfos": {
   "methods": {
    "get": {
     "id": "blogger.postUserInfos.get",
     "path": "users/{userId}/blogs/{blogId}/posts/{postId}",
     "httpMethod": "GET",
     "description": "Gets one post and user info pair, by post id and user id. The post user info contains per-user information about the post, such as access rights, specific to the user.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "list": {
     "id": "blogger.postUserInfos.list",
     "path": "users/{userId}/blogs/{blogId}/posts",
     "httpMethod": "GET",
     "description": "Retrieves a list of post and post user info pairs, possibly filtered. The post user info contains per-user information about the post, such as access rights, specific to the user.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    }
   }
  },
  "posts": {
   "methods": {
    "delete": {
     "id": "blogger.posts.delete",
     "path": "blogs/{blogId}/posts/{postId}",
     "httpMethod": "DELETE",
     "description": "Delete a post by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "get": {
     "id": "blogger.posts.get",
     "path": "blogs/{blogId}/posts/{postId}",
     "httpMethod": "GET",
     "description": "Get a post by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "getByPath": {
     "id": "blogger.posts.getByPath",
     "path": "blogs/{blogId}/posts/bypath",
     "httpMethod": "GET",
     "description": "Retrieve a Post by Path.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "insert": {
     "id": "blogger.posts.insert",
     "path": "blogs/{blogId}/posts",
     "httpMethod": "POST",
     "description": "Add a post.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "list": {
     "id": "blogger.posts.list",
     "path": "blogs/{blogId}/posts",
     "httpMethod": "GET",
     "description": "Retrieves a list of posts, possibly filtered.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "patch": {
     "id": "blogger.posts.patch",
     "path": "blogs/{blogId}/posts/{postId}",
     "httpMethod": "PATCH",
     "description": "Update a post. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "publish": {
     "id": "blogger.posts.publish",
     "path": "blogs/{blogId}/posts/{postId}/publish",
     "httpMethod": "POST",
     "description": "Publish a draft post.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "revert": {
     "id": "blogger.posts.revert",
     "path": "blogs/{blogId}/posts/{postId}/revert",
     "httpMethod": "POST",
     "description": "Revert a published or scheduled post to draft state.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    },
    "search": {
     "id": "blogger.posts.search",
     "path": "blogs/{blogId}/posts/search",
     "httpMethod": "GET",
     "description": "Search for a post.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    },
    "update": {
     "id": "blogger.posts.update",
     "path": "blogs/{blogId}/posts/{postId}",
     "httpMethod": "PUT",
     "description": "Update a post.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ]
    }
   }
  },
  "users": {
   "methods": {
    "get": {
     "id": "blogger.users.get",
     "path": "users/{userId}",
     "httpMethod": "GET",
     "description": "Gets one user by id.",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ]
    }
   }
  }
 }
}
