{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tasks": {
          "description": "Create, edit, organize, and delete all your tasks"
        },
        "https://www.googleapis.com/auth/tasks.readonly": {
          "description": "View your tasks"
        }
      }
    }
  },
  "basePath": "/tasks/v1/",
  "baseUrl": "https://www.googleapis.com/tasks/v1/",
  "batchPath": "batch/tasks/v1",
  "description": "Manages your tasks and task lists.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/google-apps/tasks/firstapp",
  "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/hFPeXxltvOJhEJjSu7bzNBnzbwY\"",
  "id": "tasks:v1",
  "kind": "discovery#restDescription",
  "name": "tasks",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "tasklists": {
      "methods": {
        "delete": {
          "description": "Deletes the authenticated user's specified task list.",
          "httpMethod": "DELETE",
          "id": "tasks.tasklists.delete",
          "path": "users/@me/lists/{tasklist}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "get": {
          "description": "Returns the authenticated user's specified task list.",
          "httpMethod": "GET",
          "id": "tasks.tasklists.get",
          "path": "users/@me/lists/{tasklist}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ]
        },
        "insert": {
          "description": "Creates a new task list and adds it to the authenticated user's task lists. Fails with HTTP code 403 or 429 after reaching the storage limit of 2,000 lists.",
          "httpMethod": "POST",
          "id": "tasks.tasklists.insert",
          "path": "users/@me/lists",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "list": {
          "description": "Returns all the authenticated user's task lists.",
          "httpMethod": "GET",
          "id": "tasks.tasklists.list",
          "path": "users/@me/lists",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ]
        },
        "patch": {
          "description": "Updates the authenticated user's specified task list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "tasks.tasklists.patch",
          "path": "users/@me/lists/{tasklist}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "update": {
          "description": "Updates the authenticated user's specified task list.",
          "httpMethod": "PUT",
          "id": "tasks.tasklists.update",
          "path": "users/@me/lists/{tasklist}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        }
      }
    },
    "tasks": {
      "methods": {
        "clear": {
          "description": "Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.",
          "httpMethod": "POST",
          "id": "tasks.tasks.clear",
          "path": "lists/{tasklist}/clear",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "delete": {
          "description": "Deletes the specified task from the task list.",
          "httpMethod": "DELETE",
          "id": "tasks.tasks.delete",
          "path": "lists/{tasklist}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "get": {
          "description": "Returns the specified task.",
          "httpMethod": "GET",
          "id": "tasks.tasks.get",
          "path": "lists/{tasklist}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ]
        },
        "insert": {
          "description": "Creates a new task on the specified task list. Fails with HTTP code 403 or 429 after reaching the storage limit of 100,000 tasks per account.",
          "httpMethod": "POST",
          "id": "tasks.tasks.insert",
          "path": "lists/{tasklist}/tasks",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "list": {
          "description": "Returns all tasks in the specified task list.",
          "httpMethod": "GET",
          "id": "tasks.tasks.list",
          "path": "lists/{tasklist}/tasks",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ]
        },
        "move": {
          "description": "Moves the specified task to another position in the task list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks.",
          "httpMethod": "POST",
          "id": "tasks.tasks.move",
          "path": "lists/{tasklist}/tasks/{task}/move",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "patch": {
          "description": "Updates the specified task. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "tasks.tasks.patch",
          "path": "lists/{tasklist}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "update": {
          "description": "Updates the specified task.",
          "httpMethod": "PUT",
          "id": "tasks.tasks.update",
          "path": "lists/{tasklist}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        }
      }
    }
  },
  "revision": "20200129",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "tasks/v1/",
  "title": "Tasks API",
  "version": "v1"
}