{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/6aC1_omptpkys969gj83ZtJAvZ8\"",
 "discoveryVersion": "v1",
 "id": "adexchangeseller:v2.0",
 "name": "adexchangeseller",
 "canonicalName": "Ad Exchange Seller",
 "version": "v2.0",
 "revision": "20141112",
 "title": "Ad Exchange Seller API",
 "description": "Gives Ad Exchange seller users access to their inventory and the ability to generate reports",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/ad-exchange/seller-rest/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/adexchangeseller/v2.0/",
 "basePath": "/adexchangeseller/v2.0/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "adexchangeseller/v2.0/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/adexchange.seller": {
     "description": "View and manage your Ad Exchange data"
    },
    "https://www.googleapis.com/auth/adexchange.seller.readonly": {
     "description": "View your Ad Exchange data"
    }
   }
  }
 },
 "resources": {
  "accounts": {
   "methods": {
    "get": {
     "id": "adexchangeseller.accounts.get",
     "path": "accounts/{accountId}",
     "httpMethod": "GET",
     "description": "Get information about the selected Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    },
    "list": {
     "id": "adexchangeseller.accounts.list",
     "path": "accounts",
     "httpMethod": "GET",
     "description": "List all accounts available to this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   },
   "resources": {
    "adclients": {
     "methods": {
      "list": {
       "id": "adexchangeseller.accounts.adclients.list",
       "path": "accounts/{accountId}/adclients",
       "httpMethod": "GET",
       "description": "List all ad clients in this Ad Exchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    },
    "alerts": {
     "methods": {
      "list": {
       "id": "adexchangeseller.accounts.alerts.list",
       "path": "accounts/{accountId}/alerts",
       "httpMethod": "GET",
       "description": "List the alerts for this Ad Exchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    },
    "customchannels": {
     "methods": {
      "get": {
       "id": "adexchangeseller.accounts.customchannels.get",
       "path": "accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}",
       "httpMethod": "GET",
       "description": "Get the specified custom channel from the specified ad client.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      },
      "list": {
       "id": "adexchangeseller.accounts.customchannels.list",
       "path": "accounts/{accountId}/adclients/{adClientId}/customchannels",
       "httpMethod": "GET",
       "description": "List all custom channels in the specified ad client for this Ad Exchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    },
    "metadata": {
     "resources": {
      "dimensions": {
       "methods": {
        "list": {
         "id": "adexchangeseller.accounts.metadata.dimensions.list",
         "path": "accounts/{accountId}/metadata/dimensions",
         "httpMethod": "GET",
         "description": "List the metadata for the dimensions available to this AdExchange account.",
         "scopes": [
          "https://www.googleapis.com/auth/adexchange.seller",
          "https://www.googleapis.com/auth/adexchange.seller.readonly"
         ]
        }
       }
      },
      "metrics": {
       "methods": {
        "list": {
         "id": "adexchangeseller.accounts.metadata.metrics.list",
         "path": "accounts/{accountId}/metadata/metrics",
         "httpMethod": "GET",
         "description": "List the metadata for the metrics available to this AdExchange account.",
         "scopes": [
          "https://www.googleapis.com/auth/adexchange.seller",
          "https://www.googleapis.com/auth/adexchange.seller.readonly"
         ]
        }
       }
      }
     }
    },
    "preferreddeals": {
     "methods": {
      "get": {
       "id": "adexchangeseller.accounts.preferreddeals.get",
       "path": "accounts/{accountId}/preferreddeals/{dealId}",
       "httpMethod": "GET",
       "description": "Get information about the selected Ad Exchange Preferred Deal.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      },
      "list": {
       "id": "adexchangeseller.accounts.preferreddeals.list",
       "path": "accounts/{accountId}/preferreddeals",
       "httpMethod": "GET",
       "description": "List the preferred deals for this Ad Exchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    },
    "reports": {
     "methods": {
      "generate": {
       "id": "adexchangeseller.accounts.reports.generate",
       "path": "accounts/{accountId}/reports",
       "httpMethod": "GET",
       "description": "Generate an Ad Exchange report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ],
       "supportsMediaDownload": true
      }
     },
     "resources": {
      "saved": {
       "methods": {
        "generate": {
         "id": "adexchangeseller.accounts.reports.saved.generate",
         "path": "accounts/{accountId}/reports/{savedReportId}",
         "httpMethod": "GET",
         "description": "Generate an Ad Exchange report based on the saved report ID sent in the query parameters.",
         "scopes": [
          "https://www.googleapis.com/auth/adexchange.seller",
          "https://www.googleapis.com/auth/adexchange.seller.readonly"
         ]
        },
        "list": {
         "id": "adexchangeseller.accounts.reports.saved.list",
         "path": "accounts/{accountId}/reports/saved",
         "httpMethod": "GET",
         "description": "List all saved reports in this Ad Exchange account.",
         "scopes": [
          "https://www.googleapis.com/auth/adexchange.seller",
          "https://www.googleapis.com/auth/adexchange.seller.readonly"
         ]
        }
       }
      }
     }
    },
    "urlchannels": {
     "methods": {
      "list": {
       "id": "adexchangeseller.accounts.urlchannels.list",
       "path": "accounts/{accountId}/adclients/{adClientId}/urlchannels",
       "httpMethod": "GET",
       "description": "List all URL channels in the specified ad client for this Ad Exchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
