// +build go1.9

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder

package blueprintapi

import original "github.com/Azure/azure-sdk-for-go/services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi"

type ArtifactsClientAPI = original.ArtifactsClientAPI
type AssignmentOperationsClientAPI = original.AssignmentOperationsClientAPI
type AssignmentsClientAPI = original.AssignmentsClientAPI
type BlueprintsClientAPI = original.BlueprintsClientAPI
type PublishedArtifactsClientAPI = original.PublishedArtifactsClientAPI
type PublishedBlueprintsClientAPI = original.PublishedBlueprintsClientAPI
