package(default_visibility = ["//visibility:public"])

licenses(["notice"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_binary",
    "go_library",
    "go_test",
    "cgo_library",
)

go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
        "fake_clusterrole.go",
        "fake_clusterrolebinding.go",
        "fake_rbac_client.go",
        "fake_role.go",
        "fake_rolebinding.go",
    ],
    tags = ["automanaged"],
)
