{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/ZeC-oWzDKj1E5_H69LVDW5wAByE\"",
 "discoveryVersion": "v1",
 "id": "appsactivity:v1",
 "name": "appsactivity",
 "version": "v1",
 "revision": "20150326",
 "title": "Google Apps Activity API",
 "description": "Provides a historical view of activity.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/google-apps/activity/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/appsactivity/v1/",
 "basePath": "/appsactivity/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "appsactivity/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/activity": {
     "description": "View the activity history of your Google Apps"
    },
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.metadata": {
     "description": "View and manage metadata of files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.metadata.readonly": {
     "description": "View metadata for files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "View the files in your Google Drive"
    }
   }
  }
 },
 "resources": {
  "activities": {
   "methods": {
    "list": {
     "id": "appsactivity.activities.list",
     "path": "activities",
     "httpMethod": "GET",
     "description": "Returns a list of activities visible to the current logged in user. Visible activities are determined by the visiblity settings of the object that was acted on, e.g. Drive files a user can see. An activity is a record of past events. Multiple events may be merged if they are similar. A request is scoped to activities from a given Google service using the source parameter.",
     "scopes": [
      "https://www.googleapis.com/auth/activity",
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  }
 }
}
