package(default_visibility = ["//visibility:public"])

licenses(["notice"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_library",
)

go_library(
    name = "go_default_library",
    srcs = [
        "factory.go",
        "generic.go",
    ],
    tags = ["automanaged"],
    deps = [
        "//vendor/k8s.io/apimachinery/pkg/runtime:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema:go_default_library",
        "//vendor/k8s.io/client-go/informers/admissionregistration:go_default_library",
        "//vendor/k8s.io/client-go/informers/apps:go_default_library",
        "//vendor/k8s.io/client-go/informers/autoscaling:go_default_library",
        "//vendor/k8s.io/client-go/informers/batch:go_default_library",
        "//vendor/k8s.io/client-go/informers/certificates:go_default_library",
        "//vendor/k8s.io/client-go/informers/core:go_default_library",
        "//vendor/k8s.io/client-go/informers/extensions:go_default_library",
        "//vendor/k8s.io/client-go/informers/internalinterfaces:go_default_library",
        "//vendor/k8s.io/client-go/informers/networking:go_default_library",
        "//vendor/k8s.io/client-go/informers/policy:go_default_library",
        "//vendor/k8s.io/client-go/informers/rbac:go_default_library",
        "//vendor/k8s.io/client-go/informers/settings:go_default_library",
        "//vendor/k8s.io/client-go/informers/storage:go_default_library",
        "//vendor/k8s.io/client-go/kubernetes:go_default_library",
        "//vendor/k8s.io/client-go/pkg/api/v1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/admissionregistration/v1alpha1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/apps/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/autoscaling/v1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/autoscaling/v2alpha1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/batch/v1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/batch/v2alpha1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/certificates/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/extensions/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/networking/v1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/policy/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/rbac/v1alpha1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/rbac/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/settings/v1alpha1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/storage/v1:go_default_library",
        "//vendor/k8s.io/client-go/pkg/apis/storage/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/tools/cache:go_default_library",
    ],
)
