{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/nYpof5sWVgQxA1Kf0FAXxMsfkXY\"",
 "discoveryVersion": "v1",
 "id": "analytics:v3",
 "name": "analytics",
 "version": "v3",
 "title": "Google Analytics API",
 "description": "View and manage your Google Analytics data",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/analytics/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/analytics/v3/",
 "basePath": "/analytics/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "analytics/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/analytics": {
     "description": "View and manage your Google Analytics data"
    },
    "https://www.googleapis.com/auth/analytics.edit": {
     "description": "Edit Google Analytics management entities"
    },
    "https://www.googleapis.com/auth/analytics.manage.users": {
     "description": "Manage Google Analytics Account users by email address"
    },
    "https://www.googleapis.com/auth/analytics.readonly": {
     "description": "View your Google Analytics data"
    }
   }
  }
 },
 "resources": {
  "data": {
   "resources": {
    "ga": {
     "methods": {
      "get": {
       "id": "analytics.data.ga.get",
       "path": "data/ga",
       "httpMethod": "GET",
       "description": "Returns Analytics data for a view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "mcf": {
     "methods": {
      "get": {
       "id": "analytics.data.mcf.get",
       "path": "data/mcf",
       "httpMethod": "GET",
       "description": "Returns Analytics Multi-Channel Funnels data for a view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "realtime": {
     "methods": {
      "get": {
       "id": "analytics.data.realtime.get",
       "path": "data/realtime",
       "httpMethod": "GET",
       "description": "Returns real time data for a view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    }
   }
  },
  "management": {
   "resources": {
    "accountSummaries": {
     "methods": {
      "list": {
       "id": "analytics.management.accountSummaries.list",
       "path": "management/accountSummaries",
       "httpMethod": "GET",
       "description": "Lists account summaries (lightweight tree comprised of accounts/properties/profiles) to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "accountUserLinks": {
     "methods": {
      "delete": {
       "id": "analytics.management.accountUserLinks.delete",
       "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
       "httpMethod": "DELETE",
       "description": "Removes a user from the given account.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "insert": {
       "id": "analytics.management.accountUserLinks.insert",
       "path": "management/accounts/{accountId}/entityUserLinks",
       "httpMethod": "POST",
       "description": "Adds a new user to the given account.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "list": {
       "id": "analytics.management.accountUserLinks.list",
       "path": "management/accounts/{accountId}/entityUserLinks",
       "httpMethod": "GET",
       "description": "Lists account-user links for a given account.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "update": {
       "id": "analytics.management.accountUserLinks.update",
       "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
       "httpMethod": "PUT",
       "description": "Updates permissions for an existing user on the given account.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      }
     }
    },
    "accounts": {
     "methods": {
      "list": {
       "id": "analytics.management.accounts.list",
       "path": "management/accounts",
       "httpMethod": "GET",
       "description": "Lists all accounts to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "customDataSources": {
     "methods": {
      "list": {
       "id": "analytics.management.customDataSources.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources",
       "httpMethod": "GET",
       "description": "List custom data sources to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "dailyUploads": {
     "methods": {
      "delete": {
       "id": "analytics.management.dailyUploads.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/dailyUploads/{date}",
       "httpMethod": "DELETE",
       "description": "Delete uploaded data for the given date.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "list": {
       "id": "analytics.management.dailyUploads.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/dailyUploads",
       "httpMethod": "GET",
       "description": "List daily uploads to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "upload": {
       "id": "analytics.management.dailyUploads.upload",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/dailyUploads/{date}/uploads",
       "httpMethod": "POST",
       "description": "Update/Overwrite data for a custom data source.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "experiments": {
     "methods": {
      "delete": {
       "id": "analytics.management.experiments.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "httpMethod": "DELETE",
       "description": "Delete an experiment.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "get": {
       "id": "analytics.management.experiments.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "httpMethod": "GET",
       "description": "Returns an experiment to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "insert": {
       "id": "analytics.management.experiments.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
       "httpMethod": "POST",
       "description": "Create a new experiment.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "list": {
       "id": "analytics.management.experiments.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
       "httpMethod": "GET",
       "description": "Lists experiments to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "patch": {
       "id": "analytics.management.experiments.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "httpMethod": "PATCH",
       "description": "Update an existing experiment. This method supports patch semantics.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "update": {
       "id": "analytics.management.experiments.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "httpMethod": "PUT",
       "description": "Update an existing experiment.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      }
     }
    },
    "goals": {
     "methods": {
      "get": {
       "id": "analytics.management.goals.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
       "httpMethod": "GET",
       "description": "Gets a goal to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "insert": {
       "id": "analytics.management.goals.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "httpMethod": "POST",
       "description": "Create a new goal.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "list": {
       "id": "analytics.management.goals.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "httpMethod": "GET",
       "description": "Lists goals to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "patch": {
       "id": "analytics.management.goals.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
       "httpMethod": "PATCH",
       "description": "Updates an existing view (profile). This method supports patch semantics.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "update": {
       "id": "analytics.management.goals.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
       "httpMethod": "PUT",
       "description": "Updates an existing view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      }
     }
    },
    "profileUserLinks": {
     "methods": {
      "delete": {
       "id": "analytics.management.profileUserLinks.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
       "httpMethod": "DELETE",
       "description": "Removes a user from the given view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "insert": {
       "id": "analytics.management.profileUserLinks.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
       "httpMethod": "POST",
       "description": "Adds a new user to the given view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "list": {
       "id": "analytics.management.profileUserLinks.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
       "httpMethod": "GET",
       "description": "Lists profile-user links for a given view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "update": {
       "id": "analytics.management.profileUserLinks.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
       "httpMethod": "PUT",
       "description": "Updates permissions for an existing user on the given view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      }
     }
    },
    "profiles": {
     "methods": {
      "delete": {
       "id": "analytics.management.profiles.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "httpMethod": "DELETE",
       "description": "Deletes a view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "get": {
       "id": "analytics.management.profiles.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "httpMethod": "GET",
       "description": "Gets a view (profile) to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "insert": {
       "id": "analytics.management.profiles.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "httpMethod": "POST",
       "description": "Create a new view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "list": {
       "id": "analytics.management.profiles.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "httpMethod": "GET",
       "description": "Lists views (profiles) to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "patch": {
       "id": "analytics.management.profiles.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "httpMethod": "PATCH",
       "description": "Updates an existing view (profile). This method supports patch semantics.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "update": {
       "id": "analytics.management.profiles.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "httpMethod": "PUT",
       "description": "Updates an existing view (profile).",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      }
     }
    },
    "segments": {
     "methods": {
      "list": {
       "id": "analytics.management.segments.list",
       "path": "management/segments",
       "httpMethod": "GET",
       "description": "Lists segments to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "uploads": {
     "methods": {
      "deleteUploadData": {
       "id": "analytics.management.uploads.deleteUploadData",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData",
       "httpMethod": "POST",
       "description": "Delete data associated with a previous upload.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "get": {
       "id": "analytics.management.uploads.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}",
       "httpMethod": "GET",
       "description": "List uploads to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "list": {
       "id": "analytics.management.uploads.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
       "httpMethod": "GET",
       "description": "List uploads to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "uploadData": {
       "id": "analytics.management.uploads.uploadData",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
       "httpMethod": "POST",
       "description": "Upload data for a custom data source.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "webproperties": {
     "methods": {
      "get": {
       "id": "analytics.management.webproperties.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
       "httpMethod": "GET",
       "description": "Gets a web property to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "insert": {
       "id": "analytics.management.webproperties.insert",
       "path": "management/accounts/{accountId}/webproperties",
       "httpMethod": "POST",
       "description": "Create a new property if the account has fewer than 20 properties. Web properties are visible in the Google Analytics interface only if they have at least one profile.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "list": {
       "id": "analytics.management.webproperties.list",
       "path": "management/accounts/{accountId}/webproperties",
       "httpMethod": "GET",
       "description": "Lists web properties to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "patch": {
       "id": "analytics.management.webproperties.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
       "httpMethod": "PATCH",
       "description": "Updates an existing web property. This method supports patch semantics.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      },
      "update": {
       "id": "analytics.management.webproperties.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
       "httpMethod": "PUT",
       "description": "Updates an existing web property.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ]
      }
     }
    },
    "webpropertyUserLinks": {
     "methods": {
      "delete": {
       "id": "analytics.management.webpropertyUserLinks.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
       "httpMethod": "DELETE",
       "description": "Removes a user from the given web property.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "insert": {
       "id": "analytics.management.webpropertyUserLinks.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
       "httpMethod": "POST",
       "description": "Adds a new user to the given web property.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "list": {
       "id": "analytics.management.webpropertyUserLinks.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
       "httpMethod": "GET",
       "description": "Lists webProperty-user links for a given web property.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      },
      "update": {
       "id": "analytics.management.webpropertyUserLinks.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
       "httpMethod": "PUT",
       "description": "Updates permissions for an existing user on the given web property.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ]
      }
     }
    }
   }
  },
  "metadata": {
   "resources": {
    "columns": {
     "methods": {
      "list": {
       "id": "analytics.metadata.columns.list",
       "path": "metadata/{reportType}/columns",
       "httpMethod": "GET",
       "description": "Lists all columns for a report type",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
