load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["config.go"],
    importpath = "k8s.io/kubernetes/cmd/kubelet/pkg/apis/resourcemetrics/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd/kubelet/pkg/apis/stats/v1alpha1:go_default_library",
        "//cmd/kubelet/pkg/server/stats:go_default_library",
    ],
)

filegroup(
    name = "package-srcs",
    srcs = glob(["**"]),
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)

filegroup(
    name = "all-srcs",
    srcs = [":package-srcs"],
    tags = ["automanaged"],
    visibility = ["//visibility:public"],
)
