{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/WULtnL9Z3EMEMURHbmsYLMeTjK8\"",
 "discoveryVersion": "v1",
 "id": "youtubeAnalytics:v1beta1",
 "name": "youtubeAnalytics",
 "canonicalName": "YouTube Analytics",
 "version": "v1beta1",
 "revision": "20151211",
 "title": "YouTube Analytics API",
 "description": "Retrieve your YouTube Analytics reports.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "http://developers.google.com/youtube/analytics/",
 "labels": [
  "deprecated"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/youtube/analytics/v1beta1/",
 "basePath": "/youtube/analytics/v1beta1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "youtube/analytics/v1beta1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtube": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.readonly": {
     "description": "View your YouTube account"
    },
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    },
    "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
     "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
    },
    "https://www.googleapis.com/auth/yt-analytics.readonly": {
     "description": "View YouTube Analytics reports for your YouTube content"
    }
   }
  }
 },
 "resources": {
  "batchReportDefinitions": {
   "methods": {
    "list": {
     "id": "youtubeAnalytics.batchReportDefinitions.list",
     "path": "batchReportDefinitions",
     "httpMethod": "GET",
     "description": "Retrieves a list of available batch report definitions.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    }
   }
  },
  "batchReports": {
   "methods": {
    "list": {
     "id": "youtubeAnalytics.batchReports.list",
     "path": "batchReports",
     "httpMethod": "GET",
     "description": "Retrieves a list of processed batch reports.",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    }
   }
  },
  "groupItems": {
   "methods": {
    "delete": {
     "id": "youtubeAnalytics.groupItems.delete",
     "path": "groupItems",
     "httpMethod": "DELETE",
     "description": "Removes an item from a group.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubeAnalytics.groupItems.insert",
     "path": "groupItems",
     "httpMethod": "POST",
     "description": "Creates a group item.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubeAnalytics.groupItems.list",
     "path": "groupItems",
     "httpMethod": "GET",
     "description": "Returns a collection of group items that match the API request parameters.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    }
   }
  },
  "groups": {
   "methods": {
    "delete": {
     "id": "youtubeAnalytics.groups.delete",
     "path": "groups",
     "httpMethod": "DELETE",
     "description": "Deletes a group.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubeAnalytics.groups.insert",
     "path": "groups",
     "httpMethod": "POST",
     "description": "Creates a group.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubeAnalytics.groups.list",
     "path": "groups",
     "httpMethod": "GET",
     "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    },
    "update": {
     "id": "youtubeAnalytics.groups.update",
     "path": "groups",
     "httpMethod": "PUT",
     "description": "Modifies a group. For example, you could change a group's title.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "reports": {
   "methods": {
    "query": {
     "id": "youtubeAnalytics.reports.query",
     "path": "reports",
     "httpMethod": "GET",
     "description": "Retrieve your YouTube Analytics reports.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ]
    }
   }
  }
 }
}
