{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.delete.containers": {
          "description": "Delete your Google Tag Manager containers"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containers": {
          "description": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
          "description": "Manage your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
          "description": "View and manage your Google Tag Manager accounts"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.users": {
          "description": "Manage user permissions of your Google Tag Manager account and container"
        },
        "https://www.googleapis.com/auth/tagmanager.publish": {
          "description": "Publish your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.readonly": {
          "description": "View your Google Tag Manager container and its subcomponents"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://www.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Tag Manager",
  "description": "This API allows clients to access and modify container and tag\n     configuration.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/tag-manager",
  "id": "tagmanager:v2",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "name": "tagmanager",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "accounts": {
      "methods": {
        "get": {
          "description": "Gets a GTM Account.",
          "flatPath": "tagmanager/v2/accounts/{accountsId}",
          "httpMethod": "GET",
          "id": "tagmanager.accounts.get",
          "path": "tagmanager/v2/{+path}",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ]
        },
        "list": {
          "description": "Lists all GTM Accounts that a user has access to.",
          "flatPath": "tagmanager/v2/accounts",
          "httpMethod": "GET",
          "id": "tagmanager.accounts.list",
          "path": "tagmanager/v2/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ]
        },
        "update": {
          "description": "Updates a GTM Account.",
          "flatPath": "tagmanager/v2/accounts/{accountsId}",
          "httpMethod": "PUT",
          "id": "tagmanager.accounts.update",
          "path": "tagmanager/v2/{+path}",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.manage.accounts"
          ]
        }
      },
      "resources": {
        "containers": {
          "methods": {
            "create": {
              "description": "Creates a Container.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers",
              "httpMethod": "POST",
              "id": "tagmanager.accounts.containers.create",
              "path": "tagmanager/v2/{+parent}/containers",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ]
            },
            "delete": {
              "description": "Deletes a Container.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
              "httpMethod": "DELETE",
              "id": "tagmanager.accounts.containers.delete",
              "path": "tagmanager/v2/{+path}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.delete.containers"
              ]
            },
            "get": {
              "description": "Gets a Container.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
              "httpMethod": "GET",
              "id": "tagmanager.accounts.containers.get",
              "path": "tagmanager/v2/{+path}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ]
            },
            "list": {
              "description": "Lists all Containers that belongs to a GTM Account.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers",
              "httpMethod": "GET",
              "id": "tagmanager.accounts.containers.list",
              "path": "tagmanager/v2/{+parent}/containers",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ]
            },
            "update": {
              "description": "Updates a Container.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
              "httpMethod": "PUT",
              "id": "tagmanager.accounts.containers.update",
              "path": "tagmanager/v2/{+path}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ]
            }
          },
          "resources": {
            "environments": {
              "methods": {
                "create": {
                  "description": "Creates a GTM Environment.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.environments.create",
                  "path": "tagmanager/v2/{+parent}/environments",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "delete": {
                  "description": "Deletes a GTM Environment.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                  "httpMethod": "DELETE",
                  "id": "tagmanager.accounts.containers.environments.delete",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "get": {
                  "description": "Gets a GTM Environment.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.environments.get",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "list": {
                  "description": "Lists all GTM Environments of a GTM Container.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.environments.list",
                  "path": "tagmanager/v2/{+parent}/environments",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "reauthorize": {
                  "description": "Re-generates the authorization code for a GTM Environment.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}:reauthorize",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.environments.reauthorize",
                  "path": "tagmanager/v2/{+path}:reauthorize",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ]
                },
                "update": {
                  "description": "Updates a GTM Environment.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                  "httpMethod": "PUT",
                  "id": "tagmanager.accounts.containers.environments.update",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                }
              }
            },
            "version_headers": {
              "methods": {
                "latest": {
                  "description": "Gets the latest container version header",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers:latest",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.version_headers.latest",
                  "path": "tagmanager/v2/{+parent}/version_headers:latest",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "list": {
                  "description": "Lists all Container Versions of a GTM Container.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.version_headers.list",
                  "path": "tagmanager/v2/{+parent}/version_headers",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                }
              }
            },
            "versions": {
              "methods": {
                "delete": {
                  "description": "Deletes a Container Version.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                  "httpMethod": "DELETE",
                  "id": "tagmanager.accounts.containers.versions.delete",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                },
                "get": {
                  "description": "Gets a Container Version.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.versions.get",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "live": {
                  "description": "Gets the live (i.e. published) container version",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions:live",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.versions.live",
                  "path": "tagmanager/v2/{+parent}/versions:live",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "publish": {
                  "description": "Publishes a Container Version.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:publish",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.versions.publish",
                  "path": "tagmanager/v2/{+path}:publish",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ]
                },
                "set_latest": {
                  "description": "Sets the latest version used for synchronization of workspaces when\ndetecting conflicts and errors.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:set_latest",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.versions.set_latest",
                  "path": "tagmanager/v2/{+path}:set_latest",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "undelete": {
                  "description": "Undeletes a Container Version.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:undelete",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.versions.undelete",
                  "path": "tagmanager/v2/{+path}:undelete",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                },
                "update": {
                  "description": "Updates a Container Version.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                  "httpMethod": "PUT",
                  "id": "tagmanager.accounts.containers.versions.update",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                }
              }
            },
            "workspaces": {
              "methods": {
                "create": {
                  "description": "Creates a Workspace.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.workspaces.create",
                  "path": "tagmanager/v2/{+parent}/workspaces",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "create_version": {
                  "description": "Creates a Container Version from the entities present in the workspace,\ndeletes the workspace, and sets the base container version to the newly\ncreated version.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:create_version",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.workspaces.create_version",
                  "path": "tagmanager/v2/{+path}:create_version",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                },
                "delete": {
                  "description": "Deletes a Workspace.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                  "httpMethod": "DELETE",
                  "id": "tagmanager.accounts.containers.workspaces.delete",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.delete.containers"
                  ]
                },
                "get": {
                  "description": "Gets a Workspace.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.workspaces.get",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "getStatus": {
                  "description": "Finds conflicting and modified entities in the workspace.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/status",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.workspaces.getStatus",
                  "path": "tagmanager/v2/{+path}/status",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "list": {
                  "description": "Lists all Workspaces that belong to a GTM Container.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces",
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.workspaces.list",
                  "path": "tagmanager/v2/{+parent}/workspaces",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "quick_preview": {
                  "description": "Quick previews a workspace by creating a fake container version from all\nentities in the provided workspace.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:quick_preview",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.workspaces.quick_preview",
                  "path": "tagmanager/v2/{+path}:quick_preview",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                },
                "resolve_conflict": {
                  "description": "Resolves a merge conflict for a workspace entity by updating it to the\nresolved entity passed in the request.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:resolve_conflict",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.workspaces.resolve_conflict",
                  "path": "tagmanager/v2/{+path}:resolve_conflict",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "sync": {
                  "description": "Syncs a workspace to the latest container version by updating all\nunmodified workspace entities and displaying conflicts for modified\nentities.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:sync",
                  "httpMethod": "POST",
                  "id": "tagmanager.accounts.containers.workspaces.sync",
                  "path": "tagmanager/v2/{+path}:sync",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "update": {
                  "description": "Updates a Workspace.",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                  "httpMethod": "PUT",
                  "id": "tagmanager.accounts.containers.workspaces.update",
                  "path": "tagmanager/v2/{+path}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                }
              },
              "resources": {
                "built_in_variables": {
                  "methods": {
                    "create": {
                      "description": "Creates one or more GTM Built-In Variables.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.create",
                      "path": "tagmanager/v2/{+parent}/built_in_variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes one or more GTM Built-In Variables.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "list": {
                      "description": "Lists all the enabled Built-In Variables of a GTM Container.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.list",
                      "path": "tagmanager/v2/{+parent}/built_in_variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Built-In Variables in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.revert",
                      "path": "tagmanager/v2/{+path}/built_in_variables:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                },
                "folders": {
                  "methods": {
                    "create": {
                      "description": "Creates a GTM Folder.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.folders.create",
                      "path": "tagmanager/v2/{+parent}/folders",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Folder.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.folders.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "entities": {
                      "description": "List all entities in a GTM Folder.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:entities",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.folders.entities",
                      "path": "tagmanager/v2/{+path}:entities",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "get": {
                      "description": "Gets a GTM Folder.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.folders.get",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists all GTM Folders of a Container.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.folders.list",
                      "path": "tagmanager/v2/{+parent}/folders",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "move_entities_to_folder": {
                      "description": "Moves entities to a GTM Folder.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:move_entities_to_folder",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.folders.move_entities_to_folder",
                      "path": "tagmanager/v2/{+path}:move_entities_to_folder",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Folder in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.folders.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "update": {
                      "description": "Updates a GTM Folder.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                      "httpMethod": "PUT",
                      "id": "tagmanager.accounts.containers.workspaces.folders.update",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                },
                "tags": {
                  "methods": {
                    "create": {
                      "description": "Creates a GTM Tag.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.tags.create",
                      "path": "tagmanager/v2/{+parent}/tags",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Tag.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.tags.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "get": {
                      "description": "Gets a GTM Tag.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.tags.get",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists all GTM Tags of a Container.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.tags.list",
                      "path": "tagmanager/v2/{+parent}/tags",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Tag in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.tags.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "update": {
                      "description": "Updates a GTM Tag.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                      "httpMethod": "PUT",
                      "id": "tagmanager.accounts.containers.workspaces.tags.update",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                },
                "templates": {
                  "methods": {
                    "create": {
                      "description": "Creates a GTM Custom Template.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.templates.create",
                      "path": "tagmanager/v2/{+parent}/templates",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Template.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.templates.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "get": {
                      "description": "Gets a GTM Template.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.templates.get",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists all GTM Templates of a GTM container workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.templates.list",
                      "path": "tagmanager/v2/{+parent}/templates",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Template in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.templates.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "update": {
                      "description": "Updates a GTM Template.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                      "httpMethod": "PUT",
                      "id": "tagmanager.accounts.containers.workspaces.templates.update",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                },
                "triggers": {
                  "methods": {
                    "create": {
                      "description": "Creates a GTM Trigger.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.triggers.create",
                      "path": "tagmanager/v2/{+parent}/triggers",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Trigger.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.triggers.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "get": {
                      "description": "Gets a GTM Trigger.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.triggers.get",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists all GTM Triggers of a Container.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.triggers.list",
                      "path": "tagmanager/v2/{+parent}/triggers",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Trigger in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.triggers.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "update": {
                      "description": "Updates a GTM Trigger.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                      "httpMethod": "PUT",
                      "id": "tagmanager.accounts.containers.workspaces.triggers.update",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                },
                "variables": {
                  "methods": {
                    "create": {
                      "description": "Creates a GTM Variable.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.variables.create",
                      "path": "tagmanager/v2/{+parent}/variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Variable.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.variables.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "get": {
                      "description": "Gets a GTM Variable.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.variables.get",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists all GTM Variables of a Container.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.variables.list",
                      "path": "tagmanager/v2/{+parent}/variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Variable in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.variables.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "update": {
                      "description": "Updates a GTM Variable.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                      "httpMethod": "PUT",
                      "id": "tagmanager.accounts.containers.workspaces.variables.update",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                },
                "zones": {
                  "methods": {
                    "create": {
                      "description": "Creates a GTM Zone.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.zones.create",
                      "path": "tagmanager/v2/{+parent}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Zone.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.zones.delete",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "get": {
                      "description": "Gets a GTM Zone.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.zones.get",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists all GTM Zones of a GTM container workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones",
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.zones.list",
                      "path": "tagmanager/v2/{+parent}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Zone in a GTM Workspace.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}:revert",
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.zones.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "update": {
                      "description": "Updates a GTM Zone.",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                      "httpMethod": "PUT",
                      "id": "tagmanager.accounts.containers.workspaces.zones.update",
                      "path": "tagmanager/v2/{+path}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "user_permissions": {
          "methods": {
            "create": {
              "description": "Creates a user's Account \u0026 Container access.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions",
              "httpMethod": "POST",
              "id": "tagmanager.accounts.user_permissions.create",
              "path": "tagmanager/v2/{+parent}/user_permissions",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            },
            "delete": {
              "description": "Removes a user from the account, revoking access to it and all of its\ncontainers.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
              "httpMethod": "DELETE",
              "id": "tagmanager.accounts.user_permissions.delete",
              "path": "tagmanager/v2/{+path}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            },
            "get": {
              "description": "Gets a user's Account \u0026 Container access.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
              "httpMethod": "GET",
              "id": "tagmanager.accounts.user_permissions.get",
              "path": "tagmanager/v2/{+path}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            },
            "list": {
              "description": "List all users that have access to the account along with Account and\nContainer user access granted to each of them.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions",
              "httpMethod": "GET",
              "id": "tagmanager.accounts.user_permissions.list",
              "path": "tagmanager/v2/{+parent}/user_permissions",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            },
            "update": {
              "description": "Updates a user's Account \u0026 Container access.",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
              "httpMethod": "PUT",
              "id": "tagmanager.accounts.user_permissions.update",
              "path": "tagmanager/v2/{+path}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20200220",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "",
  "title": "Tag Manager API",
  "version": "v2"
}