{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/apps.order": {
          "description": "Manage users on your domain"
        },
        "https://www.googleapis.com/auth/apps.order.readonly": {
          "description": "Manage users on your domain"
        }
      }
    }
  },
  "basePath": "/apps/reseller/v1/",
  "baseUrl": "https://www.googleapis.com/apps/reseller/v1/",
  "batchPath": "batch/reseller/v1",
  "description": "Creates and manages your customers and their subscriptions.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/google-apps/reseller/",
  "etag": "\"F5McR9eEaw0XRpaO3M9gbIugkbs/4xq0Bw2LuAbeJZTw0U29AruL5y4\"",
  "id": "reseller:v1",
  "kind": "discovery#restDescription",
  "labels": [
    "limited_availability"
  ],
  "name": "reseller",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "customers": {
      "methods": {
        "get": {
          "description": "Get a customer account.",
          "httpMethod": "GET",
          "id": "reseller.customers.get",
          "path": "customers/{customerId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ]
        },
        "insert": {
          "description": "Order a new customer's account.",
          "httpMethod": "POST",
          "id": "reseller.customers.insert",
          "path": "customers",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "patch": {
          "description": "Update a customer account's settings. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "reseller.customers.patch",
          "path": "customers/{customerId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "update": {
          "description": "Update a customer account's settings.",
          "httpMethod": "PUT",
          "id": "reseller.customers.update",
          "path": "customers/{customerId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        }
      }
    },
    "resellernotify": {
      "methods": {
        "getwatchdetails": {
          "description": "Returns all the details of the watch corresponding to the reseller.",
          "httpMethod": "GET",
          "id": "reseller.resellernotify.getwatchdetails",
          "path": "resellernotify/getwatchdetails",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ]
        },
        "register": {
          "description": "Registers a Reseller for receiving notifications.",
          "httpMethod": "POST",
          "id": "reseller.resellernotify.register",
          "path": "resellernotify/register",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "unregister": {
          "description": "Unregisters a Reseller for receiving notifications.",
          "httpMethod": "POST",
          "id": "reseller.resellernotify.unregister",
          "path": "resellernotify/unregister",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        }
      }
    },
    "subscriptions": {
      "methods": {
        "activate": {
          "description": "Activates a subscription previously suspended by the reseller",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.activate",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}/activate",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "changePlan": {
          "description": "Update a subscription plan. Use this method to update a plan for a 30-day trial or a flexible plan subscription to an annual commitment plan with monthly or yearly payments.",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.changePlan",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "changeRenewalSettings": {
          "description": "Update a user license's renewal settings. This is applicable for accounts with annual commitment plans only.",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.changeRenewalSettings",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "changeSeats": {
          "description": "Update a subscription's user license settings.",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.changeSeats",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "delete": {
          "description": "Cancel, suspend, or transfer a subscription to direct.",
          "httpMethod": "DELETE",
          "id": "reseller.subscriptions.delete",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "get": {
          "description": "Get a specific subscription.",
          "httpMethod": "GET",
          "id": "reseller.subscriptions.get",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ]
        },
        "insert": {
          "description": "Create or transfer a subscription.",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.insert",
          "path": "customers/{customerId}/subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "list": {
          "description": "List of subscriptions managed by the reseller. The list can be all subscriptions, all of a customer's subscriptions, or all of a customer's transferable subscriptions.",
          "httpMethod": "GET",
          "id": "reseller.subscriptions.list",
          "path": "subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ]
        },
        "startPaidService": {
          "description": "Immediately move a 30-day free trial subscription to a paid service subscription.",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.startPaidService",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "suspend": {
          "description": "Suspends an active subscription.",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.suspend",
          "path": "customers/{customerId}/subscriptions/{subscriptionId}/suspend",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        }
      }
    }
  },
  "revision": "20191008",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "apps/reseller/v1/",
  "title": "Enterprise Apps Reseller API",
  "version": "v1"
}