package(default_visibility = ["//visibility:public"])

licenses(["notice"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_binary",
    "go_library",
    "go_test",
    "cgo_library",
)

go_library(
    name = "go_default_library",
    srcs = [
        "builder.go",
        "doc.go",
        "helper.go",
        "interfaces.go",
        "mapper.go",
        "result.go",
        "selector.go",
        "visitor.go",
    ],
    tags = ["automanaged"],
)

go_test(
    name = "go_default_test",
    srcs = [
        "builder_test.go",
        "helper_test.go",
        "visitor_test.go",
    ],
    data = [
        "//examples:config",
        "//test/fixtures",
    ],
    library = "go_default_library",
    tags = [
        "automanaged",
        "skip",
    ],
    deps = [],
)
