package(default_visibility = ["//visibility:public"])

licenses(["notice"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_library",
    "go_test",
)

go_library(
    name = "go_default_library",
    srcs = [
        "builder.go",
        "doc.go",
        "helper.go",
        "interfaces.go",
        "mapper.go",
        "result.go",
        "selector.go",
        "visitor.go",
    ],
    tags = ["automanaged"],
    deps = [
        "//pkg/api/validation:go_default_library",
        "//vendor:k8s.io/apimachinery/pkg/apis/meta/v1",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "builder_test.go",
        "helper_test.go",
        "visitor_test.go",
    ],
    data = [
        "//examples:config",
        "//test/fixtures",
    ],
    library = ":go_default_library",
    tags = [
        "automanaged",
    ],
    deps = [
        "//pkg/api/testapi:go_default_library",
        "//pkg/api/testing:go_default_library",
        "//vendor:k8s.io/apimachinery/pkg/apis/meta/v1",
    ],
)

filegroup(
    name = "package-srcs",
    srcs = glob(["**"]),
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)

filegroup(
    name = "all-srcs",
    srcs = [":package-srcs"],
    tags = ["automanaged"],
)
