{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/fusiontables": {
          "description": "Manage your Fusion Tables"
        },
        "https://www.googleapis.com/auth/fusiontables.readonly": {
          "description": "View your Fusion Tables"
        }
      }
    }
  },
  "basePath": "/fusiontables/v1/",
  "baseUrl": "https://www.googleapis.com/fusiontables/v1/",
  "batchPath": "batch/fusiontables/v1",
  "description": "API for working with Fusion Tables data.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/fusiontables",
  "etag": "\"Zkyw9ACJZUvcYmlFaKGChzhmtnE/p0G2jAuETxZYQccv9ZDgRCaOWJQ\"",
  "id": "fusiontables:v1",
  "kind": "discovery#restDescription",
  "name": "fusiontables",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "column": {
      "methods": {
        "delete": {
          "description": "Deletes the column.",
          "httpMethod": "DELETE",
          "id": "fusiontables.column.delete",
          "path": "tables/{tableId}/columns/{columnId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "get": {
          "description": "Retrieves a specific column by its id.",
          "httpMethod": "GET",
          "id": "fusiontables.column.get",
          "path": "tables/{tableId}/columns/{columnId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "insert": {
          "description": "Adds a new column to the table.",
          "httpMethod": "POST",
          "id": "fusiontables.column.insert",
          "path": "tables/{tableId}/columns",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "list": {
          "description": "Retrieves a list of columns.",
          "httpMethod": "GET",
          "id": "fusiontables.column.list",
          "path": "tables/{tableId}/columns",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "patch": {
          "description": "Updates the name or type of an existing column. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "fusiontables.column.patch",
          "path": "tables/{tableId}/columns/{columnId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "update": {
          "description": "Updates the name or type of an existing column.",
          "httpMethod": "PUT",
          "id": "fusiontables.column.update",
          "path": "tables/{tableId}/columns/{columnId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        }
      }
    },
    "query": {
      "methods": {
        "sql": {
          "description": "Executes an SQL SELECT/INSERT/UPDATE/DELETE/SHOW/DESCRIBE/CREATE statement.",
          "httpMethod": "POST",
          "id": "fusiontables.query.sql",
          "path": "query",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": true
        },
        "sqlGet": {
          "description": "Executes an SQL SELECT/SHOW/DESCRIBE statement.",
          "httpMethod": "GET",
          "id": "fusiontables.query.sqlGet",
          "path": "query",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": true
        }
      }
    },
    "style": {
      "methods": {
        "delete": {
          "description": "Deletes a style.",
          "httpMethod": "DELETE",
          "id": "fusiontables.style.delete",
          "path": "tables/{tableId}/styles/{styleId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "get": {
          "description": "Gets a specific style.",
          "httpMethod": "GET",
          "id": "fusiontables.style.get",
          "path": "tables/{tableId}/styles/{styleId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "insert": {
          "description": "Adds a new style for the table.",
          "httpMethod": "POST",
          "id": "fusiontables.style.insert",
          "path": "tables/{tableId}/styles",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "list": {
          "description": "Retrieves a list of styles.",
          "httpMethod": "GET",
          "id": "fusiontables.style.list",
          "path": "tables/{tableId}/styles",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "patch": {
          "description": "Updates an existing style. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "fusiontables.style.patch",
          "path": "tables/{tableId}/styles/{styleId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "update": {
          "description": "Updates an existing style.",
          "httpMethod": "PUT",
          "id": "fusiontables.style.update",
          "path": "tables/{tableId}/styles/{styleId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        }
      }
    },
    "table": {
      "methods": {
        "copy": {
          "description": "Copies a table.",
          "httpMethod": "POST",
          "id": "fusiontables.table.copy",
          "path": "tables/{tableId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "delete": {
          "description": "Deletes a table.",
          "httpMethod": "DELETE",
          "id": "fusiontables.table.delete",
          "path": "tables/{tableId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "get": {
          "description": "Retrieves a specific table by its id.",
          "httpMethod": "GET",
          "id": "fusiontables.table.get",
          "path": "tables/{tableId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "importRows": {
          "description": "Import more rows into a table.",
          "httpMethod": "POST",
          "id": "fusiontables.table.importRows",
          "path": "tables/{tableId}/import",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaUpload": true
        },
        "importTable": {
          "description": "Import a new table.",
          "httpMethod": "POST",
          "id": "fusiontables.table.importTable",
          "path": "tables/import",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaUpload": true
        },
        "insert": {
          "description": "Creates a new table.",
          "httpMethod": "POST",
          "id": "fusiontables.table.insert",
          "path": "tables",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "list": {
          "description": "Retrieves a list of tables a user owns.",
          "httpMethod": "GET",
          "id": "fusiontables.table.list",
          "path": "tables",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "patch": {
          "description": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "fusiontables.table.patch",
          "path": "tables/{tableId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "update": {
          "description": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated.",
          "httpMethod": "PUT",
          "id": "fusiontables.table.update",
          "path": "tables/{tableId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        }
      }
    },
    "task": {
      "methods": {
        "delete": {
          "description": "Deletes the task, unless already started.",
          "httpMethod": "DELETE",
          "id": "fusiontables.task.delete",
          "path": "tables/{tableId}/tasks/{taskId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "get": {
          "description": "Retrieves a specific task by its id.",
          "httpMethod": "GET",
          "id": "fusiontables.task.get",
          "path": "tables/{tableId}/tasks/{taskId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "list": {
          "description": "Retrieves a list of tasks.",
          "httpMethod": "GET",
          "id": "fusiontables.task.list",
          "path": "tables/{tableId}/tasks",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        }
      }
    },
    "template": {
      "methods": {
        "delete": {
          "description": "Deletes a template",
          "httpMethod": "DELETE",
          "id": "fusiontables.template.delete",
          "path": "tables/{tableId}/templates/{templateId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "get": {
          "description": "Retrieves a specific template by its id",
          "httpMethod": "GET",
          "id": "fusiontables.template.get",
          "path": "tables/{tableId}/templates/{templateId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "insert": {
          "description": "Creates a new template for the table.",
          "httpMethod": "POST",
          "id": "fusiontables.template.insert",
          "path": "tables/{tableId}/templates",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "list": {
          "description": "Retrieves a list of templates.",
          "httpMethod": "GET",
          "id": "fusiontables.template.list",
          "path": "tables/{tableId}/templates",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ]
        },
        "patch": {
          "description": "Updates an existing template. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "fusiontables.template.patch",
          "path": "tables/{tableId}/templates/{templateId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        },
        "update": {
          "description": "Updates an existing template",
          "httpMethod": "PUT",
          "id": "fusiontables.template.update",
          "path": "tables/{tableId}/templates/{templateId}",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ]
        }
      }
    }
  },
  "revision": "20171117",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "fusiontables/v1/",
  "title": "Fusion Tables API",
  "version": "v1"
}