{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/ewiu4-KDgktNGSp-rUGcHtmrieI\"",
 "discoveryVersion": "v1",
 "id": "genomics:v1",
 "name": "genomics",
 "version": "v1",
 "revision": "20151219",
 "title": "Genomics API",
 "description": "An API to store, process, explore, and share genomic data. It supports reference-based alignements, genetic variants, and reference genomes. This API provides an implementation of the Global Alliance for Genomics and Health (GA4GH) v0.5.1 API as well as several extensions.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "",
 "protocol": "rest",
 "baseUrl": "https://genomics.googleapis.com/",
 "basePath": "/",
 "rootUrl": "https://genomics.googleapis.com/",
 "servicePath": "",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/bigquery": {
     "description": "View and manage your data in Google BigQuery"
    },
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/devstorage.read_write": {
     "description": "Manage your data in Google Cloud Storage"
    },
    "https://www.googleapis.com/auth/genomics": {
     "description": "View and manage Genomics data"
    },
    "https://www.googleapis.com/auth/genomics.readonly": {
     "description": "View Genomics data"
    }
   }
  }
 },
 "resources": {
  "datasets": {
   "methods": {
    "list": {
     "id": "genomics.datasets.list",
     "path": "v1/datasets",
     "httpMethod": "GET",
     "description": "Lists datasets within a project. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "create": {
     "id": "genomics.datasets.create",
     "path": "v1/datasets",
     "httpMethod": "POST",
     "description": "Creates a new dataset. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.datasets.get",
     "path": "v1/datasets/{datasetId}",
     "httpMethod": "GET",
     "description": "Gets a dataset by ID. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.datasets.patch",
     "path": "v1/datasets/{datasetId}",
     "httpMethod": "PATCH",
     "description": "Updates a dataset. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.datasets.delete",
     "path": "v1/datasets/{datasetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a dataset. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "undelete": {
     "id": "genomics.datasets.undelete",
     "path": "v1/datasets/{datasetId}:undelete",
     "httpMethod": "POST",
     "description": "Undeletes a dataset by restoring a dataset which was deleted via this API. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) This operation is only possible for a week after the deletion occurred.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "setIamPolicy": {
     "id": "genomics.datasets.setIamPolicy",
     "path": "v1/{+resource}:setIamPolicy",
     "httpMethod": "POST",
     "description": "Sets the access control policy on the specified dataset. Replaces any existing policy. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) See Setting a Policy for more information.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "getIamPolicy": {
     "id": "genomics.datasets.getIamPolicy",
     "path": "v1/{+resource}:getIamPolicy",
     "httpMethod": "POST",
     "description": "Gets the access control policy for the dataset. This is empty if the policy or resource does not exist. See Getting a Policy for more information. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "testIamPermissions": {
     "id": "genomics.datasets.testIamPermissions",
     "path": "v1/{+resource}:testIamPermissions",
     "httpMethod": "POST",
     "description": "Returns permissions that a caller has on the specified resource. See Testing Permissions for more information. For the definitions of datasets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "operations": {
   "methods": {
    "get": {
     "id": "genomics.operations.get",
     "path": "v1/{+name}",
     "httpMethod": "GET",
     "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "list": {
     "id": "genomics.operations.list",
     "path": "v1/{+name}",
     "httpMethod": "GET",
     "description": "Lists operations that match the specified filter in the request.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "cancel": {
     "id": "genomics.operations.cancel",
     "path": "v1/{+name}:cancel",
     "httpMethod": "POST",
     "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. Clients may use Operations.GetOperation or Operations.ListOperations to check whether the cancellation succeeded or the operation completed despite cancellation.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "readgroupsets": {
   "methods": {
    "import": {
     "id": "genomics.readgroupsets.import",
     "path": "v1/readgroupsets:import",
     "httpMethod": "POST",
     "description": "Creates read group sets by asynchronously importing the provided information. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) The caller must have WRITE permissions to the dataset. ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import - Tags will be converted to strings - tag types are not preserved - Comments (`@CO`) in the input f[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "export": {
     "id": "genomics.readgroupsets.export",
     "path": "v1/readgroupsets/{readGroupSetId}:export",
     "httpMethod": "POST",
     "description": "Exports a read group set to a BAM file in Google Cloud Storage. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Note that currently there may be some differences between exported BAM files and the original BAM file at the time of import. See [ImportReadGroupSets](google.genomics.v1.ReadServiceV1.ImportReadGroupSets) for caveats.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.readgroupsets.search",
     "path": "v1/readgroupsets/search",
     "httpMethod": "POST",
     "description": "Searches for read group sets matching the criteria. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.readgroupsets.patch",
     "path": "v1/readgroupsets/{readGroupSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a read group set. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.readgroupsets.delete",
     "path": "v1/readgroupsets/{readGroupSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a read group set. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.readgroupsets.get",
     "path": "v1/readgroupsets/{readGroupSetId}",
     "httpMethod": "GET",
     "description": "Gets a read group set by ID. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   },
   "resources": {
    "coveragebuckets": {
     "methods": {
      "list": {
       "id": "genomics.readgroupsets.coveragebuckets.list",
       "path": "v1/readgroupsets/{readGroupSetId}/coveragebuckets",
       "httpMethod": "GET",
       "description": "Lists fixed width coverage buckets for a read group set, each of which correspond to a range of a reference sequence. Each bucket summarizes coverage information across its corresponding genomic range. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Coverage is defined as the number of reads which are aligned to a given base in the reference sequenc[...]",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/genomics",
        "https://www.googleapis.com/auth/genomics.readonly"
       ]
      }
     }
    }
   }
  },
  "reads": {
   "methods": {
    "search": {
     "id": "genomics.reads.search",
     "path": "v1/reads/search",
     "httpMethod": "POST",
     "description": "Gets a list of reads for one or more read group sets. For the definitions of read group sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Reads search operates over a genomic coordinate space of reference sequence & position defined over the reference sequences to which the requested read group sets are aligned. If a target positional range is specified, search returns all reads whose a[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "stream": {
     "id": "genomics.reads.stream",
     "path": "v1/reads:stream",
     "httpMethod": "POST",
     "description": "Returns a stream of all the reads matching the search request, ordered by reference name, position, and ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "referencesets": {
   "methods": {
    "search": {
     "id": "genomics.referencesets.search",
     "path": "v1/referencesets/search",
     "httpMethod": "POST",
     "description": "Searches for reference sets which match the given criteria. For the definitions of references and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.searchReferenceSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L71)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "get": {
     "id": "genomics.referencesets.get",
     "path": "v1/referencesets/{referenceSetId}",
     "httpMethod": "GET",
     "description": "Gets a reference set. For the definitions of references and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.getReferenceSet](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L83).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  },
  "references": {
   "methods": {
    "search": {
     "id": "genomics.references.search",
     "path": "v1/references/search",
     "httpMethod": "POST",
     "description": "Searches for references which match the given criteria. For the definitions of references and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.searchReferences](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L146).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "get": {
     "id": "genomics.references.get",
     "path": "v1/references/{referenceId}",
     "httpMethod": "GET",
     "description": "Gets a reference. For the definitions of references and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.getReference](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L158).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   },
   "resources": {
    "bases": {
     "methods": {
      "list": {
       "id": "genomics.references.bases.list",
       "path": "v1/references/{referenceId}/bases",
       "httpMethod": "GET",
       "description": "Lists the bases in a reference, optionally restricted to a range. For the definitions of references and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.getReferenceBases](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L221).",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/genomics",
        "https://www.googleapis.com/auth/genomics.readonly"
       ]
      }
     }
    }
   }
  },
  "variants": {
   "methods": {
    "import": {
     "id": "genomics.variants.import",
     "path": "v1/variants:import",
     "httpMethod": "POST",
     "description": "Creates variant data by asynchronously importing the provided information. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) The variants for import will be merged with any existing variant that matches its reference sequence, start, end, reference bases, and alternative bases. If no such variant exists, a new one will be created. When variants are merged,[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.variants.search",
     "path": "v1/variants/search",
     "httpMethod": "POST",
     "description": "Gets a list of variants matching the criteria. For the definitions of variants and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.searchVariants](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L126).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "create": {
     "id": "genomics.variants.create",
     "path": "v1/variants",
     "httpMethod": "POST",
     "description": "Creates a new variant. For the definitions of variants and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.variants.patch",
     "path": "v1/variants/{variantId}",
     "httpMethod": "PATCH",
     "description": "Updates a variant. For the definitions of variants and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) This method supports patch semantics. Returns the modified variant without its calls.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.variants.delete",
     "path": "v1/variants/{variantId}",
     "httpMethod": "DELETE",
     "description": "Deletes a variant. For the definitions of variants and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.variants.get",
     "path": "v1/variants/{variantId}",
     "httpMethod": "GET",
     "description": "Gets a variant by ID. For the definitions of variants and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "stream": {
     "id": "genomics.variants.stream",
     "path": "v1/variants:stream",
     "httpMethod": "POST",
     "description": "Returns a stream of all the variants matching the search request, ordered by reference name, position, and ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "variantsets": {
   "methods": {
    "create": {
     "id": "genomics.variantsets.create",
     "path": "v1/variantsets",
     "httpMethod": "POST",
     "description": "Creates a new variant set. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) The provided variant set must have a valid `datasetId` set - all other fields are optional. Note that the `id` field will be ignored, as this is assigned by the server.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "export": {
     "id": "genomics.variantsets.export",
     "path": "v1/variantsets/{variantSetId}:export",
     "httpMethod": "POST",
     "description": "Exports variant set data to an external destination. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/bigquery",
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.variantsets.get",
     "path": "v1/variantsets/{variantSetId}",
     "httpMethod": "GET",
     "description": "Gets a variant set by ID. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "search": {
     "id": "genomics.variantsets.search",
     "path": "v1/variantsets/search",
     "httpMethod": "POST",
     "description": "Returns a list of all variant sets matching search criteria. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.searchVariantSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L49).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "delete": {
     "id": "genomics.variantsets.delete",
     "path": "v1/variantsets/{variantSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes the contents of a variant set. The variant set object is not deleted. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.variantsets.patch",
     "path": "v1/variantsets/{variantSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a variant set using patch semantics. For the definitions of variant sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "callsets": {
   "methods": {
    "search": {
     "id": "genomics.callsets.search",
     "path": "v1/callsets/search",
     "httpMethod": "POST",
     "description": "Gets a list of call sets matching the criteria. For the definitions of call sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) Implements [GlobalAllianceApi.searchCallSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L178).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "create": {
     "id": "genomics.callsets.create",
     "path": "v1/callsets",
     "httpMethod": "POST",
     "description": "Creates a new call set. For the definitions of call sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.callsets.patch",
     "path": "v1/callsets/{callSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a call set. For the definitions of call sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics) This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.callsets.delete",
     "path": "v1/callsets/{callSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a call set. For the definitions of call sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.callsets.get",
     "path": "v1/callsets/{callSetId}",
     "httpMethod": "GET",
     "description": "Gets a call set by ID. For the definitions of call sets and other genomics resources, see [Fundamentals of Google Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  }
 }
}
