{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/presentations": {
          "description": "View and manage your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/presentations.readonly": {
          "description": "View your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://slides.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Slides",
  "description": "Reads and writes Google Slides presentations.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/slides/",
  "fullyEncodeReservedExpansion": true,
  "id": "slides:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://slides.mtls.googleapis.com/",
  "name": "slides",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "presentations": {
      "methods": {
        "batchUpdate": {
          "description": "Applies one or more updates to the presentation.\n\nEach request is validated before\nbeing applied. If any request is not valid, then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how they are applied. Other requests do\nnot need to return information; these each return an empty reply.\nThe order of replies matches that of the requests.\n\nFor example, suppose you call batchUpdate with four [...]",
          "flatPath": "v1/presentations/{presentationId}:batchUpdate",
          "httpMethod": "POST",
          "id": "slides.presentations.batchUpdate",
          "path": "v1/presentations/{presentationId}:batchUpdate",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ]
        },
        "create": {
          "description": "Creates a blank presentation using the title given in the request. If a\n`presentationId` is provided, it is used as the ID of the new presentation.\nOtherwise, a new ID is generated. Other fields in the request, including\nany provided content, are ignored.\nReturns the created presentation.",
          "flatPath": "v1/presentations",
          "httpMethod": "POST",
          "id": "slides.presentations.create",
          "path": "v1/presentations",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/presentations"
          ]
        },
        "get": {
          "description": "Gets the latest version of the specified presentation.",
          "flatPath": "v1/presentations/{presentationsId}",
          "httpMethod": "GET",
          "id": "slides.presentations.get",
          "path": "v1/presentations/{+presentationId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/presentations.readonly"
          ]
        }
      },
      "resources": {
        "pages": {
          "methods": {
            "get": {
              "description": "Gets the latest version of the specified page in the presentation.",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "httpMethod": "GET",
              "id": "slides.presentations.pages.get",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ]
            },
            "getThumbnail": {
              "description": "Generates a thumbnail of the latest version of the specified page in the\npresentation and returns a URL to the thumbnail image.\n\nThis request counts as an [expensive read request](/slides/limits) for\nquota purposes.",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "httpMethod": "GET",
              "id": "slides.presentations.pages.getThumbnail",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20200214",
  "rootUrl": "https://slides.googleapis.com/",
  "servicePath": "",
  "title": "Google Slides API",
  "version": "v1",
  "version_module": true
}