# These packages get included in the set of packages tested by "make test"
# when no explicit WHAT target is specified.
#
# Which packages to include here is a bit subjective:
# - Should be "important". In particular, it should
#   be compiled into one of our production binaries (use
#   `go mod why $package` without the vendor prefix) or
#   be used regularly.
# - Should be at risk of breaking because we compile them
#   differently than upstream (different Go version, different
#   dependencies).
# - Must support being tested outside of their normal source tree.
# - Must be reasonably fast.

# Compiled differently (Go version, dependencies) than in the upstream
# repo, therefore worth testing locally.
hack/tools/golangci-lint/sigs.k8s.io/logtools/...

# This is just one package which is known to work.
# The goal is to run more.
vendor/go.etcd.io/etcd/client/pkg/v3/fileutil
