# These directories were opted into strict Go API change tracking.
# They have a CHANGELOG.md file where breaking Go API changes get documented.
# Adding such documentation manually or with hack/update-go-apidocs.sh will make
# hack/verify-go-apidocs.sh pass without an error.

staging/src/k8s.io/client-go

# TODO: re-enable apimachinery once we have more experience with this feature.
# staging/src/k8s.io/apimachinery
