{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "basePath": "/games/v1/",
  "baseUrl": "https://www.googleapis.com/games/v1/",
  "batchPath": "batch/games/v1",
  "canonicalName": "Games",
  "description": "The API for Google Play Game Services.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/games/services/",
  "etag": "\"F5McR9eEaw0XRpaO3M9gbIugkbs/S1XdsaA4QL0oNYNbtJtRXPuoeKA\"",
  "id": "games:v1",
  "kind": "discovery#restDescription",
  "name": "games",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "achievementDefinitions": {
      "methods": {
        "list": {
          "description": "Lists all the achievement definitions for your application.",
          "httpMethod": "GET",
          "id": "games.achievementDefinitions.list",
          "path": "achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "achievements": {
      "methods": {
        "increment": {
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.increment",
          "path": "achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "httpMethod": "GET",
          "id": "games.achievements.list",
          "path": "players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "reveal": {
          "description": "Sets the state of the achievement with the given ID to REVEALED for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.reveal",
          "path": "achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "setStepsAtLeast": {
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "httpMethod": "POST",
          "id": "games.achievements.setStepsAtLeast",
          "path": "achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.unlock",
          "path": "achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "updateMultiple": {
          "description": "Updates multiple achievements for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.updateMultiple",
          "path": "achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "applications": {
      "methods": {
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified platformType, the returned response will not include any instance data.",
          "httpMethod": "GET",
          "id": "games.applications.get",
          "path": "applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "played": {
          "description": "Indicate that the the currently authenticated user is playing your application.",
          "httpMethod": "POST",
          "id": "games.applications.played",
          "path": "applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "verify": {
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "id": "games.applications.verify",
          "path": "applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "events": {
      "methods": {
        "listByPlayer": {
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "id": "games.events.listByPlayer",
          "path": "events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listDefinitions": {
          "description": "Returns a list of the event definitions in this application.",
          "httpMethod": "GET",
          "id": "games.events.listDefinitions",
          "path": "eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "record": {
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "httpMethod": "POST",
          "id": "games.events.record",
          "path": "events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "httpMethod": "GET",
          "id": "games.leaderboards.get",
          "path": "leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET",
          "id": "games.leaderboards.list",
          "path": "leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "description": "Return the metagame configuration data for the calling application.",
          "httpMethod": "GET",
          "id": "games.metagame.getMetagameConfig",
          "path": "metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listCategoriesByPlayer": {
          "description": "List play data aggregated per category for the player corresponding to playerId.",
          "httpMethod": "GET",
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set playerId to me.",
          "httpMethod": "GET",
          "id": "games.players.get",
          "path": "players/{playerId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Get the collection of players for the currently authenticated user.",
          "httpMethod": "GET",
          "id": "games.players.list",
          "path": "players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "pushtokens": {
      "methods": {
        "remove": {
          "description": "Removes a push token for the current user and application. Removing a non-existent push token will report success.",
          "httpMethod": "POST",
          "id": "games.pushtokens.remove",
          "path": "pushtokens/remove",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "update": {
          "description": "Registers a push token for the current user and application.",
          "httpMethod": "PUT",
          "id": "games.pushtokens.update",
          "path": "pushtokens",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "description": "Checks whether the games client is out of date.",
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "path": "revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "rooms": {
      "methods": {
        "create": {
          "description": "Create a room. For internal use by the Games SDK only. Calling this method directly is unsupported.",
          "httpMethod": "POST",
          "id": "games.rooms.create",
          "path": "rooms/create",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "decline": {
          "description": "Decline an invitation to join a room. For internal use by the Games SDK only. Calling this method directly is unsupported.",
          "httpMethod": "POST",
          "id": "games.rooms.decline",
          "path": "rooms/{roomId}/decline",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "dismiss": {
          "description": "Dismiss an invitation to join a room. For internal use by the Games SDK only. Calling this method directly is unsupported.",
          "httpMethod": "POST",
          "id": "games.rooms.dismiss",
          "path": "rooms/{roomId}/dismiss",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "description": "Get the data for a room.",
          "httpMethod": "GET",
          "id": "games.rooms.get",
          "path": "rooms/{roomId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "join": {
          "description": "Join a room. For internal use by the Games SDK only. Calling this method directly is unsupported.",
          "httpMethod": "POST",
          "id": "games.rooms.join",
          "path": "rooms/{roomId}/join",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "leave": {
          "description": "Leave a room. For internal use by the Games SDK only. Calling this method directly is unsupported.",
          "httpMethod": "POST",
          "id": "games.rooms.leave",
          "path": "rooms/{roomId}/leave",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Returns invitations to join rooms.",
          "httpMethod": "GET",
          "id": "games.rooms.list",
          "path": "rooms",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "reportStatus": {
          "description": "Updates sent by a client reporting the status of peers in a room. For internal use by the Games SDK only. Calling this method directly is unsupported.",
          "httpMethod": "POST",
          "id": "games.rooms.reportStatus",
          "path": "rooms/{roomId}/reportstatus",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, leaderboardId can be set to ALL to retrieve data for all leaderboards in a given time span.\nNOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "httpMethod": "GET",
          "id": "games.scores.get",
          "path": "players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "httpMethod": "GET",
          "id": "games.scores.list",
          "path": "leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listWindow": {
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "httpMethod": "GET",
          "id": "games.scores.listWindow",
          "path": "leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submit": {
          "description": "Submits a score to the specified leaderboard.",
          "httpMethod": "POST",
          "id": "games.scores.submit",
          "path": "leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submitMultiple": {
          "description": "Submits multiple scores to leaderboards.",
          "httpMethod": "POST",
          "id": "games.scores.submitMultiple",
          "path": "leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "description": "Retrieves the metadata for a given snapshot ID.",
          "httpMethod": "GET",
          "id": "games.snapshots.get",
          "path": "snapshots/{snapshotId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "httpMethod": "GET",
          "id": "games.snapshots.list",
          "path": "players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "turnBasedMatches": {
      "methods": {
        "cancel": {
          "description": "Cancel a turn-based match.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.cancel",
          "path": "turnbasedmatches/{matchId}/cancel",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "create": {
          "description": "Create a turn-based match.",
          "httpMethod": "POST",
          "id": "games.turnBasedMatches.create",
          "path": "turnbasedmatches/create",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "decline": {
          "description": "Decline an invitation to play a turn-based match.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.decline",
          "path": "turnbasedmatches/{matchId}/decline",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "dismiss": {
          "description": "Dismiss a turn-based match from the match list. The match will no longer show up in the list and will not generate notifications.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.dismiss",
          "path": "turnbasedmatches/{matchId}/dismiss",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "finish": {
          "description": "Finish a turn-based match. Each player should make this call once, after all results are in. Only the player whose turn it is may make the first call to Finish, and can pass in the final match state.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.finish",
          "path": "turnbasedmatches/{matchId}/finish",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "description": "Get the data for a turn-based match.",
          "httpMethod": "GET",
          "id": "games.turnBasedMatches.get",
          "path": "turnbasedmatches/{matchId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "join": {
          "description": "Join a turn-based match.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.join",
          "path": "turnbasedmatches/{matchId}/join",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "leave": {
          "description": "Leave a turn-based match when it is not the current player's turn, without canceling the match.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.leave",
          "path": "turnbasedmatches/{matchId}/leave",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "leaveTurn": {
          "description": "Leave a turn-based match during the current player's turn, without canceling the match.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.leaveTurn",
          "path": "turnbasedmatches/{matchId}/leaveTurn",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "description": "Returns turn-based matches the player is or was involved in.",
          "httpMethod": "GET",
          "id": "games.turnBasedMatches.list",
          "path": "turnbasedmatches",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "rematch": {
          "description": "Create a rematch of a match that was previously completed, with the same participants. This can be called by only one player on a match still in their list; the player must have called Finish first. Returns the newly created match; it will be the caller's turn.",
          "httpMethod": "POST",
          "id": "games.turnBasedMatches.rematch",
          "path": "turnbasedmatches/{matchId}/rematch",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "sync": {
          "description": "Returns turn-based matches the player is or was involved in that changed since the last sync call, with the least recent changes coming first. Matches that should be removed from the local cache will have a status of MATCH_DELETED.",
          "httpMethod": "GET",
          "id": "games.turnBasedMatches.sync",
          "path": "turnbasedmatches/sync",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "takeTurn": {
          "description": "Commit the results of a player turn.",
          "httpMethod": "PUT",
          "id": "games.turnBasedMatches.takeTurn",
          "path": "turnbasedmatches/{matchId}/turn",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    }
  },
  "revision": "20191017",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "games/v1/",
  "title": "Google Play Game Services API",
  "version": "v1"
}