{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/xRQmfo4WYHt7ESOziu0ToVNCLZc\"",
 "discoveryVersion": "v1",
 "id": "mapsengine:v1",
 "name": "mapsengine",
 "canonicalName": "Maps Engine",
 "version": "v1",
 "revision": "20150120",
 "title": "Google Maps Engine API",
 "description": "The Google Maps Engine API allows developers to store and query geospatial vector and raster data.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/maps-engine/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/mapsengine/v1/",
 "basePath": "/mapsengine/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "mapsengine/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/mapsengine": {
     "description": "View and manage your Google My Maps data"
    },
    "https://www.googleapis.com/auth/mapsengine.readonly": {
     "description": "View your Google My Maps data"
    }
   }
  }
 },
 "resources": {
  "assets": {
   "methods": {
    "get": {
     "id": "mapsengine.assets.get",
     "path": "assets/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.assets.list",
     "path": "assets",
     "httpMethod": "GET",
     "description": "Return all assets readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    }
   },
   "resources": {
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.assets.parents.list",
       "path": "assets/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "permissions": {
     "methods": {
      "list": {
       "id": "mapsengine.assets.permissions.list",
       "path": "assets/{id}/permissions",
       "httpMethod": "GET",
       "description": "Return all of the permissions for the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "layers": {
   "methods": {
    "cancelProcessing": {
     "id": "mapsengine.layers.cancelProcessing",
     "path": "layers/{id}/cancelProcessing",
     "httpMethod": "POST",
     "description": "Cancel processing on a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "create": {
     "id": "mapsengine.layers.create",
     "path": "layers",
     "httpMethod": "POST",
     "description": "Create a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "delete": {
     "id": "mapsengine.layers.delete",
     "path": "layers/{id}",
     "httpMethod": "DELETE",
     "description": "Delete a layer.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.layers.get",
     "path": "layers/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular layer.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "getPublished": {
     "id": "mapsengine.layers.getPublished",
     "path": "layers/{id}/published",
     "httpMethod": "GET",
     "description": "Return the published metadata for a particular layer.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.layers.list",
     "path": "layers",
     "httpMethod": "GET",
     "description": "Return all layers readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "listPublished": {
     "id": "mapsengine.layers.listPublished",
     "path": "layers/published",
     "httpMethod": "GET",
     "description": "Return all published layers readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "patch": {
     "id": "mapsengine.layers.patch",
     "path": "layers/{id}",
     "httpMethod": "PATCH",
     "description": "Mutate a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "process": {
     "id": "mapsengine.layers.process",
     "path": "layers/{id}/process",
     "httpMethod": "POST",
     "description": "Process a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "publish": {
     "id": "mapsengine.layers.publish",
     "path": "layers/{id}/publish",
     "httpMethod": "POST",
     "description": "Publish a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "unpublish": {
     "id": "mapsengine.layers.unpublish",
     "path": "layers/{id}/unpublish",
     "httpMethod": "POST",
     "description": "Unpublish a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.layers.parents.list",
       "path": "layers/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified layer.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "permissions": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.layers.permissions.batchDelete",
       "path": "layers/{id}/permissions/batchDelete",
       "httpMethod": "POST",
       "description": "Remove permission entries from an already existing asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchUpdate": {
       "id": "mapsengine.layers.permissions.batchUpdate",
       "path": "layers/{id}/permissions/batchUpdate",
       "httpMethod": "POST",
       "description": "Add or update permission entries to an already existing asset.\n\nAn asset can hold up to 20 different permission entries. Each batchInsert request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "list": {
       "id": "mapsengine.layers.permissions.list",
       "path": "layers/{id}/permissions",
       "httpMethod": "GET",
       "description": "Return all of the permissions for the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "maps": {
   "methods": {
    "create": {
     "id": "mapsengine.maps.create",
     "path": "maps",
     "httpMethod": "POST",
     "description": "Create a map asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "delete": {
     "id": "mapsengine.maps.delete",
     "path": "maps/{id}",
     "httpMethod": "DELETE",
     "description": "Delete a map.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.maps.get",
     "path": "maps/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular map.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "getPublished": {
     "id": "mapsengine.maps.getPublished",
     "path": "maps/{id}/published",
     "httpMethod": "GET",
     "description": "Return the published metadata for a particular map.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.maps.list",
     "path": "maps",
     "httpMethod": "GET",
     "description": "Return all maps readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "listPublished": {
     "id": "mapsengine.maps.listPublished",
     "path": "maps/published",
     "httpMethod": "GET",
     "description": "Return all published maps readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "patch": {
     "id": "mapsengine.maps.patch",
     "path": "maps/{id}",
     "httpMethod": "PATCH",
     "description": "Mutate a map asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "publish": {
     "id": "mapsengine.maps.publish",
     "path": "maps/{id}/publish",
     "httpMethod": "POST",
     "description": "Publish a map asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "unpublish": {
     "id": "mapsengine.maps.unpublish",
     "path": "maps/{id}/unpublish",
     "httpMethod": "POST",
     "description": "Unpublish a map asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "permissions": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.maps.permissions.batchDelete",
       "path": "maps/{id}/permissions/batchDelete",
       "httpMethod": "POST",
       "description": "Remove permission entries from an already existing asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchUpdate": {
       "id": "mapsengine.maps.permissions.batchUpdate",
       "path": "maps/{id}/permissions/batchUpdate",
       "httpMethod": "POST",
       "description": "Add or update permission entries to an already existing asset.\n\nAn asset can hold up to 20 different permission entries. Each batchInsert request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "list": {
       "id": "mapsengine.maps.permissions.list",
       "path": "maps/{id}/permissions",
       "httpMethod": "GET",
       "description": "Return all of the permissions for the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "projects": {
   "methods": {
    "list": {
     "id": "mapsengine.projects.list",
     "path": "projects",
     "httpMethod": "GET",
     "description": "Return all projects readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    }
   },
   "resources": {
    "icons": {
     "methods": {
      "create": {
       "id": "mapsengine.projects.icons.create",
       "path": "projects/{projectId}/icons",
       "httpMethod": "POST",
       "description": "Create an icon.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ],
       "supportsMediaUpload": true
      },
      "get": {
       "id": "mapsengine.projects.icons.get",
       "path": "projects/{projectId}/icons/{id}",
       "httpMethod": "GET",
       "description": "Return an icon or its associated metadata",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ],
       "supportsMediaDownload": true
      },
      "list": {
       "id": "mapsengine.projects.icons.list",
       "path": "projects/{projectId}/icons",
       "httpMethod": "GET",
       "description": "Return all icons in the current project",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "rasterCollections": {
   "methods": {
    "cancelProcessing": {
     "id": "mapsengine.rasterCollections.cancelProcessing",
     "path": "rasterCollections/{id}/cancelProcessing",
     "httpMethod": "POST",
     "description": "Cancel processing on a raster collection asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "create": {
     "id": "mapsengine.rasterCollections.create",
     "path": "rasterCollections",
     "httpMethod": "POST",
     "description": "Create a raster collection asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "delete": {
     "id": "mapsengine.rasterCollections.delete",
     "path": "rasterCollections/{id}",
     "httpMethod": "DELETE",
     "description": "Delete a raster collection.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.rasterCollections.get",
     "path": "rasterCollections/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular raster collection.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.rasterCollections.list",
     "path": "rasterCollections",
     "httpMethod": "GET",
     "description": "Return all raster collections readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "patch": {
     "id": "mapsengine.rasterCollections.patch",
     "path": "rasterCollections/{id}",
     "httpMethod": "PATCH",
     "description": "Mutate a raster collection asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "process": {
     "id": "mapsengine.rasterCollections.process",
     "path": "rasterCollections/{id}/process",
     "httpMethod": "POST",
     "description": "Process a raster collection asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.rasterCollections.parents.list",
       "path": "rasterCollections/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified raster collection.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "permissions": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.rasterCollections.permissions.batchDelete",
       "path": "rasterCollections/{id}/permissions/batchDelete",
       "httpMethod": "POST",
       "description": "Remove permission entries from an already existing asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchUpdate": {
       "id": "mapsengine.rasterCollections.permissions.batchUpdate",
       "path": "rasterCollections/{id}/permissions/batchUpdate",
       "httpMethod": "POST",
       "description": "Add or update permission entries to an already existing asset.\n\nAn asset can hold up to 20 different permission entries. Each batchInsert request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "list": {
       "id": "mapsengine.rasterCollections.permissions.list",
       "path": "rasterCollections/{id}/permissions",
       "httpMethod": "GET",
       "description": "Return all of the permissions for the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "rasters": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.rasterCollections.rasters.batchDelete",
       "path": "rasterCollections/{id}/rasters/batchDelete",
       "httpMethod": "POST",
       "description": "Remove rasters from an existing raster collection.\n\nUp to 50 rasters can be included in a single batchDelete request. Each batchDelete request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchInsert": {
       "id": "mapsengine.rasterCollections.rasters.batchInsert",
       "path": "rasterCollections/{id}/rasters/batchInsert",
       "httpMethod": "POST",
       "description": "Add rasters to an existing raster collection. Rasters must be successfully processed in order to be added to a raster collection.\n\nUp to 50 rasters can be included in a single batchInsert request. Each batchInsert request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "list": {
       "id": "mapsengine.rasterCollections.rasters.list",
       "path": "rasterCollections/{id}/rasters",
       "httpMethod": "GET",
       "description": "Return all rasters within a raster collection.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "rasters": {
   "methods": {
    "delete": {
     "id": "mapsengine.rasters.delete",
     "path": "rasters/{id}",
     "httpMethod": "DELETE",
     "description": "Delete a raster.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.rasters.get",
     "path": "rasters/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a single raster.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.rasters.list",
     "path": "rasters",
     "httpMethod": "GET",
     "description": "Return all rasters readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "patch": {
     "id": "mapsengine.rasters.patch",
     "path": "rasters/{id}",
     "httpMethod": "PATCH",
     "description": "Mutate a raster asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "process": {
     "id": "mapsengine.rasters.process",
     "path": "rasters/{id}/process",
     "httpMethod": "POST",
     "description": "Process a raster asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "upload": {
     "id": "mapsengine.rasters.upload",
     "path": "rasters/upload",
     "httpMethod": "POST",
     "description": "Create a skeleton raster asset for upload.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "files": {
     "methods": {
      "insert": {
       "id": "mapsengine.rasters.files.insert",
       "path": "rasters/{id}/files",
       "httpMethod": "POST",
       "description": "Upload a file to a raster asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.rasters.parents.list",
       "path": "rasters/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified rasters.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "permissions": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.rasters.permissions.batchDelete",
       "path": "rasters/{id}/permissions/batchDelete",
       "httpMethod": "POST",
       "description": "Remove permission entries from an already existing asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchUpdate": {
       "id": "mapsengine.rasters.permissions.batchUpdate",
       "path": "rasters/{id}/permissions/batchUpdate",
       "httpMethod": "POST",
       "description": "Add or update permission entries to an already existing asset.\n\nAn asset can hold up to 20 different permission entries. Each batchInsert request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "list": {
       "id": "mapsengine.rasters.permissions.list",
       "path": "rasters/{id}/permissions",
       "httpMethod": "GET",
       "description": "Return all of the permissions for the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "tables": {
   "methods": {
    "create": {
     "id": "mapsengine.tables.create",
     "path": "tables",
     "httpMethod": "POST",
     "description": "Create a table asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "delete": {
     "id": "mapsengine.tables.delete",
     "path": "tables/{id}",
     "httpMethod": "DELETE",
     "description": "Delete a table.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.tables.get",
     "path": "tables/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular table, including the schema.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.tables.list",
     "path": "tables",
     "httpMethod": "GET",
     "description": "Return all tables readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "patch": {
     "id": "mapsengine.tables.patch",
     "path": "tables/{id}",
     "httpMethod": "PATCH",
     "description": "Mutate a table asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "process": {
     "id": "mapsengine.tables.process",
     "path": "tables/{id}/process",
     "httpMethod": "POST",
     "description": "Process a table asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "upload": {
     "id": "mapsengine.tables.upload",
     "path": "tables/upload",
     "httpMethod": "POST",
     "description": "Create a placeholder table asset to which table files can be uploaded.\nOnce the placeholder has been created, files are uploaded to the https://www.googleapis.com/upload/mapsengine/v1/tables/table_id/files endpoint.\nSee Table Upload in the Developer's Guide or Table.files: insert in the reference documentation for more information.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "features": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.tables.features.batchDelete",
       "path": "tables/{id}/features/batchDelete",
       "httpMethod": "POST",
       "description": "Delete all features matching the given IDs.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchInsert": {
       "id": "mapsengine.tables.features.batchInsert",
       "path": "tables/{id}/features/batchInsert",
       "httpMethod": "POST",
       "description": "Append features to an existing table.\n\nA single batchInsert request can create:\n\n- Up to 50 features.\n- A combined total of 10 000 vertices.\nFeature limits are documented in the Supported data formats and limits article of the Google Maps Engine help center. Note that free and paid accounts have different limits.\n\nFor more information about inserting features, read Creating features in the Google Maps Engine developer's guide.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchPatch": {
       "id": "mapsengine.tables.features.batchPatch",
       "path": "tables/{id}/features/batchPatch",
       "httpMethod": "POST",
       "description": "Update the supplied features.\n\nA single batchPatch request can update:\n\n- Up to 50 features.\n- A combined total of 10 000 vertices.\nFeature limits are documented in the Supported data formats and limits article of the Google Maps Engine help center. Note that free and paid accounts have different limits.\n\nFeature updates use HTTP PATCH semantics:\n\n- A supplied value replaces an existing value (if any) in that field.\n- Omitted fields remain unchanged.\n- Complex [...]",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "get": {
       "id": "mapsengine.tables.features.get",
       "path": "tables/{tableId}/features/{id}",
       "httpMethod": "GET",
       "description": "Return a single feature, given its ID.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      },
      "list": {
       "id": "mapsengine.tables.features.list",
       "path": "tables/{id}/features",
       "httpMethod": "GET",
       "description": "Return all features readable by the current user.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "files": {
     "methods": {
      "insert": {
       "id": "mapsengine.tables.files.insert",
       "path": "tables/{id}/files",
       "httpMethod": "POST",
       "description": "Upload a file to a placeholder table asset. See Table Upload in the Developer's Guide for more information.\nSupported file types are listed in the Supported data formats and limits article of the Google Maps Engine help center.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.tables.parents.list",
       "path": "tables/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified table.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "permissions": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.tables.permissions.batchDelete",
       "path": "tables/{id}/permissions/batchDelete",
       "httpMethod": "POST",
       "description": "Remove permission entries from an already existing asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchUpdate": {
       "id": "mapsengine.tables.permissions.batchUpdate",
       "path": "tables/{id}/permissions/batchUpdate",
       "httpMethod": "POST",
       "description": "Add or update permission entries to an already existing asset.\n\nAn asset can hold up to 20 different permission entries. Each batchInsert request is atomic.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "list": {
       "id": "mapsengine.tables.permissions.list",
       "path": "tables/{id}/permissions",
       "httpMethod": "GET",
       "description": "Return all of the permissions for the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
