{
 "kind": "discovery#restDescription",
 "etag": "\"5M1WkxnZyJhziV-cW1kdtwscs8E/cLXdvPSJ73RAjLVWqio6ofbcpRI\"",
 "discoveryVersion": "v1",
 "id": "mirror:v1",
 "name": "mirror",
 "version": "v1",
 "title": "Google Mirror API",
 "description": "API for interacting with Glass users via the timeline.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/glass",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/mirror/v1/",
 "basePath": "/mirror/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "mirror/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/glass.location": {
     "description": "View your location"
    },
    "https://www.googleapis.com/auth/glass.timeline": {
     "description": "View and manage your Glass timeline"
    }
   }
  }
 },
 "resources": {
  "accounts": {
   "methods": {
    "insert": {
     "id": "mirror.accounts.insert",
     "path": "accounts/{userToken}/{accountType}/{accountName}",
     "httpMethod": "POST",
     "description": "Inserts a new account for a user"
    }
   }
  },
  "contacts": {
   "methods": {
    "delete": {
     "id": "mirror.contacts.delete",
     "path": "contacts/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes a contact.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "get": {
     "id": "mirror.contacts.get",
     "path": "contacts/{id}",
     "httpMethod": "GET",
     "description": "Gets a single contact by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "insert": {
     "id": "mirror.contacts.insert",
     "path": "contacts",
     "httpMethod": "POST",
     "description": "Inserts a new contact.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "list": {
     "id": "mirror.contacts.list",
     "path": "contacts",
     "httpMethod": "GET",
     "description": "Retrieves a list of contacts for the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "patch": {
     "id": "mirror.contacts.patch",
     "path": "contacts/{id}",
     "httpMethod": "PATCH",
     "description": "Updates a contact in place. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "update": {
     "id": "mirror.contacts.update",
     "path": "contacts/{id}",
     "httpMethod": "PUT",
     "description": "Updates a contact in place.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    }
   }
  },
  "locations": {
   "methods": {
    "get": {
     "id": "mirror.locations.get",
     "path": "locations/{id}",
     "httpMethod": "GET",
     "description": "Gets a single location by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "list": {
     "id": "mirror.locations.list",
     "path": "locations",
     "httpMethod": "GET",
     "description": "Retrieves a list of locations for the user.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    }
   }
  },
  "subscriptions": {
   "methods": {
    "delete": {
     "id": "mirror.subscriptions.delete",
     "path": "subscriptions/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes a subscription.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "insert": {
     "id": "mirror.subscriptions.insert",
     "path": "subscriptions",
     "httpMethod": "POST",
     "description": "Creates a new subscription.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "list": {
     "id": "mirror.subscriptions.list",
     "path": "subscriptions",
     "httpMethod": "GET",
     "description": "Retrieves a list of subscriptions for the authenticated user and service.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "update": {
     "id": "mirror.subscriptions.update",
     "path": "subscriptions/{id}",
     "httpMethod": "PUT",
     "description": "Updates an existing subscription in place.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    }
   }
  },
  "timeline": {
   "methods": {
    "delete": {
     "id": "mirror.timeline.delete",
     "path": "timeline/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes a timeline item.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "get": {
     "id": "mirror.timeline.get",
     "path": "timeline/{id}",
     "httpMethod": "GET",
     "description": "Gets a single timeline item by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "insert": {
     "id": "mirror.timeline.insert",
     "path": "timeline",
     "httpMethod": "POST",
     "description": "Inserts a new item into the timeline.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaUpload": true
    },
    "list": {
     "id": "mirror.timeline.list",
     "path": "timeline",
     "httpMethod": "GET",
     "description": "Retrieves a list of timeline items for the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "patch": {
     "id": "mirror.timeline.patch",
     "path": "timeline/{id}",
     "httpMethod": "PATCH",
     "description": "Updates a timeline item in place. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ]
    },
    "update": {
     "id": "mirror.timeline.update",
     "path": "timeline/{id}",
     "httpMethod": "PUT",
     "description": "Updates a timeline item in place.",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaUpload": true
    }
   },
   "resources": {
    "attachments": {
     "methods": {
      "delete": {
       "id": "mirror.timeline.attachments.delete",
       "path": "timeline/{itemId}/attachments/{attachmentId}",
       "httpMethod": "DELETE",
       "description": "Deletes an attachment from a timeline item.",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ]
      },
      "get": {
       "id": "mirror.timeline.attachments.get",
       "path": "timeline/{itemId}/attachments/{attachmentId}",
       "httpMethod": "GET",
       "description": "Retrieves an attachment on a timeline item by item ID and attachment ID.",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ],
       "supportsMediaDownload": true
      },
      "insert": {
       "id": "mirror.timeline.attachments.insert",
       "path": "timeline/{itemId}/attachments",
       "httpMethod": "POST",
       "description": "Adds a new attachment to a timeline item.",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ],
       "supportsMediaUpload": true
      },
      "list": {
       "id": "mirror.timeline.attachments.list",
       "path": "timeline/{itemId}/attachments",
       "httpMethod": "GET",
       "description": "Returns a list of attachments for a timeline item.",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ]
      }
     }
    }
   }
  }
 }
}
