{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/xqSX7-n8LugACXqRoz62D83GEuE\"",
 "discoveryVersion": "v1",
 "id": "admin:directory_v1",
 "name": "admin",
 "canonicalName": "directory",
 "version": "directory_v1",
 "title": "Admin Directory API",
 "description": "The Admin SDK Directory API lets you view and manage enterprise resources such as users and groups, administrative notifications, security features, and more.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": "admin",
 "documentationLink": "https://developers.google.com/admin-sdk/directory/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/admin/directory/v1/",
 "basePath": "/admin/directory/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "admin/directory/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/admin.directory.device.chromeos": {
     "description": "View and manage your Chrome OS devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly": {
     "description": "View your Chrome OS devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.device.mobile": {
     "description": "View and manage your mobile devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.device.mobile.action": {
     "description": "Manage your mobile devices by performing administrative tasks"
    },
    "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly": {
     "description": "View your mobile devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.group": {
     "description": "View and manage the provisioning of groups on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group.member": {
     "description": "View and manage group subscriptions on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group.member.readonly": {
     "description": "View group subscriptions on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group.readonly": {
     "description": "View groups on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.notifications": {
     "description": "View and manage notifications received on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.orgunit": {
     "description": "View and manage organization units on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.orgunit.readonly": {
     "description": "View organization units on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user": {
     "description": "View and manage the provisioning of users on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.alias": {
     "description": "View and manage user aliases on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.alias.readonly": {
     "description": "View user aliases on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.readonly": {
     "description": "View users on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.security": {
     "description": "Manage data access permissions for users on your domain"
    }
   }
  }
 },
 "resources": {
  "asps": {
   "methods": {
    "delete": {
     "id": "directory.asps.delete",
     "path": "users/{userKey}/asps/{codeId}",
     "httpMethod": "DELETE",
     "description": "Delete an ASP issued by a user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    },
    "get": {
     "id": "directory.asps.get",
     "path": "users/{userKey}/asps/{codeId}",
     "httpMethod": "GET",
     "description": "Get information about an ASP issued by a user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    },
    "list": {
     "id": "directory.asps.list",
     "path": "users/{userKey}/asps",
     "httpMethod": "GET",
     "description": "List the ASPs issued by a user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    }
   }
  },
  "channels": {
   "methods": {
    "stop": {
     "id": "admin.channels.stop",
     "path": "/admin/directory_v1/channels/stop",
     "httpMethod": "POST",
     "description": "Stop watching resources through this channel",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.alias",
      "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ]
    }
   }
  },
  "chromeosdevices": {
   "methods": {
    "get": {
     "id": "directory.chromeosdevices.get",
     "path": "customer/{customerId}/devices/chromeos/{deviceId}",
     "httpMethod": "GET",
     "description": "Retrieve Chrome OS Device",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos",
      "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
     ]
    },
    "list": {
     "id": "directory.chromeosdevices.list",
     "path": "customer/{customerId}/devices/chromeos",
     "httpMethod": "GET",
     "description": "Retrieve all Chrome OS Devices of a customer (paginated)",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos",
      "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
     ]
    },
    "patch": {
     "id": "directory.chromeosdevices.patch",
     "path": "customer/{customerId}/devices/chromeos/{deviceId}",
     "httpMethod": "PATCH",
     "description": "Update Chrome OS Device. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos"
     ]
    },
    "update": {
     "id": "directory.chromeosdevices.update",
     "path": "customer/{customerId}/devices/chromeos/{deviceId}",
     "httpMethod": "PUT",
     "description": "Update Chrome OS Device",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos"
     ]
    }
   }
  },
  "groups": {
   "methods": {
    "delete": {
     "id": "directory.groups.delete",
     "path": "groups/{groupKey}",
     "httpMethod": "DELETE",
     "description": "Delete Group",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ]
    },
    "get": {
     "id": "directory.groups.get",
     "path": "groups/{groupKey}",
     "httpMethod": "GET",
     "description": "Retrieve Group",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ]
    },
    "insert": {
     "id": "directory.groups.insert",
     "path": "groups",
     "httpMethod": "POST",
     "description": "Create Group",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ]
    },
    "list": {
     "id": "directory.groups.list",
     "path": "groups",
     "httpMethod": "GET",
     "description": "Retrieve all groups in a domain (paginated)",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ]
    },
    "patch": {
     "id": "directory.groups.patch",
     "path": "groups/{groupKey}",
     "httpMethod": "PATCH",
     "description": "Update Group. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ]
    },
    "update": {
     "id": "directory.groups.update",
     "path": "groups/{groupKey}",
     "httpMethod": "PUT",
     "description": "Update Group",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ]
    }
   },
   "resources": {
    "aliases": {
     "methods": {
      "delete": {
       "id": "directory.groups.aliases.delete",
       "path": "groups/{groupKey}/aliases/{alias}",
       "httpMethod": "DELETE",
       "description": "Remove a alias for the group",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.group"
       ]
      },
      "insert": {
       "id": "directory.groups.aliases.insert",
       "path": "groups/{groupKey}/aliases",
       "httpMethod": "POST",
       "description": "Add a alias for the group",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.group"
       ]
      },
      "list": {
       "id": "directory.groups.aliases.list",
       "path": "groups/{groupKey}/aliases",
       "httpMethod": "GET",
       "description": "List all aliases for a group",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.group",
        "https://www.googleapis.com/auth/admin.directory.group.readonly"
       ],
       "supportsSubscription": true
      }
     }
    }
   }
  },
  "members": {
   "methods": {
    "delete": {
     "id": "directory.members.delete",
     "path": "groups/{groupKey}/members/{memberKey}",
     "httpMethod": "DELETE",
     "description": "Remove membership.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ]
    },
    "get": {
     "id": "directory.members.get",
     "path": "groups/{groupKey}/members/{memberKey}",
     "httpMethod": "GET",
     "description": "Retrieve Group Member",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member",
      "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ]
    },
    "insert": {
     "id": "directory.members.insert",
     "path": "groups/{groupKey}/members",
     "httpMethod": "POST",
     "description": "Add user to the specified group.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ]
    },
    "list": {
     "id": "directory.members.list",
     "path": "groups/{groupKey}/members",
     "httpMethod": "GET",
     "description": "Retrieve all members in a group (paginated)",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member",
      "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ]
    },
    "patch": {
     "id": "directory.members.patch",
     "path": "groups/{groupKey}/members/{memberKey}",
     "httpMethod": "PATCH",
     "description": "Update membership of a user in the specified group. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ]
    },
    "update": {
     "id": "directory.members.update",
     "path": "groups/{groupKey}/members/{memberKey}",
     "httpMethod": "PUT",
     "description": "Update membership of a user in the specified group.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ]
    }
   }
  },
  "mobiledevices": {
   "methods": {
    "action": {
     "id": "directory.mobiledevices.action",
     "path": "customer/{customerId}/devices/mobile/{resourceId}/action",
     "httpMethod": "POST",
     "description": "Take action on Mobile Device",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.action"
     ]
    },
    "delete": {
     "id": "directory.mobiledevices.delete",
     "path": "customer/{customerId}/devices/mobile/{resourceId}",
     "httpMethod": "DELETE",
     "description": "Delete Mobile Device",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile"
     ]
    },
    "get": {
     "id": "directory.mobiledevices.get",
     "path": "customer/{customerId}/devices/mobile/{resourceId}",
     "httpMethod": "GET",
     "description": "Retrieve Mobile Device",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
     ]
    },
    "list": {
     "id": "directory.mobiledevices.list",
     "path": "customer/{customerId}/devices/mobile",
     "httpMethod": "GET",
     "description": "Retrieve all Mobile Devices of a customer (paginated)",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
     ]
    }
   }
  },
  "notifications": {
   "methods": {
    "delete": {
     "id": "directory.notifications.delete",
     "path": "customer/{customer}/notifications/{notificationId}",
     "httpMethod": "DELETE",
     "description": "Deletes a notification",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ]
    },
    "get": {
     "id": "directory.notifications.get",
     "path": "customer/{customer}/notifications/{notificationId}",
     "httpMethod": "GET",
     "description": "Retrieves a notification.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ]
    },
    "list": {
     "id": "directory.notifications.list",
     "path": "customer/{customer}/notifications",
     "httpMethod": "GET",
     "description": "Retrieves a list of notifications.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ]
    },
    "patch": {
     "id": "directory.notifications.patch",
     "path": "customer/{customer}/notifications/{notificationId}",
     "httpMethod": "PATCH",
     "description": "Updates a notification. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ]
    },
    "update": {
     "id": "directory.notifications.update",
     "path": "customer/{customer}/notifications/{notificationId}",
     "httpMethod": "PUT",
     "description": "Updates a notification.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ]
    }
   }
  },
  "orgunits": {
   "methods": {
    "delete": {
     "id": "directory.orgunits.delete",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "httpMethod": "DELETE",
     "description": "Remove Organization Unit",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ]
    },
    "get": {
     "id": "directory.orgunits.get",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "httpMethod": "GET",
     "description": "Retrieve Organization Unit",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit",
      "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
     ]
    },
    "insert": {
     "id": "directory.orgunits.insert",
     "path": "customer/{customerId}/orgunits",
     "httpMethod": "POST",
     "description": "Add Organization Unit",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ]
    },
    "list": {
     "id": "directory.orgunits.list",
     "path": "customer/{customerId}/orgunits",
     "httpMethod": "GET",
     "description": "Retrieve all Organization Units",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit",
      "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
     ]
    },
    "patch": {
     "id": "directory.orgunits.patch",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "httpMethod": "PATCH",
     "description": "Update Organization Unit. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ]
    },
    "update": {
     "id": "directory.orgunits.update",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "httpMethod": "PUT",
     "description": "Update Organization Unit",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ]
    }
   }
  },
  "tokens": {
   "methods": {
    "delete": {
     "id": "directory.tokens.delete",
     "path": "users/{userKey}/tokens/{clientId}",
     "httpMethod": "DELETE",
     "description": "Delete all access tokens issued by a user for an application.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    },
    "get": {
     "id": "directory.tokens.get",
     "path": "users/{userKey}/tokens/{clientId}",
     "httpMethod": "GET",
     "description": "Get information about an access token issued by a user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    },
    "list": {
     "id": "directory.tokens.list",
     "path": "users/{userKey}/tokens",
     "httpMethod": "GET",
     "description": "Returns the set of current, valid verification codes for the specified user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    }
   }
  },
  "users": {
   "methods": {
    "delete": {
     "id": "directory.users.delete",
     "path": "users/{userKey}",
     "httpMethod": "DELETE",
     "description": "Delete user",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ]
    },
    "get": {
     "id": "directory.users.get",
     "path": "users/{userKey}",
     "httpMethod": "GET",
     "description": "retrieve user",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ]
    },
    "insert": {
     "id": "directory.users.insert",
     "path": "users",
     "httpMethod": "POST",
     "description": "create user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ]
    },
    "list": {
     "id": "directory.users.list",
     "path": "users",
     "httpMethod": "GET",
     "description": "Retrieve either deleted users or all users in a domain (paginated)",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ],
     "supportsSubscription": true
    },
    "makeAdmin": {
     "id": "directory.users.makeAdmin",
     "path": "users/{userKey}/makeAdmin",
     "httpMethod": "POST",
     "description": "change admin status of a user",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ]
    },
    "patch": {
     "id": "directory.users.patch",
     "path": "users/{userKey}",
     "httpMethod": "PATCH",
     "description": "update user. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ]
    },
    "undelete": {
     "id": "directory.users.undelete",
     "path": "users/{userKey}/undelete",
     "httpMethod": "POST",
     "description": "Undelete a deleted user",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ]
    },
    "update": {
     "id": "directory.users.update",
     "path": "users/{userKey}",
     "httpMethod": "PUT",
     "description": "update user",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ]
    },
    "watch": {
     "id": "directory.users.watch",
     "path": "users/watch",
     "httpMethod": "POST",
     "description": "Watch for changes in users list",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ],
     "supportsSubscription": true
    }
   },
   "resources": {
    "aliases": {
     "methods": {
      "delete": {
       "id": "directory.users.aliases.delete",
       "path": "users/{userKey}/aliases/{alias}",
       "httpMethod": "DELETE",
       "description": "Remove a alias for the user",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias"
       ]
      },
      "insert": {
       "id": "directory.users.aliases.insert",
       "path": "users/{userKey}/aliases",
       "httpMethod": "POST",
       "description": "Add a alias for the user",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias"
       ]
      },
      "list": {
       "id": "directory.users.aliases.list",
       "path": "users/{userKey}/aliases",
       "httpMethod": "GET",
       "description": "List all aliases for a user",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias",
        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
        "https://www.googleapis.com/auth/admin.directory.user.readonly"
       ],
       "supportsSubscription": true
      },
      "watch": {
       "id": "directory.users.aliases.watch",
       "path": "users/{userKey}/aliases/watch",
       "httpMethod": "POST",
       "description": "Watch for changes in user aliases list",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias",
        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
        "https://www.googleapis.com/auth/admin.directory.user.readonly"
       ],
       "supportsSubscription": true
      }
     }
    },
    "photos": {
     "methods": {
      "delete": {
       "id": "directory.users.photos.delete",
       "path": "users/{userKey}/photos/thumbnail",
       "httpMethod": "DELETE",
       "description": "Remove photos for the user",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user"
       ]
      },
      "get": {
       "id": "directory.users.photos.get",
       "path": "users/{userKey}/photos/thumbnail",
       "httpMethod": "GET",
       "description": "Retrieve photo of a user",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.readonly"
       ]
      },
      "patch": {
       "id": "directory.users.photos.patch",
       "path": "users/{userKey}/photos/thumbnail",
       "httpMethod": "PATCH",
       "description": "Add a photo for the user. This method supports patch semantics.",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user"
       ]
      },
      "update": {
       "id": "directory.users.photos.update",
       "path": "users/{userKey}/photos/thumbnail",
       "httpMethod": "PUT",
       "description": "Add a photo for the user",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user"
       ]
      }
     }
    }
   }
  },
  "verificationCodes": {
   "methods": {
    "generate": {
     "id": "directory.verificationCodes.generate",
     "path": "users/{userKey}/verificationCodes/generate",
     "httpMethod": "POST",
     "description": "Generate new backup verification codes for the user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    },
    "invalidate": {
     "id": "directory.verificationCodes.invalidate",
     "path": "users/{userKey}/verificationCodes/invalidate",
     "httpMethod": "POST",
     "description": "Invalidate the current backup verification codes for the user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    },
    "list": {
     "id": "directory.verificationCodes.list",
     "path": "users/{userKey}/verificationCodes",
     "httpMethod": "GET",
     "description": "Returns the current set of valid backup verification codes for the specified user.",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ]
    }
   }
  }
 }
}
