/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ConfigMapEnvSourceApplyConfiguration represents an declarative configuration of the ConfigMapEnvSource type for use
// with apply.
type ConfigMapEnvSourceApplyConfiguration struct {
	LocalObjectReferenceApplyConfiguration `json:",inline"`
	Optional                               *bool `json:"optional,omitempty"`
}

// ConfigMapEnvSourceApplyConfiguration constructs an declarative configuration of the ConfigMapEnvSource type for use with
// apply.
func ConfigMapEnvSource() *ConfigMapEnvSourceApplyConfiguration {
	return &ConfigMapEnvSourceApplyConfiguration{}
}

// SetLocalObjectReference sets the LocalObjectReference field in the declarative configuration to the given value.
func (b *ConfigMapEnvSourceApplyConfiguration) SetLocalObjectReference(value *LocalObjectReferenceApplyConfiguration) *ConfigMapEnvSourceApplyConfiguration {
	if value != nil {
		b.LocalObjectReferenceApplyConfiguration = *value
	}
	return b
}

// GetLocalObjectReference gets the LocalObjectReference field from the declarative configuration.
func (b *ConfigMapEnvSourceApplyConfiguration) GetLocalObjectReference() (value *LocalObjectReferenceApplyConfiguration, ok bool) {
	return &b.LocalObjectReferenceApplyConfiguration, true
}

// SetOptional sets the Optional field in the declarative configuration to the given value.
func (b *ConfigMapEnvSourceApplyConfiguration) SetOptional(value bool) *ConfigMapEnvSourceApplyConfiguration {
	b.Optional = &value
	return b
}

// RemoveOptional removes the Optional field from the declarative configuration.
func (b *ConfigMapEnvSourceApplyConfiguration) RemoveOptional() *ConfigMapEnvSourceApplyConfiguration {
	b.Optional = nil
	return b
}

// GetOptional gets the Optional field from the declarative configuration.
func (b *ConfigMapEnvSourceApplyConfiguration) GetOptional() (value bool, ok bool) {
	if v := b.Optional; v != nil {
		return *v, true
	}
	return value, false
}

// ConfigMapEnvSourceList represents a listAlias of ConfigMapEnvSourceApplyConfiguration.
type ConfigMapEnvSourceList []*ConfigMapEnvSourceApplyConfiguration

// ConfigMapEnvSourceList represents a map of ConfigMapEnvSourceApplyConfiguration.
type ConfigMapEnvSourceMap map[string]ConfigMapEnvSourceApplyConfiguration
