/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// VolumeMountApplyConfiguration represents an declarative configuration of the VolumeMount type for use
// with apply.
type VolumeMountApplyConfiguration struct {
	Name             *string                  `json:"name,omitempty"`
	ReadOnly         *bool                    `json:"readOnly,omitempty"`
	MountPath        *string                  `json:"mountPath,omitempty"`
	SubPath          *string                  `json:"subPath,omitempty"`
	MountPropagation *v1.MountPropagationMode `json:"mountPropagation,omitempty"`
	SubPathExpr      *string                  `json:"subPathExpr,omitempty"`
}

// VolumeMountList represents a listAlias of VolumeMountApplyConfiguration.
type VolumeMountList []*VolumeMountApplyConfiguration

// VolumeMountList represents a map of VolumeMountApplyConfiguration.
type VolumeMountMap map[string]VolumeMountApplyConfiguration
