{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/Zr1bi6MHOaAncA4AeqtGBzpWAGE\"",
 "discoveryVersion": "v1",
 "id": "genomics:v1beta2",
 "name": "genomics",
 "version": "v1beta2",
 "revision": "20151209",
 "title": "Genomics API",
 "description": "Provides access to Genomics data.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/genomics/v1beta2/reference",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/genomics/v1beta2/",
 "basePath": "/genomics/v1beta2/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "genomics/v1beta2/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/bigquery": {
     "description": "View and manage your data in Google BigQuery"
    },
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/devstorage.read_write": {
     "description": "Manage your data in Google Cloud Storage"
    },
    "https://www.googleapis.com/auth/genomics": {
     "description": "View and manage Genomics data"
    },
    "https://www.googleapis.com/auth/genomics.readonly": {
     "description": "View Genomics data"
    }
   }
  }
 },
 "resources": {
  "annotationSets": {
   "methods": {
    "create": {
     "id": "genomics.annotationSets.create",
     "path": "annotationSets",
     "httpMethod": "POST",
     "description": "Creates a new annotation set. Caller must have WRITE permission for the associated dataset.\n\nThe following fields must be provided when creating an annotation set:  \n- datasetId \n- referenceSetId  \nAll other fields may be optionally specified, unless documented as being server-generated (for example, the id field).",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.annotationSets.delete",
     "path": "annotationSets/{annotationSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes an annotation set. Caller must have WRITE permission for the associated annotation set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.annotationSets.get",
     "path": "annotationSets/{annotationSetId}",
     "httpMethod": "GET",
     "description": "Gets an annotation set. Caller must have READ permission for the associated dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.annotationSets.patch",
     "path": "annotationSets/{annotationSetId}",
     "httpMethod": "PATCH",
     "description": "Updates an annotation set. The update must respect all mutability restrictions and other invariants described on the annotation set resource. Caller must have WRITE permission for the associated dataset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.annotationSets.search",
     "path": "annotationSets/search",
     "httpMethod": "POST",
     "description": "Searches for annotation sets that match the given criteria. Annotation sets are returned in an unspecified order. This order is consistent, such that two queries for the same content (regardless of page size) yield annotation sets in the same order across their respective streams of paginated responses. Caller must have READ permission for the queried datasets.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.annotationSets.update",
     "path": "annotationSets/{annotationSetId}",
     "httpMethod": "PUT",
     "description": "Updates an annotation set. The update must respect all mutability restrictions and other invariants described on the annotation set resource. Caller must have WRITE permission for the associated dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "annotations": {
   "methods": {
    "batchCreate": {
     "id": "genomics.annotations.batchCreate",
     "path": "annotations:batchCreate",
     "httpMethod": "POST",
     "description": "Creates one or more new annotations atomically. All annotations must belong to the same annotation set. Caller must have WRITE permission for this annotation set. For optimal performance, batch positionally adjacent annotations together.\n\n\nIf the request has a systemic issue, such as an attempt to write to an inaccessible annotation set, the entire RPC will fail accordingly. For lesser data issues, when possible an error will be isolated to the corresponding batch entry i[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "create": {
     "id": "genomics.annotations.create",
     "path": "annotations",
     "httpMethod": "POST",
     "description": "Creates a new annotation. Caller must have WRITE permission for the associated annotation set.\n\n\nThe following fields must be provided when creating an annotation:  \n- annotationSetId \n- position.referenceName or  position.referenceId  Transcripts \nFor annotations of type TRANSCRIPT, the following fields of annotation.transcript must be provided:  \n- exons.start \n- exons.end  \nAll other fields may be optionally specified, unless documented as being server-generated [...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.annotations.delete",
     "path": "annotations/{annotationId}",
     "httpMethod": "DELETE",
     "description": "Deletes an annotation. Caller must have WRITE permission for the associated annotation set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.annotations.get",
     "path": "annotations/{annotationId}",
     "httpMethod": "GET",
     "description": "Gets an annotation. Caller must have READ permission for the associated annotation set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.annotations.patch",
     "path": "annotations/{annotationId}",
     "httpMethod": "PATCH",
     "description": "Updates an annotation. The update must respect all mutability restrictions and other invariants described on the annotation resource. Caller must have WRITE permission for the associated dataset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.annotations.search",
     "path": "annotations/search",
     "httpMethod": "POST",
     "description": "Searches for annotations that match the given criteria. Results are ordered by genomic coordinate (by reference sequence, then position). Annotations with equivalent genomic coordinates are returned in an unspecified order. This order is consistent, such that two queries for the same content (regardless of page size) yield annotations in the same order across their respective streams of paginated responses. Caller must have READ permission for the queried annotation sets.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.annotations.update",
     "path": "annotations/{annotationId}",
     "httpMethod": "PUT",
     "description": "Updates an annotation. The update must respect all mutability restrictions and other invariants described on the annotation resource. Caller must have WRITE permission for the associated dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "callsets": {
   "methods": {
    "create": {
     "id": "genomics.callsets.create",
     "path": "callsets",
     "httpMethod": "POST",
     "description": "Creates a new call set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.callsets.delete",
     "path": "callsets/{callSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a call set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.callsets.get",
     "path": "callsets/{callSetId}",
     "httpMethod": "GET",
     "description": "Gets a call set by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.callsets.patch",
     "path": "callsets/{callSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a call set. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.callsets.search",
     "path": "callsets/search",
     "httpMethod": "POST",
     "description": "Gets a list of call sets matching the criteria.\n\nImplements GlobalAllianceApi.searchCallSets.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.callsets.update",
     "path": "callsets/{callSetId}",
     "httpMethod": "PUT",
     "description": "Updates a call set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "datasets": {
   "methods": {
    "create": {
     "id": "genomics.datasets.create",
     "path": "datasets",
     "httpMethod": "POST",
     "description": "Creates a new dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.datasets.delete",
     "path": "datasets/{datasetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.datasets.get",
     "path": "datasets/{datasetId}",
     "httpMethod": "GET",
     "description": "Gets a dataset by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "list": {
     "id": "genomics.datasets.list",
     "path": "datasets",
     "httpMethod": "GET",
     "description": "Lists datasets within a project.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.datasets.patch",
     "path": "datasets/{datasetId}",
     "httpMethod": "PATCH",
     "description": "Updates a dataset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "undelete": {
     "id": "genomics.datasets.undelete",
     "path": "datasets/{datasetId}/undelete",
     "httpMethod": "POST",
     "description": "Undeletes a dataset by restoring a dataset which was deleted via this API. This operation is only possible for a week after the deletion occurred.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "update": {
     "id": "genomics.datasets.update",
     "path": "datasets/{datasetId}",
     "httpMethod": "PUT",
     "description": "Updates a dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "experimental": {
   "resources": {
    "jobs": {
     "methods": {
      "create": {
       "id": "genomics.experimental.jobs.create",
       "path": "experimental/jobs/create",
       "httpMethod": "POST",
       "description": "Creates and asynchronously runs an ad-hoc job. This is an experimental call and may be removed or changed at any time.",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/devstorage.read_write",
        "https://www.googleapis.com/auth/genomics"
       ]
      }
     }
    }
   }
  },
  "jobs": {
   "methods": {
    "cancel": {
     "id": "genomics.jobs.cancel",
     "path": "jobs/{jobId}/cancel",
     "httpMethod": "POST",
     "description": "Cancels a job by ID. Note that it is possible for partial results to be generated and stored for cancelled jobs.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.jobs.get",
     "path": "jobs/{jobId}",
     "httpMethod": "GET",
     "description": "Gets a job by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "search": {
     "id": "genomics.jobs.search",
     "path": "jobs/search",
     "httpMethod": "POST",
     "description": "Gets a list of jobs matching the criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  },
  "readgroupsets": {
   "methods": {
    "delete": {
     "id": "genomics.readgroupsets.delete",
     "path": "readgroupsets/{readGroupSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a read group set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "export": {
     "id": "genomics.readgroupsets.export",
     "path": "readgroupsets/export",
     "httpMethod": "POST",
     "description": "Exports read group sets to a BAM file in Google Cloud Storage.\n\nNote that currently there may be some differences between exported BAM files and the original BAM file at the time of import. See ImportReadGroupSets for details.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.readgroupsets.get",
     "path": "readgroupsets/{readGroupSetId}",
     "httpMethod": "GET",
     "description": "Gets a read group set by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "import": {
     "id": "genomics.readgroupsets.import",
     "path": "readgroupsets/import",
     "httpMethod": "POST",
     "description": "Creates read group sets by asynchronously importing the provided information. The caller must have WRITE permissions to the dataset.\n\nNotes on BAM import:  \n- Tags will be converted to strings - tag types are not preserved\n- Comments (@CO) in the input file header are not imported\n- Original order of reference headers is not preserved\n- Any reverse stranded unmapped reads will be reverse complemented, and their qualities (and \"BQ\" tag, if any) will be reversed\n- Unm[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.readgroupsets.patch",
     "path": "readgroupsets/{readGroupSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a read group set. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.readgroupsets.search",
     "path": "readgroupsets/search",
     "httpMethod": "POST",
     "description": "Searches for read group sets matching the criteria.\n\nImplements GlobalAllianceApi.searchReadGroupSets.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.readgroupsets.update",
     "path": "readgroupsets/{readGroupSetId}",
     "httpMethod": "PUT",
     "description": "Updates a read group set.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   },
   "resources": {
    "coveragebuckets": {
     "methods": {
      "list": {
       "id": "genomics.readgroupsets.coveragebuckets.list",
       "path": "readgroupsets/{readGroupSetId}/coveragebuckets",
       "httpMethod": "GET",
       "description": "Lists fixed width coverage buckets for a read group set, each of which correspond to a range of a reference sequence. Each bucket summarizes coverage information across its corresponding genomic range.\n\nCoverage is defined as the number of reads which are aligned to a given base in the reference sequence. Coverage buckets are available at several precomputed bucket widths, enabling retrieval of various coverage 'zoom levels'. The caller must have READ permissions for the[...]",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/genomics",
        "https://www.googleapis.com/auth/genomics.readonly"
       ]
      }
     }
    }
   }
  },
  "reads": {
   "methods": {
    "search": {
     "id": "genomics.reads.search",
     "path": "reads/search",
     "httpMethod": "POST",
     "description": "Gets a list of reads for one or more read group sets. Reads search operates over a genomic coordinate space of reference sequence & position defined over the reference sequences to which the requested read group sets are aligned.\n\nIf a target positional range is specified, search returns all reads whose alignment to the reference genome overlap the range. A query which specifies only read group set IDs yields all reads in those read group sets, including unmapped reads.\n\[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  },
  "references": {
   "methods": {
    "get": {
     "id": "genomics.references.get",
     "path": "references/{referenceId}",
     "httpMethod": "GET",
     "description": "Gets a reference.\n\nImplements GlobalAllianceApi.getReference.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "search": {
     "id": "genomics.references.search",
     "path": "references/search",
     "httpMethod": "POST",
     "description": "Searches for references which match the given criteria.\n\nImplements GlobalAllianceApi.searchReferences.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   },
   "resources": {
    "bases": {
     "methods": {
      "list": {
       "id": "genomics.references.bases.list",
       "path": "references/{referenceId}/bases",
       "httpMethod": "GET",
       "description": "Lists the bases in a reference, optionally restricted to a range.\n\nImplements GlobalAllianceApi.getReferenceBases.",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/genomics",
        "https://www.googleapis.com/auth/genomics.readonly"
       ]
      }
     }
    }
   }
  },
  "referencesets": {
   "methods": {
    "get": {
     "id": "genomics.referencesets.get",
     "path": "referencesets/{referenceSetId}",
     "httpMethod": "GET",
     "description": "Gets a reference set.\n\nImplements GlobalAllianceApi.getReferenceSet.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "search": {
     "id": "genomics.referencesets.search",
     "path": "referencesets/search",
     "httpMethod": "POST",
     "description": "Searches for reference sets which match the given criteria.\n\nImplements GlobalAllianceApi.searchReferenceSets.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  },
  "variants": {
   "methods": {
    "create": {
     "id": "genomics.variants.create",
     "path": "variants",
     "httpMethod": "POST",
     "description": "Creates a new variant.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.variants.delete",
     "path": "variants/{variantId}",
     "httpMethod": "DELETE",
     "description": "Deletes a variant.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.variants.get",
     "path": "variants/{variantId}",
     "httpMethod": "GET",
     "description": "Gets a variant by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "search": {
     "id": "genomics.variants.search",
     "path": "variants/search",
     "httpMethod": "POST",
     "description": "Gets a list of variants matching the criteria.\n\nImplements GlobalAllianceApi.searchVariants.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.variants.update",
     "path": "variants/{variantId}",
     "httpMethod": "PUT",
     "description": "Updates a variant's names and info fields. All other modifications are silently ignored. Returns the modified variant without its calls.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "variantsets": {
   "methods": {
    "create": {
     "id": "genomics.variantsets.create",
     "path": "variantsets",
     "httpMethod": "POST",
     "description": "Creates a new variant set (only necessary in v1).\n\nThe provided variant set must have a valid datasetId set - all other fields are optional. Note that the id field will be ignored, as this is assigned by the server.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.variantsets.delete",
     "path": "variantsets/{variantSetId}",
     "httpMethod": "DELETE",
     "description": "Deletes the contents of a variant set. The variant set object is not deleted.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "export": {
     "id": "genomics.variantsets.export",
     "path": "variantsets/{variantSetId}/export",
     "httpMethod": "POST",
     "description": "Exports variant set data to an external destination.",
     "scopes": [
      "https://www.googleapis.com/auth/bigquery",
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.variantsets.get",
     "path": "variantsets/{variantSetId}",
     "httpMethod": "GET",
     "description": "Gets a variant set by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "importVariants": {
     "id": "genomics.variantsets.importVariants",
     "path": "variantsets/{variantSetId}/importVariants",
     "httpMethod": "POST",
     "description": "Creates variant data by asynchronously importing the provided information.\n\nThe variants for import will be merged with any existing data and each other according to the behavior of mergeVariants. In particular, this means for merged VCF variants that have conflicting INFO fields, some data will be arbitrarily discarded. As a special case, for single-sample VCF files, QUAL and FILTER fields will be moved to the call level; these are sometimes interpreted in a call-specific[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "mergeVariants": {
     "id": "genomics.variantsets.mergeVariants",
     "path": "variantsets/{variantSetId}/mergeVariants",
     "httpMethod": "POST",
     "description": "Merges the given variants with existing variants. Each variant will be merged with an existing variant that matches its reference sequence, start, end, reference bases, and alternative bases. If no such variant exists, a new one will be created.\n\nWhen variants are merged, the call information from the new variant is added to the existing variant, and other fields (such as key/value pairs) are discarded.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.variantsets.patch",
     "path": "variantsets/{variantSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a variant set's metadata. All other modifications are silently ignored. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.variantsets.search",
     "path": "variantsets/search",
     "httpMethod": "POST",
     "description": "Returns a list of all variant sets matching search criteria.\n\nImplements GlobalAllianceApi.searchVariantSets.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.variantsets.update",
     "path": "variantsets/{variantSetId}",
     "httpMethod": "PUT",
     "description": "Updates a variant set's metadata. All other modifications are silently ignored.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  }
 }
}
