FROM golang:1.14

ENV GOPROXY=direct

ADD . /go/src/github.com/aws/aws-sdk-go

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/github.com/aws/aws-sdk-go
CMD ["make", "get-deps-verify", "unit"]
