{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/Ob-vIbU0CMw39spLQLZEQavYp3Q\"",
 "discoveryVersion": "v1",
 "id": "adexchangeseller:v1.1",
 "name": "adexchangeseller",
 "canonicalName": "Ad Exchange Seller",
 "version": "v1.1",
 "revision": "20141112",
 "title": "Ad Exchange Seller API",
 "description": "Gives Ad Exchange seller users access to their inventory and the ability to generate reports",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/ad-exchange/seller-rest/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/adexchangeseller/v1.1/",
 "basePath": "/adexchangeseller/v1.1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "adexchangeseller/v1.1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/adexchange.seller": {
     "description": "View and manage your Ad Exchange data"
    },
    "https://www.googleapis.com/auth/adexchange.seller.readonly": {
     "description": "View your Ad Exchange data"
    }
   }
  }
 },
 "resources": {
  "accounts": {
   "methods": {
    "get": {
     "id": "adexchangeseller.accounts.get",
     "path": "accounts/{accountId}",
     "httpMethod": "GET",
     "description": "Get information about the selected Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   }
  },
  "adclients": {
   "methods": {
    "list": {
     "id": "adexchangeseller.adclients.list",
     "path": "adclients",
     "httpMethod": "GET",
     "description": "List all ad clients in this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   }
  },
  "adunits": {
   "methods": {
    "get": {
     "id": "adexchangeseller.adunits.get",
     "path": "adclients/{adClientId}/adunits/{adUnitId}",
     "httpMethod": "GET",
     "description": "Gets the specified ad unit in the specified ad client.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    },
    "list": {
     "id": "adexchangeseller.adunits.list",
     "path": "adclients/{adClientId}/adunits",
     "httpMethod": "GET",
     "description": "List all ad units in the specified ad client for this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   },
   "resources": {
    "customchannels": {
     "methods": {
      "list": {
       "id": "adexchangeseller.adunits.customchannels.list",
       "path": "adclients/{adClientId}/adunits/{adUnitId}/customchannels",
       "httpMethod": "GET",
       "description": "List all custom channels which the specified ad unit belongs to.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    }
   }
  },
  "alerts": {
   "methods": {
    "list": {
     "id": "adexchangeseller.alerts.list",
     "path": "alerts",
     "httpMethod": "GET",
     "description": "List the alerts for this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   }
  },
  "customchannels": {
   "methods": {
    "get": {
     "id": "adexchangeseller.customchannels.get",
     "path": "adclients/{adClientId}/customchannels/{customChannelId}",
     "httpMethod": "GET",
     "description": "Get the specified custom channel from the specified ad client.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    },
    "list": {
     "id": "adexchangeseller.customchannels.list",
     "path": "adclients/{adClientId}/customchannels",
     "httpMethod": "GET",
     "description": "List all custom channels in the specified ad client for this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   },
   "resources": {
    "adunits": {
     "methods": {
      "list": {
       "id": "adexchangeseller.customchannels.adunits.list",
       "path": "adclients/{adClientId}/customchannels/{customChannelId}/adunits",
       "httpMethod": "GET",
       "description": "List all ad units in the specified custom channel.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    }
   }
  },
  "metadata": {
   "resources": {
    "dimensions": {
     "methods": {
      "list": {
       "id": "adexchangeseller.metadata.dimensions.list",
       "path": "metadata/dimensions",
       "httpMethod": "GET",
       "description": "List the metadata for the dimensions available to this AdExchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    },
    "metrics": {
     "methods": {
      "list": {
       "id": "adexchangeseller.metadata.metrics.list",
       "path": "metadata/metrics",
       "httpMethod": "GET",
       "description": "List the metadata for the metrics available to this AdExchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    }
   }
  },
  "preferreddeals": {
   "methods": {
    "get": {
     "id": "adexchangeseller.preferreddeals.get",
     "path": "preferreddeals/{dealId}",
     "httpMethod": "GET",
     "description": "Get information about the selected Ad Exchange Preferred Deal.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    },
    "list": {
     "id": "adexchangeseller.preferreddeals.list",
     "path": "preferreddeals",
     "httpMethod": "GET",
     "description": "List the preferred deals for this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   }
  },
  "reports": {
   "methods": {
    "generate": {
     "id": "adexchangeseller.reports.generate",
     "path": "reports",
     "httpMethod": "GET",
     "description": "Generate an Ad Exchange report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": true
    }
   },
   "resources": {
    "saved": {
     "methods": {
      "generate": {
       "id": "adexchangeseller.reports.saved.generate",
       "path": "reports/{savedReportId}",
       "httpMethod": "GET",
       "description": "Generate an Ad Exchange report based on the saved report ID sent in the query parameters.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      },
      "list": {
       "id": "adexchangeseller.reports.saved.list",
       "path": "reports/saved",
       "httpMethod": "GET",
       "description": "List all saved reports in this Ad Exchange account.",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ]
      }
     }
    }
   }
  },
  "urlchannels": {
   "methods": {
    "list": {
     "id": "adexchangeseller.urlchannels.list",
     "path": "adclients/{adClientId}/urlchannels",
     "httpMethod": "GET",
     "description": "List all URL channels in the specified ad client for this Ad Exchange account.",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ]
    }
   }
  }
 }
}
