#!/bin/bash

set +ex

# Restart the apiserver, controller-manager, and scheduler

systemctl restart snap.kube-apiserver.daemon
action-set apiserver.status='restarted'

systemctl restart snap.kube-controller-manager.daemon
action-set controller-manager.status='restarted'

systemctl restart snap.kube-scheduler.daemon
action-set kube-scheduler.status='restarted'
