{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/jFfT_5FQxY4swYRA_Wr05M6Vn5o\"",
 "discoveryVersion": "v1",
 "id": "drive:v3",
 "name": "drive",
 "version": "v3",
 "revision": "20151209",
 "title": "Drive API",
 "description": "The API to interact with Drive.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/drive/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/drive/v3/",
 "basePath": "/drive/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "drive/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.appdata": {
     "description": "View and manage its own configuration data in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.file": {
     "description": "View and manage Google Drive files and folders that you have opened or created with this app"
    },
    "https://www.googleapis.com/auth/drive.metadata": {
     "description": "View and manage metadata of files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.metadata.readonly": {
     "description": "View metadata for files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.photos.readonly": {
     "description": "View the photos, videos and albums in your Google Photos"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "View the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.scripts": {
     "description": "Modify your Google Apps Script scripts' behavior"
    }
   }
  }
 },
 "resources": {
  "about": {
   "methods": {
    "get": {
     "id": "drive.about.get",
     "path": "about",
     "httpMethod": "GET",
     "description": "Gets information about the user, the user's Drive, and system capabilities.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "changes": {
   "methods": {
    "getStartPageToken": {
     "id": "drive.changes.getStartPageToken",
     "path": "changes/startPageToken",
     "httpMethod": "GET",
     "description": "Gets the starting pageToken for listing future changes.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.changes.list",
     "path": "changes",
     "httpMethod": "GET",
     "description": "Lists changes for a user.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsSubscription": true
    },
    "watch": {
     "id": "drive.changes.watch",
     "path": "changes/watch",
     "httpMethod": "POST",
     "description": "Subscribes to changes for a user.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsSubscription": true
    }
   }
  },
  "channels": {
   "methods": {
    "stop": {
     "id": "drive.channels.stop",
     "path": "channels/stop",
     "httpMethod": "POST",
     "description": "Stop watching resources through this channel",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "comments": {
   "methods": {
    "create": {
     "id": "drive.comments.create",
     "path": "files/{fileId}/comments",
     "httpMethod": "POST",
     "description": "Creates a new comment on a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.comments.delete",
     "path": "files/{fileId}/comments/{commentId}",
     "httpMethod": "DELETE",
     "description": "Deletes a comment.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.comments.get",
     "path": "files/{fileId}/comments/{commentId}",
     "httpMethod": "GET",
     "description": "Gets a comment by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.comments.list",
     "path": "files/{fileId}/comments",
     "httpMethod": "GET",
     "description": "Lists a file's comments.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.comments.update",
     "path": "files/{fileId}/comments/{commentId}",
     "httpMethod": "PATCH",
     "description": "Updates a comment with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "files": {
   "methods": {
    "copy": {
     "id": "drive.files.copy",
     "path": "files/{fileId}/copy",
     "httpMethod": "POST",
     "description": "Creates a copy of a file and applies any requested updates with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.photos.readonly"
     ]
    },
    "create": {
     "id": "drive.files.create",
     "path": "files",
     "httpMethod": "POST",
     "description": "Creates a new file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ],
     "supportsMediaUpload": true,
     "supportsSubscription": true
    },
    "delete": {
     "id": "drive.files.delete",
     "path": "files/{fileId}",
     "httpMethod": "DELETE",
     "description": "Permanently deletes a file owned by the user without moving it to the trash. If the target is a folder, all descendants owned by the user are also deleted.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "emptyTrash": {
     "id": "drive.files.emptyTrash",
     "path": "files/trash",
     "httpMethod": "DELETE",
     "description": "Permanently deletes all of the user's trashed files.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "export": {
     "id": "drive.files.export",
     "path": "files/{fileId}/export",
     "httpMethod": "GET",
     "description": "Exports a Google Doc to the requested MIME type.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true
    },
    "generateIds": {
     "id": "drive.files.generateIds",
     "path": "files/generateIds",
     "httpMethod": "GET",
     "description": "Generates a set of file IDs which can be provided in create requests.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.files.get",
     "path": "files/{fileId}",
     "httpMethod": "GET",
     "description": "Gets a file's metadata or content by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true,
     "supportsSubscription": true
    },
    "list": {
     "id": "drive.files.list",
     "path": "files",
     "httpMethod": "GET",
     "description": "Lists or searches files.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.files.update",
     "path": "files/{fileId}",
     "httpMethod": "PATCH",
     "description": "Updates a file's metadata and/or content with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.scripts"
     ],
     "supportsMediaUpload": true
    },
    "watch": {
     "id": "drive.files.watch",
     "path": "files/{fileId}/watch",
     "httpMethod": "POST",
     "description": "Subscribes to changes to a file",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true,
     "supportsSubscription": true
    }
   }
  },
  "permissions": {
   "methods": {
    "create": {
     "id": "drive.permissions.create",
     "path": "files/{fileId}/permissions",
     "httpMethod": "POST",
     "description": "Creates a permission for a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.permissions.delete",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "DELETE",
     "description": "Deletes a permission.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.permissions.get",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "GET",
     "description": "Gets a permission by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.permissions.list",
     "path": "files/{fileId}/permissions",
     "httpMethod": "GET",
     "description": "Lists a file's permissions.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.permissions.update",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "PATCH",
     "description": "Updates a permission with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "replies": {
   "methods": {
    "create": {
     "id": "drive.replies.create",
     "path": "files/{fileId}/comments/{commentId}/replies",
     "httpMethod": "POST",
     "description": "Creates a new reply to a comment.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.replies.delete",
     "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
     "httpMethod": "DELETE",
     "description": "Deletes a reply.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.replies.get",
     "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
     "httpMethod": "GET",
     "description": "Gets a reply by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.replies.list",
     "path": "files/{fileId}/comments/{commentId}/replies",
     "httpMethod": "GET",
     "description": "Lists a comment's replies.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.replies.update",
     "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
     "httpMethod": "PATCH",
     "description": "Updates a reply with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "revisions": {
   "methods": {
    "delete": {
     "id": "drive.revisions.delete",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "DELETE",
     "description": "Permanently deletes a revision. This method is only applicable to files with binary content in Drive.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.revisions.get",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "GET",
     "description": "Gets a revision's metadata or content by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true
    },
    "list": {
     "id": "drive.revisions.list",
     "path": "files/{fileId}/revisions",
     "httpMethod": "GET",
     "description": "Lists a file's revisions.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.revisions.update",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "PATCH",
     "description": "Updates a revision with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  }
 }
}
