{
 "kind": "discovery#restDescription",
 "etag": "\"wtgj9ZncHCe-ShJM8RewHb1DgWI/osZuPoYT5hJnE0hEpTbvxVAA6M0\"",
 "discoveryVersion": "v1",
 "id": "plus:v1domains",
 "name": "plus",
 "version": "v1domains",
 "revision": "20130726",
 "title": "Google+ API",
 "description": "The Google+ API enables developers to build on top of the Google+ platform.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/+/api/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/plus/v1domains/",
 "basePath": "/plus/v1domains/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "plus/v1domains/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/plus.circles.read": {
     "description": "View your circles and people in them"
    },
    "https://www.googleapis.com/auth/plus.circles.write": {
     "description": "Manage your circles and add people"
    },
    "https://www.googleapis.com/auth/plus.login": {
     "description": "Know your name, basic info, and list of people you're connected to on Google+"
    },
    "https://www.googleapis.com/auth/plus.me": {
     "description": "Know who you are on Google"
    },
    "https://www.googleapis.com/auth/plus.media.upload": {
     "description": "Send your photos and videos to Google+"
    },
    "https://www.googleapis.com/auth/plus.profiles.read": {
     "description": "View your own Google+ profile and profiles shared with you"
    },
    "https://www.googleapis.com/auth/plus.stream.read": {
     "description": "View your posts, comments, and stream"
    },
    "https://www.googleapis.com/auth/plus.stream.write": {
     "description": "Manage your posts, comments, and stream"
    }
   }
  }
 },
 "resources": {
  "activities": {
   "methods": {
    "get": {
     "id": "plus.activities.get",
     "path": "activities/{activityId}",
     "httpMethod": "GET",
     "description": "Get an activity.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.stream.read"
     ]
    },
    "insert": {
     "id": "plus.activities.insert",
     "path": "people/{userId}/activities",
     "httpMethod": "POST",
     "description": "Create a new activity for the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.stream.write"
     ]
    },
    "list": {
     "id": "plus.activities.list",
     "path": "people/{userId}/activities/{collection}",
     "httpMethod": "GET",
     "description": "List all of the activities in the specified collection for a particular user.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.stream.read"
     ]
    }
   }
  },
  "audiences": {
   "methods": {
    "list": {
     "id": "plus.audiences.list",
     "path": "people/{userId}/audiences",
     "httpMethod": "GET",
     "description": "List all of the audiences to which a user can share.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ]
    }
   }
  },
  "circles": {
   "methods": {
    "addPeople": {
     "id": "plus.circles.addPeople",
     "path": "circles/{circleId}/people",
     "httpMethod": "PUT",
     "description": "Add a person to a circle. Google+ limits certain circle operations, including the number of circle adds. Learn More.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ]
    },
    "get": {
     "id": "plus.circles.get",
     "path": "circles/{circleId}",
     "httpMethod": "GET",
     "description": "Get a circle.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login"
     ]
    },
    "insert": {
     "id": "plus.circles.insert",
     "path": "people/{userId}/circles",
     "httpMethod": "POST",
     "description": "Create a new circle for the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ]
    },
    "list": {
     "id": "plus.circles.list",
     "path": "people/{userId}/circles",
     "httpMethod": "GET",
     "description": "List all of the circles for a user.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ]
    },
    "patch": {
     "id": "plus.circles.patch",
     "path": "circles/{circleId}",
     "httpMethod": "PATCH",
     "description": "Update a circle's description. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ]
    },
    "remove": {
     "id": "plus.circles.remove",
     "path": "circles/{circleId}",
     "httpMethod": "DELETE",
     "description": "Delete a circle.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ]
    },
    "removePeople": {
     "id": "plus.circles.removePeople",
     "path": "circles/{circleId}/people",
     "httpMethod": "DELETE",
     "description": "Remove a person from a circle.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ]
    },
    "update": {
     "id": "plus.circles.update",
     "path": "circles/{circleId}",
     "httpMethod": "PUT",
     "description": "Update a circle's description.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ]
    }
   }
  },
  "comments": {
   "methods": {
    "get": {
     "id": "plus.comments.get",
     "path": "comments/{commentId}",
     "httpMethod": "GET",
     "description": "Get a comment.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.read"
     ]
    },
    "insert": {
     "id": "plus.comments.insert",
     "path": "activities/{activityId}/comments",
     "httpMethod": "POST",
     "description": "Create a new comment in reply to an activity.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.write"
     ]
    },
    "list": {
     "id": "plus.comments.list",
     "path": "activities/{activityId}/comments",
     "httpMethod": "GET",
     "description": "List all of the comments for an activity.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.read"
     ]
    }
   }
  },
  "media": {
   "methods": {
    "insert": {
     "id": "plus.media.insert",
     "path": "people/{userId}/media/{collection}",
     "httpMethod": "POST",
     "description": "Add a new media item to an album. The current upload size limitations are 36MB for a photo and 1GB for a video. Uploads do not count against quota if photos are less than 2048 pixels on their longest side or videos are less than 15 minutes in length.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.media.upload"
     ],
     "supportsMediaUpload": true
    }
   }
  },
  "people": {
   "methods": {
    "get": {
     "id": "plus.people.get",
     "path": "people/{userId}",
     "httpMethod": "GET",
     "description": "Get a person's profile.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.profiles.read"
     ]
    },
    "list": {
     "id": "plus.people.list",
     "path": "people/{userId}/people/{collection}",
     "httpMethod": "GET",
     "description": "List all of the people in the specified collection.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ]
    },
    "listByActivity": {
     "id": "plus.people.listByActivity",
     "path": "activities/{activityId}/people/{collection}",
     "httpMethod": "GET",
     "description": "List all of the people in the specified collection for a particular activity.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.read"
     ]
    },
    "listByCircle": {
     "id": "plus.people.listByCircle",
     "path": "circles/{circleId}/people",
     "httpMethod": "GET",
     "description": "List all of the people who are members of a circle.",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login"
     ]
    }
   }
  }
 }
}
