{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/VbFh0P5gIX42P6rhPLVK-GI_3-Y\"",
 "discoveryVersion": "v1",
 "id": "classroom:v1",
 "name": "classroom",
 "version": "v1",
 "revision": "20151013",
 "title": "Google Classroom API",
 "description": "Google Classroom API",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/classroom/",
 "protocol": "rest",
 "baseUrl": "https://classroom.googleapis.com/",
 "basePath": "/",
 "rootUrl": "https://classroom.googleapis.com/",
 "servicePath": "",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/classroom.courses": {
     "description": "Manage your Google Classroom classes"
    },
    "https://www.googleapis.com/auth/classroom.courses.readonly": {
     "description": "View your Google Classroom classes"
    },
    "https://www.googleapis.com/auth/classroom.profile.emails": {
     "description": "View the email addresses of people in your classes"
    },
    "https://www.googleapis.com/auth/classroom.profile.photos": {
     "description": "View the profile photos of people in your classes"
    },
    "https://www.googleapis.com/auth/classroom.rosters": {
     "description": "Manage your Google Classroom class rosters"
    },
    "https://www.googleapis.com/auth/classroom.rosters.readonly": {
     "description": "View your Google Classroom class rosters"
    }
   }
  }
 },
 "resources": {
  "courses": {
   "methods": {
    "create": {
     "id": "classroom.courses.create",
     "path": "v1/courses",
     "httpMethod": "POST",
     "description": "Creates a course. The user specified in `ownerId` is the owner of the created course and added as a teacher. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses or for access errors. * `NOT_FOUND` if the primary teacher is not a valid user. * `FAILED_PRECONDITION` if the course owner's account is disabled or for the following request errors: * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if an [...]",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "get": {
     "id": "classroom.courses.get",
     "path": "v1/courses/{id}",
     "httpMethod": "GET",
     "description": "Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses",
      "https://www.googleapis.com/auth/classroom.courses.readonly"
     ]
    },
    "update": {
     "id": "classroom.courses.update",
     "path": "v1/courses/{id}",
     "httpMethod": "PUT",
     "description": "Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "patch": {
     "id": "classroom.courses.patch",
     "path": "v1/courses/{id}",
     "httpMethod": "PATCH",
     "description": "Updates one or more fields in a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "delete": {
     "id": "classroom.courses.delete",
     "path": "v1/courses/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "list": {
     "id": "classroom.courses.list",
     "path": "v1/courses",
     "httpMethod": "GET",
     "description": "Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses",
      "https://www.googleapis.com/auth/classroom.courses.readonly"
     ]
    }
   },
   "resources": {
    "aliases": {
     "methods": {
      "create": {
       "id": "classroom.courses.aliases.create",
       "path": "v1/courses/{courseId}/aliases",
       "httpMethod": "POST",
       "description": "Creates an alias for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the alias or for access errors. * `NOT_FOUND` if the course does not exist. * `ALREADY_EXISTS` if the alias already exists.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.courses"
       ]
      },
      "delete": {
       "id": "classroom.courses.aliases.delete",
       "path": "v1/courses/{courseId}/aliases/{alias}",
       "httpMethod": "DELETE",
       "description": "Deletes an alias of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to remove the alias or for access errors. * `NOT_FOUND` if the alias does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.courses"
       ]
      },
      "list": {
       "id": "classroom.courses.aliases.list",
       "path": "v1/courses/{courseId}/aliases",
       "httpMethod": "GET",
       "description": "Returns a list of aliases for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the course or for access errors. * `NOT_FOUND` if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.courses",
        "https://www.googleapis.com/auth/classroom.courses.readonly"
       ]
      }
     }
    },
    "teachers": {
     "methods": {
      "create": {
       "id": "classroom.courses.teachers.create",
       "path": "v1/courses/{courseId}/teachers",
       "httpMethod": "POST",
       "description": "Creates a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create teachers in this course or for access errors. * `NOT_FOUND` if the requested course ID does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled, for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReached * UserGroupsMembershipLimitReached * `ALREAD[...]",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "get": {
       "id": "classroom.courses.teachers.get",
       "path": "v1/courses/{courseId}/teachers/{userId}",
       "httpMethod": "GET",
       "description": "Returns a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      },
      "delete": {
       "id": "classroom.courses.teachers.delete",
       "path": "v1/courses/{courseId}/teachers/{userId}",
       "httpMethod": "DELETE",
       "description": "Deletes a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of this course.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "list": {
       "id": "classroom.courses.teachers.list",
       "path": "v1/courses/{courseId}/teachers",
       "httpMethod": "GET",
       "description": "Returns a list of teachers of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      }
     }
    },
    "students": {
     "methods": {
      "create": {
       "id": "classroom.courses.students.create",
       "path": "v1/courses/{courseId}/students",
       "httpMethod": "POST",
       "description": "Adds a user as a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create students in this course or for access errors. * `NOT_FOUND` if the requested course ID does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled, for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if the user[...]",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "get": {
       "id": "classroom.courses.students.get",
       "path": "v1/courses/{courseId}/students/{userId}",
       "httpMethod": "GET",
       "description": "Returns a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      },
      "delete": {
       "id": "classroom.courses.students.delete",
       "path": "v1/courses/{courseId}/students/{userId}",
       "httpMethod": "DELETE",
       "description": "Deletes a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "list": {
       "id": "classroom.courses.students.list",
       "path": "v1/courses/{courseId}/students",
       "httpMethod": "GET",
       "description": "Returns a list of students of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      }
     }
    }
   }
  },
  "invitations": {
   "methods": {
    "create": {
     "id": "classroom.invitations.create",
     "path": "v1/invitations",
     "httpMethod": "POST",
     "description": "Creates an invitation. Only one invitation for a user and course may exist at a time. Delete and re-create an invitation to make changes. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create invitations for this course or for access errors. * `NOT_FOUND` if the course or the user does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled or if the user already has this role or a role w[...]",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters"
     ]
    },
    "get": {
     "id": "classroom.invitations.get",
     "path": "v1/invitations/{id}",
     "httpMethod": "GET",
     "description": "Returns an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters",
      "https://www.googleapis.com/auth/classroom.rosters.readonly"
     ]
    },
    "delete": {
     "id": "classroom.invitations.delete",
     "path": "v1/invitations/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters"
     ]
    },
    "list": {
     "id": "classroom.invitations.list",
     "path": "v1/invitations",
     "httpMethod": "GET",
     "description": "Returns a list of invitations that the requesting user is permitted to view, restricted to those that match the list request. *Note:* At least one of `user_id` or `course_id` must be supplied. Both fields can be supplied. This method returns the following error codes: * `PERMISSION_DENIED` for access errors.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters",
      "https://www.googleapis.com/auth/classroom.rosters.readonly"
     ]
    },
    "accept": {
     "id": "classroom.invitations.accept",
     "path": "v1/invitations/{id}:accept",
     "httpMethod": "POST",
     "description": "Accepts an invitation, removing it and adding the invited user to the teachers or students (as appropriate) of the specified course. Only the invited user may accept an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to accept the requested invitation or for access errors. * `FAILED_PRECONDITION` for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReach[...]",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters"
     ]
    }
   }
  },
  "userProfiles": {
   "methods": {
    "get": {
     "id": "classroom.userProfiles.get",
     "path": "v1/userProfiles/{userId}",
     "httpMethod": "GET",
     "description": "Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile or if no profile exists with the requested ID or for access errors.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.profile.emails",
      "https://www.googleapis.com/auth/classroom.profile.photos",
      "https://www.googleapis.com/auth/classroom.rosters",
      "https://www.googleapis.com/auth/classroom.rosters.readonly"
     ]
    }
   }
  }
 }
}
