{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/3m5rB86FE5KuW1K3jAl88AxCreg\"",
 "discoveryVersion": "v1",
 "id": "mapsengine:v1",
 "name": "mapsengine",
 "canonicalName": "Maps Engine",
 "version": "v1",
 "title": "Google Maps Engine API",
 "description": "The Google Maps Engine API allows developers to store and query geospatial vector and raster data.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/maps-engine/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/mapsengine/v1/",
 "basePath": "/mapsengine/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "mapsengine/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/mapsengine": {
     "description": "View and manage your Google Maps Engine data"
    },
    "https://www.googleapis.com/auth/mapsengine.readonly": {
     "description": "View your Google Maps Engine data"
    }
   }
  }
 },
 "resources": {
  "assets": {
   "methods": {
    "get": {
     "id": "mapsengine.assets.get",
     "path": "assets/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.assets.list",
     "path": "assets",
     "httpMethod": "GET",
     "description": "Return all assets readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    }
   },
   "resources": {
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.assets.parents.list",
       "path": "assets/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "layers": {
   "methods": {
    "create": {
     "id": "mapsengine.layers.create",
     "path": "layers",
     "httpMethod": "POST",
     "description": "Create a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.layers.get",
     "path": "layers/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular layer.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.layers.list",
     "path": "layers",
     "httpMethod": "GET",
     "description": "Return all layers readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "process": {
     "id": "mapsengine.layers.process",
     "path": "layers/{id}/process",
     "httpMethod": "POST",
     "description": "Process a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "publish": {
     "id": "mapsengine.layers.publish",
     "path": "layers/{id}/publish",
     "httpMethod": "POST",
     "description": "Publish a layer asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.layers.parents.list",
       "path": "layers/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified layer.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "maps": {
   "methods": {
    "get": {
     "id": "mapsengine.maps.get",
     "path": "maps/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular map.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.maps.list",
     "path": "maps",
     "httpMethod": "GET",
     "description": "Return all maps readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    }
   }
  },
  "projects": {
   "methods": {
    "list": {
     "id": "mapsengine.projects.list",
     "path": "projects",
     "httpMethod": "GET",
     "description": "Return all projects readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    }
   }
  },
  "rasterCollections": {
   "methods": {
    "create": {
     "id": "mapsengine.rasterCollections.create",
     "path": "rasterCollections",
     "httpMethod": "POST",
     "description": "Create a raster collection asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.rasterCollections.get",
     "path": "rasterCollections/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular raster collection.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.rasterCollections.list",
     "path": "rasterCollections",
     "httpMethod": "GET",
     "description": "Return all raster collections readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    }
   },
   "resources": {
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.rasterCollections.parents.list",
       "path": "rasterCollections/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified raster collection.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "rasters": {
     "methods": {
      "list": {
       "id": "mapsengine.rasterCollections.rasters.list",
       "path": "rasterCollections/{id}/rasters",
       "httpMethod": "GET",
       "description": "Return all rasters within a raster collection.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "rasters": {
   "methods": {
    "get": {
     "id": "mapsengine.rasters.get",
     "path": "rasters/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a single raster.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "upload": {
     "id": "mapsengine.rasters.upload",
     "path": "rasters/upload",
     "httpMethod": "POST",
     "description": "Create a skeleton raster asset for upload.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "files": {
     "methods": {
      "insert": {
       "id": "mapsengine.rasters.files.insert",
       "path": "rasters/{id}/files",
       "httpMethod": "POST",
       "description": "Upload a file to a raster asset.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.rasters.parents.list",
       "path": "rasters/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified rasters.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  },
  "tables": {
   "methods": {
    "create": {
     "id": "mapsengine.tables.create",
     "path": "tables",
     "httpMethod": "POST",
     "description": "Create a table asset.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    },
    "get": {
     "id": "mapsengine.tables.get",
     "path": "tables/{id}",
     "httpMethod": "GET",
     "description": "Return metadata for a particular table, including the schema.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "list": {
     "id": "mapsengine.tables.list",
     "path": "tables",
     "httpMethod": "GET",
     "description": "Return all tables readable by the current user.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine",
      "https://www.googleapis.com/auth/mapsengine.readonly"
     ]
    },
    "upload": {
     "id": "mapsengine.tables.upload",
     "path": "tables/upload",
     "httpMethod": "POST",
     "description": "Create a placeholder table asset to which table files can be uploaded.\nOnce the placeholder has been created, files are uploaded to the https://www.googleapis.com/upload/mapsengine/v1/tables/table_id/files endpoint.\nSee Table Upload in the Developer's Guide or Table.files: insert in the reference documentation for more information.",
     "scopes": [
      "https://www.googleapis.com/auth/mapsengine"
     ]
    }
   },
   "resources": {
    "features": {
     "methods": {
      "batchDelete": {
       "id": "mapsengine.tables.features.batchDelete",
       "path": "tables/{id}/features/batchDelete",
       "httpMethod": "POST",
       "description": "Delete all features matching the given IDs.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchInsert": {
       "id": "mapsengine.tables.features.batchInsert",
       "path": "tables/{id}/features/batchInsert",
       "httpMethod": "POST",
       "description": "Append features to an existing table.\n\nA single batchInsert request can create:\n\n- Up to 50 features.\n- A combined total of 10 000 vertices.\nFeature limits are documented in the Supported data formats and limits article of the Google Maps Engine help center. Note that free and paid accounts have different limits.\n\nFor more information about inserting features, read Creating features in the Google Maps Engine developer's guide.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "batchPatch": {
       "id": "mapsengine.tables.features.batchPatch",
       "path": "tables/{id}/features/batchPatch",
       "httpMethod": "POST",
       "description": "Update the supplied features.\n\nA single batchPatch request can update:\n\n- Up to 50 features.\n- A combined total of 10 000 vertices.\nFeature limits are documented in the Supported data formats and limits article of the Google Maps Engine help center. Note that free and paid accounts have different limits.\n\nFeature updates use HTTP PATCH semantics:\n\n- A supplied value replaces an existing value (if any) in that field.\n- Omitted fields remain unchanged.\n- Complex [...]",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ]
      },
      "get": {
       "id": "mapsengine.tables.features.get",
       "path": "tables/{tableId}/features/{id}",
       "httpMethod": "GET",
       "description": "Return a single feature, given its ID.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      },
      "list": {
       "id": "mapsengine.tables.features.list",
       "path": "tables/{id}/features",
       "httpMethod": "GET",
       "description": "Return all features readable by the current user.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    },
    "files": {
     "methods": {
      "insert": {
       "id": "mapsengine.tables.files.insert",
       "path": "tables/{id}/files",
       "httpMethod": "POST",
       "description": "Upload a file to a placeholder table asset. See Table Upload in the Developer's Guide for more information.\nSupported file types are listed in the Supported data formats and limits article of the Google Maps Engine help center.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "parents": {
     "methods": {
      "list": {
       "id": "mapsengine.tables.parents.list",
       "path": "tables/{id}/parents",
       "httpMethod": "GET",
       "description": "Return all parent ids of the specified table.",
       "scopes": [
        "https://www.googleapis.com/auth/mapsengine",
        "https://www.googleapis.com/auth/mapsengine.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
