{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Insert mail into your mailbox"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "Manage mailbox labels"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "View and modify but not delete your email"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "Manage your basic mail settings"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        }
      }
    }
  },
  "basePath": "/gmail/v1/users/",
  "baseUrl": "https://www.googleapis.com/gmail/v1/users/",
  "batchPath": "batch/gmail/v1",
  "description": "Access Gmail mailboxes including sending user email.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/g3bzeMMQiCUwx2f62jBl-yFDoB8\"",
  "id": "gmail:v1",
  "kind": "discovery#restDescription",
  "name": "gmail",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "users": {
      "methods": {
        "getProfile": {
          "description": "Gets the current user's Gmail profile.",
          "httpMethod": "GET",
          "id": "gmail.users.getProfile",
          "path": "{userId}/profile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "stop": {
          "description": "Stop receiving push notifications for the given user mailbox.",
          "httpMethod": "POST",
          "id": "gmail.users.stop",
          "path": "{userId}/stop",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "watch": {
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "path": "{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        }
      },
      "resources": {
        "drafts": {
          "methods": {
            "create": {
              "description": "Creates a new draft with the DRAFT label.",
              "httpMethod": "POST",
              "id": "gmail.users.drafts.create",
              "path": "{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "httpMethod": "DELETE",
              "id": "gmail.users.drafts.delete",
              "path": "{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "description": "Gets the specified draft.",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.get",
              "path": "{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "description": "Lists the drafts in the user's mailbox.",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.list",
              "path": "{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "send": {
              "description": "Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers.",
              "httpMethod": "POST",
              "id": "gmail.users.drafts.send",
              "path": "{userId}/drafts/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "update": {
              "description": "Replaces a draft's content.",
              "httpMethod": "PUT",
              "id": "gmail.users.drafts.update",
              "path": "{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing historyId).",
              "httpMethod": "GET",
              "id": "gmail.users.history.list",
              "path": "{userId}/history",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "labels": {
          "methods": {
            "create": {
              "description": "Creates a new label.",
              "httpMethod": "POST",
              "id": "gmail.users.labels.create",
              "path": "{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "httpMethod": "DELETE",
              "id": "gmail.users.labels.delete",
              "path": "{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "description": "Gets the specified label.",
              "httpMethod": "GET",
              "id": "gmail.users.labels.get",
              "path": "{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "description": "Lists all labels in the user's mailbox.",
              "httpMethod": "GET",
              "id": "gmail.users.labels.list",
              "path": "{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "patch": {
              "description": "Updates the specified label. This method supports patch semantics.",
              "httpMethod": "PATCH",
              "id": "gmail.users.labels.patch",
              "path": "{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "update": {
              "description": "Updates the specified label.",
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "path": "{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          }
        },
        "messages": {
          "methods": {
            "batchDelete": {
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchDelete",
              "path": "{userId}/messages/batchDelete",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "batchModify": {
              "description": "Modifies the labels on the specified messages.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchModify",
              "path": "{userId}/messages/batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer messages.trash instead.",
              "httpMethod": "DELETE",
              "id": "gmail.users.messages.delete",
              "path": "{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "get": {
              "description": "Gets the specified message.",
              "httpMethod": "GET",
              "id": "gmail.users.messages.get",
              "path": "{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "import": {
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.import",
              "path": "{userId}/messages/import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "insert": {
              "description": "Directly inserts a message into only this user's mailbox similar to IMAP APPEND, bypassing most scanning and classification. Does not send a message.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.insert",
              "path": "{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "list": {
              "description": "Lists the messages in the user's mailbox.",
              "httpMethod": "GET",
              "id": "gmail.users.messages.list",
              "path": "{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "description": "Modifies the labels on the specified message.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.modify",
              "path": "{userId}/messages/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "send": {
              "description": "Sends the specified message to the recipients in the To, Cc, and Bcc headers.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.send",
              "path": "{userId}/messages/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "supportsMediaUpload": true
            },
            "trash": {
              "description": "Moves the specified message to the trash.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.trash",
              "path": "{userId}/messages/{id}/trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "untrash": {
              "description": "Removes the specified message from the trash.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.untrash",
              "path": "{userId}/messages/{id}/untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "httpMethod": "GET",
                  "id": "gmail.users.messages.attachments.get",
                  "path": "{userId}/messages/{messageId}/attachments/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ]
                }
              }
            }
          }
        },
        "settings": {
          "methods": {
            "getAutoForwarding": {
              "description": "Gets the auto-forwarding setting for the specified account.",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getAutoForwarding",
              "path": "{userId}/settings/autoForwarding",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getImap": {
              "description": "Gets IMAP settings.",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getImap",
              "path": "{userId}/settings/imap",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getLanguage": {
              "description": "Gets language settings.",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getLanguage",
              "path": "{userId}/settings/language",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getPop": {
              "description": "Gets POP settings.",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getPop",
              "path": "{userId}/settings/pop",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getVacation": {
              "description": "Gets vacation responder settings.",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getVacation",
              "path": "{userId}/settings/vacation",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateAutoForwarding": {
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateAutoForwarding",
              "path": "{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ]
            },
            "updateImap": {
              "description": "Updates IMAP settings.",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateImap",
              "path": "{userId}/settings/imap",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateLanguage": {
              "description": "Updates language settings.\n\nIf successful, the return object contains the displayLanguage that was saved for the user, which may differ from the value passed into the request. This is because the requested displayLanguage may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateLanguage",
              "path": "{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updatePop": {
              "description": "Updates POP settings.",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updatePop",
              "path": "{userId}/settings/pop",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateVacation": {
              "description": "Updates vacation responder settings.",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateVacation",
              "path": "{userId}/settings/vacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            }
          },
          "resources": {
            "delegates": {
              "methods": {
                "create": {
                  "description": "Adds a delegate with its verification status set directly to accepted, without sending any verification email. The delegate user must be a member of the same G Suite organization as the delegator user.\n\nGmail imposes limitations on the number of delegates and delegators each user in a G Suite organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators.\n\nNote that a delegate use[...]",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.delegates.create",
                  "path": "{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it.\n\nNote that a delegate user must be referred to by their primary email address, and not an email alias.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.delegates.delete",
                  "path": "{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "description": "Gets the specified delegate.\n\nNote that a delegate user must be referred to by their primary email address, and not an email alias.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.get",
                  "path": "{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the delegates for the specified account.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.list",
                  "path": "{userId}/settings/delegates",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "filters": {
              "methods": {
                "create": {
                  "description": "Creates a filter.",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.filters.create",
                  "path": "{userId}/settings/filters",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "delete": {
                  "description": "Deletes a filter.",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.filters.delete",
                  "path": "{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "description": "Gets a filter.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.get",
                  "path": "{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the message filters of a Gmail user.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.list",
                  "path": "{userId}/settings/filters",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "create": {
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to pending; otherwise, the resource will be created with verification status set to accepted.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "path": "{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "path": "{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "description": "Gets the specified forwarding address.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "path": "{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the forwarding addresses for the specified account.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "path": "{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "sendAs": {
              "methods": {
                "create": {
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to pending; otherwise, the resource will be created with verification status set to accepted. If a signature is provided, Gmail will sanitize[...]",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.create",
                  "path": "{userId}/settings/sendAs",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.sendAs.delete",
                  "path": "{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.get",
                  "path": "{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.list",
                  "path": "{userId}/settings/sendAs",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "patch": {
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias.\n\nAddresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority. This method supports patch semantics.",
                  "httpMethod": "PATCH",
                  "id": "gmail.users.settings.sendAs.patch",
                  "path": "{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "update": {
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias.\n\nAddresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "PUT",
                  "id": "gmail.users.settings.sendAs.update",
                  "path": "{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "verify": {
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be pending.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.verify",
                  "path": "{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                }
              },
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "delete": {
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "get": {
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "insert": {
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "list": {
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "setDefault": {
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "threads": {
          "methods": {
            "delete": {
              "description": "Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.",
              "httpMethod": "DELETE",
              "id": "gmail.users.threads.delete",
              "path": "{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "get": {
              "description": "Gets the specified thread.",
              "httpMethod": "GET",
              "id": "gmail.users.threads.get",
              "path": "{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "description": "Lists the threads in the user's mailbox.",
              "httpMethod": "GET",
              "id": "gmail.users.threads.list",
              "path": "{userId}/threads",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "httpMethod": "POST",
              "id": "gmail.users.threads.modify",
              "path": "{userId}/threads/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "trash": {
              "description": "Moves the specified thread to the trash.",
              "httpMethod": "POST",
              "id": "gmail.users.threads.trash",
              "path": "{userId}/threads/{id}/trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "untrash": {
              "description": "Removes the specified thread from the trash.",
              "httpMethod": "POST",
              "id": "gmail.users.threads.untrash",
              "path": "{userId}/threads/{id}/untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20200203",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "gmail/v1/users/",
  "title": "Gmail API",
  "version": "v1"
}