load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
        "env_parse.go",
        "env_resolve.go",
    ],
    importpath = "k8s.io/kubernetes/pkg/kubectl/cmd/util/env",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api/v1/resource:go_default_library",
        "//pkg/fieldpath:go_default_library",
        "//vendor/k8s.io/api/core/v1:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/runtime:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/util/sets:go_default_library",
        "//vendor/k8s.io/client-go/kubernetes:go_default_library",
    ],
)

filegroup(
    name = "package-srcs",
    srcs = glob(["**"]),
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)

filegroup(
    name = "all-srcs",
    srcs = [":package-srcs"],
    tags = ["automanaged"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["env_parse_test.go"],
    importpath = "k8s.io/kubernetes/pkg/kubectl/cmd/util/env",
    library = ":go_default_library",
)
