.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubectl config set\-credentials \- Sets a user entry in kubeconfig


.SH SYNOPSIS
.PP
\fBkubectl config set\-credentials\fP [OPTIONS]


.SH DESCRIPTION
.PP
Sets a user entry in kubeconfig
Specifying a name that already exists will merge new fields on top of existing values.

.PP
Client\-certificate flags:
    \-\-client\-certificate=certfile \-\-client\-key=keyfile

.PP
Bearer token flags:
    \-\-token=bearer\_token

.PP
Basic auth flags:
    \-\-username=basic\_user \-\-password=basic\_password

.PP
Bearer token and basic auth are mutually exclusive.


.SH OPTIONS
.PP
\fB\-\-client\-certificate\fP=""
    path to client\-certificate file for the user entry in kubeconfig

.PP
\fB\-\-client\-key\fP=""
    path to client\-key file for the user entry in kubeconfig

.PP
\fB\-\-embed\-certs\fP=false
    embed client cert/key for the user entry in kubeconfig

.PP
\fB\-\-password\fP=""
    password for the user entry in kubeconfig

.PP
\fB\-\-token\fP=""
    token for the user entry in kubeconfig

.PP
\fB\-\-username\fP=""
    username for the user entry in kubeconfig


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-alsologtostderr\fP=false
    log to standard error as well as files

.PP
\fB\-\-api\-version\fP=""
    DEPRECATED: The API version to use when talking to the server

.PP
\fB\-\-certificate\-authority\fP=""
    Path to a cert. file for the certificate authority.

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.

.PP
\fB\-\-kubeconfig\fP=""
    use a particular kubeconfig file

.PP
\fB\-\-log\-backtrace\-at\fP=:0
    when logging hits line file:N, emit a stack trace

.PP
\fB\-\-log\-dir\fP=""
    If non\-empty, write log files in this directory

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-logtostderr\fP=true
    log to standard error instead of files

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request.

.PP
\fB\-s\fP, \fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-stderrthreshold\fP=2
    logs at or above this threshold go to stderr

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use

.PP
\fB\-\-v\fP=0
    log level for V logs

.PP
\fB\-\-vmodule\fP=
    comma\-separated list of pattern=N settings for file\-filtered logging


.SH EXAMPLE
.PP
.RS

.nf
# Set only the "client\-key" field on the "cluster\-admin"
# entry, without touching other values:
kubectl config set\-credentials cluster\-admin \-\-client\-key=\~/.kube/admin.key

# Set basic auth for the "cluster\-admin" entry
kubectl config set\-credentials cluster\-admin \-\-username=admin \-\-password=uXFGweU9l35qcif

# Embed client certificate data in the "cluster\-admin" entry
kubectl config set\-credentials cluster\-admin \-\-client\-certificate=\~/.kube/admin.crt \-\-embed\-certs=true

.fi
.RE


.SH SEE ALSO
.PP
\fBkubectl\-config(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
