.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm alpha phase kubeconfig kubelet \- Generate a kubeconfig file for the Kubelet to use. Please note that this should \fIonly\fP be used for bootstrapping purposes! After your control plane is up, you should request all kubelet credentials from the CSR API.


.SH SYNOPSIS
.PP
\fBkubeadm alpha phase kubeconfig kubelet\fP [OPTIONS]


.SH DESCRIPTION
.PP
Generate a kubeconfig file for the Kubelet to use. Please note that this should \fIonly\fP be used for bootstrapping purposes! After your control plane is up, you should request all kubelet credentials from the CSR API.


.SH OPTIONS
.PP
\fB\-\-apiserver\-advertise\-address\fP=""
    The IP address or DNS name the API Server is accessible on.

.PP
\fB\-\-apiserver\-bind\-port\fP=6443
    The port the API Server is accessible on.

.PP
\fB\-\-cert\-dir\fP="/etc/kubernetes/pki"
    The path where certificates are stored.

.PP
\fB\-\-config\fP=""
    Path to kubeadm config file. WARNING: Usage of a configuration file is experimental!

.PP
\fB\-\-kubeconfig\-dir\fP="/etc/kubernetes"
    The path where to save and store the kubeconfig file.

.PP
\fB\-\-node\-name\fP=""
    The node name that the kubelet client cert should use.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file container Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-phase\-kubeconfig(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
