.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubectl delete \- Delete resources by filenames, stdin, resources and names, or by resources and label selector.


.SH SYNOPSIS
.PP
\fBkubectl delete\fP [OPTIONS]


.SH DESCRIPTION
.PP
Delete resources by filenames, stdin, resources and names, or by resources and label selector.

.PP
JSON and YAML formats are accepted.

.PP
Only one type of the arguments may be specified: filenames, resources and names, or resources and label selector

.PP
Note that the delete command does NOT do resource version checks, so if someone
submits an update to a resource right when you submit a delete, their update
will be lost along with the rest of the resource.


.SH OPTIONS
.PP
\fB\-\-all\fP=false
    [\-all] to select all the specified resources.

.PP
\fB\-\-cascade\fP=true
    If true, cascade the deletion of the resources managed by this resource (e.g. Pods created by a ReplicationController).  Default true.

.PP
\fB\-f\fP, \fB\-\-filename\fP=[]
    Filename, directory, or URL to a file containing the resource to delete.

.PP
\fB\-\-grace\-period\fP=\-1
    Period of time in seconds given to the resource to terminate gracefully. Ignored if negative.

.PP
\fB\-\-ignore\-not\-found\fP=false
    Treat "resource not found" as a successful delete. Defaults to "true" when \-\-all is specified.

.PP
\fB\-o\fP, \fB\-\-output\fP=""
    Output mode. Use "\-o name" for shorter output (resource/name).

.PP
\fB\-l\fP, \fB\-\-selector\fP=""
    Selector (label query) to filter on.

.PP
\fB\-\-timeout\fP=0
    The length of time to wait before giving up on a delete, zero means determine a timeout from the size of the object


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-alsologtostderr\fP=false
    log to standard error as well as files

.PP
\fB\-\-api\-version\fP=""
    The API version to use when talking to the server

.PP
\fB\-\-certificate\-authority\fP=""
    Path to a cert. file for the certificate authority.

.PP
\fB\-\-client\-certificate\fP=""
    Path to a client key file for TLS.

.PP
\fB\-\-client\-key\fP=""
    Path to a client key file for TLS.

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.

.PP
\fB\-\-kubeconfig\fP=""
    Path to the kubeconfig file to use for CLI requests.

.PP
\fB\-\-log\-backtrace\-at\fP=:0
    when logging hits line file:N, emit a stack trace

.PP
\fB\-\-log\-dir\fP=""
    If non\-empty, write log files in this directory

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-logtostderr\fP=true
    log to standard error instead of files

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request.

.PP
\fB\-\-password\fP=""
    Password for basic authentication to the API server.

.PP
\fB\-s\fP, \fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-stderrthreshold\fP=2
    logs at or above this threshold go to stderr

.PP
\fB\-\-token\fP=""
    Bearer token for authentication to the API server.

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use

.PP
\fB\-\-username\fP=""
    Username for basic authentication to the API server.

.PP
\fB\-\-v\fP=0
    log level for V logs

.PP
\fB\-\-vmodule\fP=
    comma\-separated list of pattern=N settings for file\-filtered logging


.SH EXAMPLE
.PP
.RS

.nf
# Delete a pod using the type and name specified in pod.json.
$ kubectl delete \-f ./pod.json

# Delete a pod based on the type and name in the JSON passed into stdin.
$ cat pod.json | kubectl delete \-f \-

# Delete pods and services with same names "baz" and "foo"
$ kubectl delete pod,service baz foo

# Delete pods and services with label name=myLabel.
$ kubectl delete pods,services \-l name=myLabel

# Delete a pod with UID 1234\-56\-7890\-234234\-456456.
$ kubectl delete pod 1234\-56\-7890\-234234\-456456

# Delete all pods
$ kubectl delete pods \-\-all

.fi
.RE


.SH SEE ALSO
.PP
\fBkubectl(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
