.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm alpha phase certs apiserver \- Generate API Server serving certificate and key.


.SH SYNOPSIS
.PP
\fBkubeadm alpha phase certs apiserver\fP [OPTIONS]


.SH DESCRIPTION
.PP
Generate API Server serving certificate and key.


.SH OPTIONS
.PP
\fB\-\-apiserver\-advertise\-address\fP=""
    The IP address the API Server will advertise it is listening on. Specify '0.0.0.0' to use the address of the default network interface.

.PP
\fB\-\-apiserver\-cert\-extra\-sans\fP=[]
    Optional extra Subject Alternative Names (SANs) to use for the API Server serving certificate. Can be both IP addresses and DNS names.

.PP
\fB\-\-cert\-dir\fP="/etc/kubernetes/pki"
    The path where to save and store the certificates.

.PP
\fB\-\-config\fP=""
    Path to a kubeadm config file. WARNING: Usage of a configuration file is experimental!

.PP
\fB\-\-service\-cidr\fP="10.96.0.0/12"
    Use alternative range of IP address for service VIPs.

.PP
\fB\-\-service\-dns\-domain\fP="cluster.local"
    Use alternative domain for services, e.g. "myorg.internal".


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file container Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-phase\-certs(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
