.TH "KUBERNETES" "1" " kubernetes User Manuals" "Scott Collier" "October 2014"  ""


.SH NAME
.PP
kube\-scheduler \- Schedules containers on hosts.


.SH SYNOPSIS
.PP
\fBkube\-scheduler\fP [OPTIONS]


.SH DESCRIPTION
.PP
The \fBkubernetes\fP scheduler is a policy\-rich, topology\-aware, workload\-specific function that significantly impacts availability, performance, and capacity. The scheduler needs to take into account individual and collective resource requirements, quality of service requirements, hardware/software/policy constraints, affinity and anti\-affinity specifications, data locality, inter\-workload interference, deadlines, and so on. Workload\-specific requirements will be exposed through the API as necessary.

.PP
The kube\-scheduler can take several options.


.SH OPTIONS
.PP
\fB\-\-address=\fP"127.0.0.1"
    The address to serve from.

.PP
\fB\-\-alsologtostderr=\fPfalse
    log to standard error as well as files.

.PP
\fB\-\-api\_version=\fP""
    The API version to use when talking to the server.

.PP
\fB\-\-insecure\_skip\_tls\_verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.

.PP
\fB\-\-log\_backtrace\_at=\fP:0
    when logging hits line file:N, emit a stack trace.

.PP
\fB\-\-log\_dir=\fP""
    If non\-empty, write log files in this directory.

.PP
\fB\-\-log\_flush\_frequency\fP=5s
    Maximum number of seconds between log flushes.

.PP
\fB\-\-logtostderr\fP=false
    log to standard error instead of files.

.PP
\fB\-\-master=\fP""
    The address of the Kubernetes API server.

.PP
\fB\-\-port=\fP10251
    The port that the scheduler's http service runs on.

.PP
\fB\-\-stderrthreshold\fP=0
    logs at or above this threshold go to stderr.

.PP
\fB\-\-v\fP=0
    log level for V logs.

.PP
\fB\-\-version\fP=false
    Print version information and quit.

.PP
\fB\-\-vmodule\fP=
    comma\-separated list of pattern=N settings for file\-filtered logging.


.SH EXAMPLES
.PP
.RS

.nf
/usr/bin/kube\-scheduler \-\-logtostderr=true \-\-v=0 \-\-master=127.0.0.1:8080

.fi
.RE


.SH HISTORY
.PP
October 2014, Originally compiled by Scott Collier (scollier@redhat.com) based
 on the kubernetes source material and internal work.
