.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kube\-scheduler \- kube\-scheduler schedules pods onto nodes


.SH SYNOPSIS
.PP
\fBkube\-scheduler\fP [OPTIONS]


.SH DESCRIPTION
.PP
The Kubernetes scheduler is a policy\-rich, topology\-aware,
workload\-specific function that significantly impacts availability, performance,
and capacity. The scheduler needs to take into account individual and collective
resource requirements, quality of service requirements, hardware/software/policy
constraints, affinity and anti\-affinity specifications, data locality, inter\-workload
interference, deadlines, and so on. Workload\-specific requirements will be exposed
through the API as necessary.


.SH OPTIONS
.PP
\fB\-\-address\fP=127.0.0.1
    The IP address to serve on (set to 0.0.0.0 for all interfaces)

.PP
\fB\-\-algorithm\-provider\fP="DefaultProvider"
    The scheduling algorithm provider to use, one of: DefaultProvider

.PP
\fB\-\-alsologtostderr\fP[=false]
    log to standard error as well as files

.PP
\fB\-\-bind\-pods\-burst\fP=20
    Number of bindings per second scheduler is allowed to make during bursts

.PP
\fB\-\-bind\-pods\-qps\fP=15
    Number of bindings per second scheduler is allowed to continuously make

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for kube\-scheduler

.PP
\fB\-\-kubeconfig\fP=""
    Path to kubeconfig file with authorization and master location information.

.PP
\fB\-\-log\-backtrace\-at\fP=:0
    when logging hits line file:N, emit a stack trace

.PP
\fB\-\-log\-dir\fP=""
    If non\-empty, write log files in this directory

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-logtostderr\fP[=true]
    log to standard error instead of files

.PP
\fB\-\-master\fP=""
    The address of the Kubernetes API server (overrides any value in kubeconfig)

.PP
\fB\-\-policy\-config\-file\fP=""
    File with scheduler policy configuration

.PP
\fB\-\-port\fP=10251
    The port that the scheduler's http service runs on

.PP
\fB\-\-profiling\fP[=true]
    Enable profiling via web interface host:port/debug/pprof/

.PP
\fB\-\-stderrthreshold\fP=2
    logs at or above this threshold go to stderr

.PP
\fB\-\-v\fP=0
    log level for V logs

.PP
\fB\-\-version\fP=false
    Print version information and quit

.PP
\fB\-\-vmodule\fP=
    comma\-separated list of pattern=N settings for file\-filtered logging


.SH HISTORY
.PP
2015\-08\-21 07:23:00.707501129 +0000 UTC Auto generated by spf13/cobra
