.TH "KUBERNETES" "1" " kubernetes User Manuals" "Scott Collier" "October 2014"  ""

.SH NAME
.PP
kube\-controller\-manager \- Enforces kubernetes services.

.SH SYNOPSIS
.PP
\fBkube\-controller\-manager\fP [OPTIONS]

.SH DESCRIPTION
.PP
The \fBkubernetes\fP controller manager is really a service that is layered on top of the simple pod API. To enforce this layering, the logic for the replicationController is actually broken out into another server. This server watches etcd for changes to replicationController objects and then uses the public Kubernetes API to implement the replication algorithm.

.PP
The kube\-controller\-manager has several options.

.SH OPTIONS
.PP
\fB\-\-address\fP=""
    The address on the local server to listen to. Default 127.0.0.1.

.PP
\fB\-\-allow\_privileged\fP="false"
    If true, allow privileged containers.

.PP
\fB\-\-address=\fP"127.0.0.1"
    The address to serve from.

.PP
\fB\-\-alsologtostderr\fP=false
    log to standard error as well as files.

.PP
\fB\-\-api\_version\fP=""
    The API version to use when talking to the server.

.PP
\fB\-\-cloud\_config\fP=""
    The path to the cloud provider configuration file. Empty string for no configuration file.

.PP
\fB\-\-cloud\_provider\fP=""
    The provider for cloud services. Empty string for no provider.

.PP
\fB\-\-minion\_regexp\fP=""
    If non empty, and \-cloud\_provider is specified, a regular expression for matching minion VMs.

.PP
\fB\-\-insecure\_skip\_tls\_verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.

.PP
\fB\-\-log\_backtrace\_at\fP=:0
    when logging hits line file:N, emit a stack trace.

.PP
\fB\-\-log\_dir\fP=""
    If non\-empty, write log files in this directory.

.PP
\fB\-\-log\_flush\_frequency\fP=5s
    Maximum number of seconds between log flushes.

.PP
\fB\-\-logtostderr\fP=false
    log to standard error instead of files.

.PP
\fB\-\-machines\fP=[]
        List of machines to schedule onto, comma separated.

.PP
\fB\-\-master\fP=""
    The address of the Kubernetes API server.

.PP
\fB\-\-port\fP=10252
    The port that the controller\-manager's http service runs on.

.PP
\fB\-\-stderrthreshold\fP=0
    logs at or above this threshold go to stderr.

.PP
\fB\-\-v\fP=0
    log level for V logs.

.PP
\fB\-\-version\fP=false
    Print version information and quit.

.PP
\fB\-\-vmodule\fP=
    comma\-separated list of pattern=N settings for file\-filtered logging.

.SH EXAMPLES
.PP
.RS

.nf
/usr/bin/kube\-controller\-manager \-\-logtostderr=true \-\-v=0 \-\-master=127.0.0.1:8080

.fi

.SH HISTORY
.PP
October 2014, Originally compiled by Scott Collier (scollier at redhat dot com) based
 on the kubernetes source material and internal work.
