.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm \- kubeadm: easily bootstrap a secure Kubernetes cluster


.SH SYNOPSIS
.PP
\fBkubeadm\fP [OPTIONS]


.SH DESCRIPTION
.PP
kubeadm: easily bootstrap a secure Kubernetes cluster.

.PP
.RS

.nf
┌──────────────────────────────────────────────────────────┐
│ KUBEADM IS CURRENTLY IN BETA                             │
│                                                          │
│ But please, try it out and give us feedback at:          │
│ https://github.com/kubernetes/kubeadm/issues             │
│ and at\-mention @kubernetes/sig\-cluster\-lifecycle\-bugs    │
│ or @kubernetes/sig\-cluster\-lifecycle\-feature\-requests    │
└──────────────────────────────────────────────────────────┘

.fi
.RE

.PP
Example usage:

.PP
.RS

.nf
Create a two\-machine cluster with one master (which controls the cluster),
and one node (where your workloads, like Pods and Deployments run).

┌──────────────────────────────────────────────────────────┐
│ On the first machine:                                    │
├──────────────────────────────────────────────────────────┤
│ master# kubeadm init                                     │
└──────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────┐
│ On the second machine:                                   │
├──────────────────────────────────────────────────────────┤
│ node# kubeadm join <arguments\-returned\-from\-init>        │
└──────────────────────────────────────────────────────────┘

You can then repeat the second step on as many other machines as you like.

.fi
.RE


.SH OPTIONS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file container Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH SEE ALSO
.PP
\fBkubeadm\-alpha(1)\fP, \fBkubeadm\-completion(1)\fP, \fBkubeadm\-config(1)\fP, \fBkubeadm\-init(1)\fP, \fBkubeadm\-join(1)\fP, \fBkubeadm\-reset(1)\fP, \fBkubeadm\-token(1)\fP, \fBkubeadm\-upgrade(1)\fP, \fBkubeadm\-version(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
