.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kube\-proxy \-


.SH SYNOPSIS
.PP
\fBkube\-proxy\fP [OPTIONS]


.SH DESCRIPTION
.PP
The Kubernetes network proxy runs on each node. This
reflects services as defined in the Kubernetes API on each node and can do simple
TCP,UDP stream forwarding or round robin TCP,UDP forwarding across a set of backends.
Service cluster ips and ports are currently found through Docker\-links\-compatible
environment variables specifying ports opened by the service proxy. There is an optional
addon that provides cluster DNS for these cluster IPs. The user must create a service
with the apiserver API to configure the proxy.


.SH OPTIONS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file container Azure container registry configuration information.

.PP
\fB\-\-bind\-address\fP=0.0.0.0
    The IP address for the proxy server to serve on (set to 0.0.0.0 for all interfaces)

.PP
\fB\-\-cleanup\-iptables\fP=false
    If true cleanup iptables rules and exit.

.PP
\fB\-\-cluster\-cidr\fP=""
    The CIDR range of pods in the cluster. It is used to bridge traffic coming from outside of the cluster. If not provided, no off\-cluster bridging will be performed.

.PP
\fB\-\-config\-sync\-period\fP=15m0s
    How often configuration from the apiserver is refreshed.  Must be greater than 0.

.PP
\fB\-\-conntrack\-max\fP=0
    Maximum number of NAT connections to track (0 to leave as\-is). This overrides conntrack\-max\-per\-core and conntrack\-min.

.PP
\fB\-\-conntrack\-max\-per\-core\fP=32768
    Maximum number of NAT connections to track per CPU core (0 to leave the limit as\-is and ignore conntrack\-min).

.PP
\fB\-\-conntrack\-min\fP=131072
    Minimum number of conntrack entries to allocate, regardless of conntrack\-max\-per\-core (set conntrack\-max\-per\-core=0 to leave the limit as\-is).

.PP
\fB\-\-conntrack\-tcp\-timeout\-close\-wait\fP=1h0m0s
    NAT timeout for TCP connections in the CLOSE\_WAIT state

.PP
\fB\-\-conntrack\-tcp\-timeout\-established\fP=24h0m0s
    Idle timeout for established TCP connections (0 to leave as\-is)

.PP
\fB\-\-feature\-gates\fP=
    A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
AffinityInAnnotations=true|false (ALPHA \- default=false)
AllAlpha=true|false (ALPHA \- default=false)
AllowExtTrafficLocalEndpoints=true|false (BETA \- default=true)
AppArmor=true|false (BETA \- default=true)
DynamicKubeletConfig=true|false (ALPHA \- default=false)
DynamicVolumeProvisioning=true|false (ALPHA \- default=true)
ExperimentalCriticalPodAnnotation=true|false (ALPHA \- default=false)
ExperimentalHostUserNamespaceDefaulting=true|false (BETA \- default=false)
StreamingProxyRedirects=true|false (BETA \- default=true)

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-healthz\-bind\-address\fP=127.0.0.1
    The IP address for the health check server to serve on, defaulting to 127.0.0.1 (set to 0.0.0.0 for all interfaces)

.PP
\fB\-\-healthz\-port\fP=10249
    The port to bind the health check server. Use 0 to disable.

.PP
\fB\-\-hostname\-override\fP=""
    If non\-empty, will use this string as identification instead of the actual hostname.

.PP
\fB\-\-iptables\-masquerade\-bit\fP=14
    If using the pure iptables proxy, the bit of the fwmark space to mark packets requiring SNAT with.  Must be within the range [0, 31].

.PP
\fB\-\-iptables\-min\-sync\-period\fP=0s
    The minimum interval of how often the iptables rules can be refreshed as endpoints and services change (e.g. '5s', '1m', '2h22m').

.PP
\fB\-\-iptables\-sync\-period\fP=30s
    The maximum interval of how often iptables rules are refreshed (e.g. '5s', '1m', '2h22m').  Must be greater than 0.

.PP
\fB\-\-kube\-api\-burst\fP=10
    Burst to use while talking with kubernetes apiserver

.PP
\fB\-\-kube\-api\-content\-type\fP="application/vnd.kubernetes.protobuf"
    Content type of requests sent to apiserver.

.PP
\fB\-\-kube\-api\-qps\fP=5
    QPS to use while talking with kubernetes apiserver

.PP
\fB\-\-kubeconfig\fP=""
    Path to kubeconfig file with authorization information (the master location is set by the master flag).

.PP
\fB\-\-masquerade\-all\fP=false
    If using the pure iptables proxy, SNAT everything

.PP
\fB\-\-master\fP=""
    The address of the Kubernetes API server (overrides any value in kubeconfig)

.PP
\fB\-\-oom\-score\-adj\fP=\-999
    The oom\-score\-adj value for kube\-proxy process. Values must be within the range [\-1000, 1000]

.PP
\fB\-\-proxy\-mode\fP=
    Which proxy mode to use: 'userspace' (older) or 'iptables' (faster). If blank, use the best\-available proxy (currently iptables).  If the iptables proxy is selected, regardless of how, but the system's kernel or iptables versions are insufficient, this always falls back to the userspace proxy.

.PP
\fB\-\-proxy\-port\-range\fP=
    Range of host ports (beginPort\-endPort, inclusive) that may be consumed in order to proxy service traffic. If unspecified (0\-0) then ports will be randomly chosen.

.PP
\fB\-\-resource\-container\fP=""
    Absolute name of the resource\-only container to create and run the Kube\-proxy in (Default: /kube\-proxy).

.PP
\fB\-\-udp\-timeout\fP=250ms
    How long an idle UDP connection will be kept open (e.g. '250ms', '2s').  Must be greater than 0. Only applicable for proxy\-mode=userspace


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
