.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm alpha phase mark\-master \- Mark a node as master


.SH SYNOPSIS
.PP
\fBkubeadm alpha phase mark\-master\fP [OPTIONS]


.SH DESCRIPTION
.PP
Applies a label that specifies that a node is a master and a taint that forces workloads to be deployed accordingly.

.PP
Alpha Disclaimer: this command is currently alpha.


.SH OPTIONS
.PP
\fB\-\-config\fP=""
    Path to kubeadm config file (WARNING: Usage of a configuration file is experimental)

.PP
\fB\-\-kubeconfig\fP="/etc/kubernetes/admin.conf"
    The KubeConfig file to use when talking to the cluster

.PP
\fB\-\-node\-name\fP=""
    The node name to which label and taints should apply


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file container Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH EXAMPLE
.PP
.RS

.nf
  # Applies master label and taint to the current node, functionally equivalent to what executed by kubeadm init.
  kubeadm alpha phase mark\-master
  
  # Applies master label and taint to a specific node
  kubeadm alpha phase mark\-master \-\-node\-name myNode

.fi
.RE


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-phase(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
