.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubectl config set\-credentials \- Sets a user entry in .kubeconfig


.SH SYNOPSIS
.PP
\fBkubectl config set\-credentials\fP [OPTIONS]


.SH DESCRIPTION
.PP
Sets a user entry in .kubeconfig

.PP
Specifying a name that already exists will merge new fields on top of existing
  values. For example, the following only sets the "client\-key" field on the
  "cluster\-admin" entry, without touching other values:

.PP
.RS

.nf
set\-credentials cluster\-admin \-\-client\-key=\~/.kube/admin.key

.fi
.RE

.PP
Client\-certificate flags:
    \-\-client\-certificate=certfile \-\-client\-key=keyfile

.PP
Bearer token flags:
    \-\-token=bearer\_token

.PP
Basic auth flags:
    \-\-username=basic\_user \-\-password=basic\_password

.PP
Bearer token and basic auth are mutually exclusive.


.SH OPTIONS
.PP
\fB\-\-auth\-path\fP=""
    auth\-path for the user entry in .kubeconfig

.PP
\fB\-\-client\-certificate\fP=""
    client\-certificate for the user entry in .kubeconfig

.PP
\fB\-\-client\-key\fP=""
    client\-key for the user entry in .kubeconfig

.PP
\fB\-\-password\fP=""
    password for the user entry in .kubeconfig

.PP
\fB\-\-token\fP=""
    token for the user entry in .kubeconfig

.PP
\fB\-\-username\fP=""
    username for the user entry in .kubeconfig


.SH SEE ALSO
.PP
\fBkubectl\-config(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
