.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm alpha phase certs apiserver \- Generates API server serving certificate and key


.SH SYNOPSIS
.PP
\fBkubeadm alpha phase certs apiserver\fP [OPTIONS]


.SH DESCRIPTION
.PP
Generates the API server serving certificate and key and saves them into apiserver.crt and apiserver.key files.

.PP
The certificate includes default subject alternative names and additional sans eventually provided by the user; default sans are: <node-name>, <apiserver-advertise-address>, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc. <service-dns-domain>, <internalAPIServerVirtualIP>(that is the .10 address in <service-cidr>address space).

.PP
If both files already exist, kubeadm skips the generation step and existing files will be used.

.PP
Alpha Disclaimer: this command is currently alpha.


.SH OPTIONS
.PP
\fB\-\-apiserver\-advertise\-address\fP=""
    The IP address the API server is accessible on, to use for the API server serving cert

.PP
\fB\-\-apiserver\-cert\-extra\-sans\fP=[]
    Optional extra altnames to use for the API server serving cert. Can be both IP addresses and dns names

.PP
\fB\-\-cert\-dir\fP="/etc/kubernetes/pki"
    The path where to save the certificates

.PP
\fB\-\-config\fP=""
    Path to kubeadm config file (WARNING: Usage of a configuration file is experimental)

.PP
\fB\-\-service\-cidr\fP="10.96.0.0/12"
    Alternative range of IP address for service VIPs, from which derives the internal API server VIP that will be added to the API Server serving cert

.PP
\fB\-\-service\-dns\-domain\fP="cluster.local"
    Alternative domain for services, to use for the API server serving cert


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file container Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-phase\-certs(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
