{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/xiMdcGrwm4vNaftUqbcmg_X46_0\"",
 "discoveryVersion": "v1",
 "id": "orkut:v2",
 "name": "orkut",
 "version": "v2",
 "title": "Orkut API",
 "description": "Lets you manage activities, comments and badges in Orkut. More stuff coming in time.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "http://code.google.com/apis/orkut/v2/reference.html",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/orkut/v2/",
 "basePath": "/orkut/v2/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "orkut/v2/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/orkut": {
     "description": "Manage your Orkut activity"
    },
    "https://www.googleapis.com/auth/orkut.readonly": {
     "description": "View your Orkut data"
    }
   }
  }
 },
 "resources": {
  "acl": {
   "methods": {
    "delete": {
     "id": "orkut.acl.delete",
     "path": "activities/{activityId}/acl/{userId}",
     "httpMethod": "DELETE",
     "description": "Excludes an element from the ACL of the activity.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    }
   }
  },
  "activities": {
   "methods": {
    "delete": {
     "id": "orkut.activities.delete",
     "path": "activities/{activityId}",
     "httpMethod": "DELETE",
     "description": "Deletes an existing activity, if the access controls allow it.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "list": {
     "id": "orkut.activities.list",
     "path": "people/{userId}/activities/{collection}",
     "httpMethod": "GET",
     "description": "Retrieves a list of activities.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "activityVisibility": {
   "methods": {
    "get": {
     "id": "orkut.activityVisibility.get",
     "path": "activities/{activityId}/visibility",
     "httpMethod": "GET",
     "description": "Gets the visibility of an existing activity.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "patch": {
     "id": "orkut.activityVisibility.patch",
     "path": "activities/{activityId}/visibility",
     "httpMethod": "PATCH",
     "description": "Updates the visibility of an existing activity. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "update": {
     "id": "orkut.activityVisibility.update",
     "path": "activities/{activityId}/visibility",
     "httpMethod": "PUT",
     "description": "Updates the visibility of an existing activity.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    }
   }
  },
  "badges": {
   "methods": {
    "get": {
     "id": "orkut.badges.get",
     "path": "people/{userId}/badges/{badgeId}",
     "httpMethod": "GET",
     "description": "Retrieves a badge from a user.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "list": {
     "id": "orkut.badges.list",
     "path": "people/{userId}/badges",
     "httpMethod": "GET",
     "description": "Retrieves the list of visible badges of a user.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "comments": {
   "methods": {
    "delete": {
     "id": "orkut.comments.delete",
     "path": "comments/{commentId}",
     "httpMethod": "DELETE",
     "description": "Deletes an existing comment.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "get": {
     "id": "orkut.comments.get",
     "path": "comments/{commentId}",
     "httpMethod": "GET",
     "description": "Retrieves an existing comment.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "insert": {
     "id": "orkut.comments.insert",
     "path": "activities/{activityId}/comments",
     "httpMethod": "POST",
     "description": "Inserts a new comment to an activity.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "list": {
     "id": "orkut.comments.list",
     "path": "activities/{activityId}/comments",
     "httpMethod": "GET",
     "description": "Retrieves a list of comments, possibly filtered.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communities": {
   "methods": {
    "get": {
     "id": "orkut.communities.get",
     "path": "communities/{communityId}",
     "httpMethod": "GET",
     "description": "Retrieves the basic information (aka. profile) of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "list": {
     "id": "orkut.communities.list",
     "path": "people/{userId}/communities",
     "httpMethod": "GET",
     "description": "Retrieves the list of communities the current user is a member of.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communityFollow": {
   "methods": {
    "delete": {
     "id": "orkut.communityFollow.delete",
     "path": "communities/{communityId}/followers/{userId}",
     "httpMethod": "DELETE",
     "description": "Removes a user from the followers of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "insert": {
     "id": "orkut.communityFollow.insert",
     "path": "communities/{communityId}/followers/{userId}",
     "httpMethod": "POST",
     "description": "Adds a user as a follower of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    }
   }
  },
  "communityMembers": {
   "methods": {
    "delete": {
     "id": "orkut.communityMembers.delete",
     "path": "communities/{communityId}/members/{userId}",
     "httpMethod": "DELETE",
     "description": "Makes the user leave a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "get": {
     "id": "orkut.communityMembers.get",
     "path": "communities/{communityId}/members/{userId}",
     "httpMethod": "GET",
     "description": "Retrieves the relationship between a user and a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "insert": {
     "id": "orkut.communityMembers.insert",
     "path": "communities/{communityId}/members/{userId}",
     "httpMethod": "POST",
     "description": "Makes the user join a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "list": {
     "id": "orkut.communityMembers.list",
     "path": "communities/{communityId}/members",
     "httpMethod": "GET",
     "description": "Lists members of a community. Use the pagination tokens to retrieve the full list; do not rely on the member count available in the community profile information to know when to stop iterating, as that count may be approximate.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communityMessages": {
   "methods": {
    "delete": {
     "id": "orkut.communityMessages.delete",
     "path": "communities/{communityId}/topics/{topicId}/messages/{messageId}",
     "httpMethod": "DELETE",
     "description": "Moves a message of the community to the trash folder.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "insert": {
     "id": "orkut.communityMessages.insert",
     "path": "communities/{communityId}/topics/{topicId}/messages",
     "httpMethod": "POST",
     "description": "Adds a message to a given community topic.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "list": {
     "id": "orkut.communityMessages.list",
     "path": "communities/{communityId}/topics/{topicId}/messages",
     "httpMethod": "GET",
     "description": "Retrieves the messages of a topic of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communityPollComments": {
   "methods": {
    "insert": {
     "id": "orkut.communityPollComments.insert",
     "path": "communities/{communityId}/polls/{pollId}/comments",
     "httpMethod": "POST",
     "description": "Adds a comment on a community poll.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "list": {
     "id": "orkut.communityPollComments.list",
     "path": "communities/{communityId}/polls/{pollId}/comments",
     "httpMethod": "GET",
     "description": "Retrieves the comments of a community poll.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communityPollVotes": {
   "methods": {
    "insert": {
     "id": "orkut.communityPollVotes.insert",
     "path": "communities/{communityId}/polls/{pollId}/votes",
     "httpMethod": "POST",
     "description": "Votes on a community poll.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    }
   }
  },
  "communityPolls": {
   "methods": {
    "get": {
     "id": "orkut.communityPolls.get",
     "path": "communities/{communityId}/polls/{pollId}",
     "httpMethod": "GET",
     "description": "Retrieves one specific poll of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "list": {
     "id": "orkut.communityPolls.list",
     "path": "communities/{communityId}/polls",
     "httpMethod": "GET",
     "description": "Retrieves the polls of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communityRelated": {
   "methods": {
    "list": {
     "id": "orkut.communityRelated.list",
     "path": "communities/{communityId}/related",
     "httpMethod": "GET",
     "description": "Retrieves the communities related to another one.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "communityTopics": {
   "methods": {
    "delete": {
     "id": "orkut.communityTopics.delete",
     "path": "communities/{communityId}/topics/{topicId}",
     "httpMethod": "DELETE",
     "description": "Moves a topic of the community to the trash folder.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "get": {
     "id": "orkut.communityTopics.get",
     "path": "communities/{communityId}/topics/{topicId}",
     "httpMethod": "GET",
     "description": "Retrieves a topic of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    },
    "insert": {
     "id": "orkut.communityTopics.insert",
     "path": "communities/{communityId}/topics",
     "httpMethod": "POST",
     "description": "Adds a topic to a given community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    },
    "list": {
     "id": "orkut.communityTopics.list",
     "path": "communities/{communityId}/topics",
     "httpMethod": "GET",
     "description": "Retrieves the topics of a community.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "counters": {
   "methods": {
    "list": {
     "id": "orkut.counters.list",
     "path": "people/{userId}/counters",
     "httpMethod": "GET",
     "description": "Retrieves the counters of a user.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut",
      "https://www.googleapis.com/auth/orkut.readonly"
     ]
    }
   }
  },
  "scraps": {
   "methods": {
    "insert": {
     "id": "orkut.scraps.insert",
     "path": "activities/scraps",
     "httpMethod": "POST",
     "description": "Creates a new scrap.",
     "scopes": [
      "https://www.googleapis.com/auth/orkut"
     ]
    }
   }
  }
 }
}
