source 'https://rubygems.org'

gem 'activesupport', '6.0.3.4'
gem 'elasticsearch-xpack', '7.9.0'
gem 'fluentd', '1.11.4'
gem 'fluent-plugin-concat', '2.4.0'
gem 'fluent-plugin-detect-exceptions', '0.0.13'
gem 'fluent-plugin-elasticsearch', '4.2.2'
gem 'fluent-plugin-kubernetes_metadata_filter', '2.5.2'
gem 'fluent-plugin-multi-format-parser', '1.0.0'
gem 'fluent-plugin-prometheus', '1.8.4'
gem 'fluent-plugin-systemd', '1.0.2'
gem 'oj', '3.10.15'

