s/__PILLAR__DNS__SERVER__/VAR_DNS_SERVER_IP/g
s/__PILLAR__DNS__REPLICAS__/VAR_DNS_REPLICAS/g
s/__PILLAR__DNS__DOMAIN__/VAR_DNS_DOMAIN/g
/__PILLAR__FEDERATIONS__DOMAIN__MAP__/d
s/__MACHINE_GENERATED_WARNING__/Warning: This is a file generated from the base template file: __SOURCE_FILENAME__/g
