{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/T-KUOZ6MW3qGb2TywsMrS2SH2E4\"",
 "discoveryVersion": "v1",
 "id": "siteVerification:v1",
 "name": "siteVerification",
 "version": "v1",
 "title": "Google Site Verification API",
 "description": "Lets you programatically verify ownership of websites or domains with Google.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/site-verification/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/siteVerification/v1/",
 "basePath": "/siteVerification/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "siteVerification/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/siteverification": {
     "description": "Manage the list of sites and domains you control"
    },
    "https://www.googleapis.com/auth/siteverification.verify_only": {
     "description": "Manage your new site verifications with Google"
    }
   }
  }
 },
 "resources": {
  "webResource": {
   "methods": {
    "delete": {
     "id": "siteVerification.webResource.delete",
     "path": "webResource/{id}",
     "httpMethod": "DELETE",
     "description": "Relinquish ownership of a website or domain.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ]
    },
    "get": {
     "id": "siteVerification.webResource.get",
     "path": "webResource/{id}",
     "httpMethod": "GET",
     "description": "Get the most current data for a website or domain.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ]
    },
    "getToken": {
     "id": "siteVerification.webResource.getToken",
     "path": "token",
     "httpMethod": "POST",
     "description": "Get a verification token for placing on a website or domain.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification",
      "https://www.googleapis.com/auth/siteverification.verify_only"
     ]
    },
    "insert": {
     "id": "siteVerification.webResource.insert",
     "path": "webResource",
     "httpMethod": "POST",
     "description": "Attempt verification of a website or domain.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification",
      "https://www.googleapis.com/auth/siteverification.verify_only"
     ]
    },
    "list": {
     "id": "siteVerification.webResource.list",
     "path": "webResource",
     "httpMethod": "GET",
     "description": "Get the list of your verified websites and domains.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ]
    },
    "patch": {
     "id": "siteVerification.webResource.patch",
     "path": "webResource/{id}",
     "httpMethod": "PATCH",
     "description": "Modify the list of owners for your website or domain. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ]
    },
    "update": {
     "id": "siteVerification.webResource.update",
     "path": "webResource/{id}",
     "httpMethod": "PUT",
     "description": "Modify the list of owners for your website or domain.",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ]
    }
   }
  }
 }
}
