package(default_visibility = ["//visibility:public"])

licenses(["notice"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_binary",
    "go_library",
    "go_test",
    "cgo_library",
)

go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
        "fake_daemonset.go",
        "fake_deployment.go",
        "fake_deployment_expansion.go",
        "fake_extensions_client.go",
        "fake_ingress.go",
        "fake_job.go",
        "fake_podsecuritypolicy.go",
        "fake_replicaset.go",
        "fake_scale.go",
        "fake_scale_expansion.go",
        "fake_thirdpartyresource.go",
    ],
    tags = ["automanaged"],
)
