{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        }
      }
    }
  },
  "basePath": "/youtube/analytics/v1beta1/",
  "baseUrl": "https://www.googleapis.com/youtube/analytics/v1beta1/",
  "batchPath": "batch/youtubeAnalytics/v1beta1",
  "canonicalName": "YouTube Analytics",
  "description": "Retrieves your YouTube Analytics data.",
  "discoveryVersion": "v1",
  "documentationLink": "http://developers.google.com/youtube/analytics/",
  "etag": "\"Zkyw9ACJZUvcYmlFaKGChzhmtnE/1EQIGwwL3SKNyvnAKOnN_kA5s_Y\"",
  "id": "youtubeAnalytics:v1beta1",
  "kind": "discovery#restDescription",
  "labels": [
    "deprecated"
  ],
  "name": "youtubeAnalytics",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "groupItems": {
      "methods": {
        "delete": {
          "description": "Removes an item from a group.",
          "httpMethod": "DELETE",
          "id": "youtubeAnalytics.groupItems.delete",
          "path": "groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Creates a group item.",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groupItems.insert",
          "path": "groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Returns a collection of group items that match the API request parameters.",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groupItems.list",
          "path": "groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    },
    "groups": {
      "methods": {
        "delete": {
          "description": "Deletes a group.",
          "httpMethod": "DELETE",
          "id": "youtubeAnalytics.groups.delete",
          "path": "groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Creates a group.",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groups.insert",
          "path": "groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groups.list",
          "path": "groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "update": {
          "description": "Modifies a group. For example, you could change a group's title.",
          "httpMethod": "PUT",
          "id": "youtubeAnalytics.groups.update",
          "path": "groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "description": "Retrieve your YouTube Analytics reports.",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.reports.query",
          "path": "reports",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "revision": "20180430",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "youtube/analytics/v1beta1/",
  "title": "YouTube Analytics API",
  "version": "v1beta1"
}