{
 "kind": "discovery#restDescription",
 "etag": "\"kEk3sFj6Ef5_yR1-H3bAO6qw9mI/lCOFlgVtGlgupSVNF85eEEfwphE\"",
 "discoveryVersion": "v1",
 "id": "reseller:v1sandbox",
 "name": "reseller",
 "version": "v1sandbox",
 "title": "Enterprise Apps Reseller API",
 "description": "Lets you create and manage your customers and their subscriptions.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/google-apps/reseller/",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/apps/reseller/v1sandbox/",
 "basePath": "/apps/reseller/v1sandbox/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "apps/reseller/v1sandbox/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/apps.order": {
     "description": "Manage users on your domain"
    },
    "https://www.googleapis.com/auth/apps.order.readonly": {
     "description": "Manage users on your domain"
    }
   }
  }
 },
 "resources": {
  "customers": {
   "methods": {
    "get": {
     "id": "reseller.customers.get",
     "path": "customers/{customerId}",
     "httpMethod": "GET",
     "description": "Gets a customer resource if one exists and is owned by the reseller.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order",
      "https://www.googleapis.com/auth/apps.order.readonly"
     ]
    },
    "insert": {
     "id": "reseller.customers.insert",
     "path": "customers",
     "httpMethod": "POST",
     "description": "Creates a customer resource if one does not already exist.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "patch": {
     "id": "reseller.customers.patch",
     "path": "customers/{customerId}",
     "httpMethod": "PATCH",
     "description": "Update a customer resource if one it exists and is owned by the reseller. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "update": {
     "id": "reseller.customers.update",
     "path": "customers/{customerId}",
     "httpMethod": "PUT",
     "description": "Update a customer resource if one it exists and is owned by the reseller.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    }
   }
  },
  "subscriptions": {
   "methods": {
    "changePlan": {
     "id": "reseller.subscriptions.changePlan",
     "path": "customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
     "httpMethod": "POST",
     "description": "Changes the plan of a subscription",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "changeRenewalSettings": {
     "id": "reseller.subscriptions.changeRenewalSettings",
     "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
     "httpMethod": "POST",
     "description": "Changes the renewal settings of a subscription",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "changeSeats": {
     "id": "reseller.subscriptions.changeSeats",
     "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
     "httpMethod": "POST",
     "description": "Changes the seats configuration of a subscription",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "delete": {
     "id": "reseller.subscriptions.delete",
     "path": "customers/{customerId}/subscriptions/{subscriptionId}",
     "httpMethod": "DELETE",
     "description": "Cancels/Downgrades a subscription.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "get": {
     "id": "reseller.subscriptions.get",
     "path": "customers/{customerId}/subscriptions/{subscriptionId}",
     "httpMethod": "GET",
     "description": "Gets a subscription of the customer.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order",
      "https://www.googleapis.com/auth/apps.order.readonly"
     ]
    },
    "insert": {
     "id": "reseller.subscriptions.insert",
     "path": "customers/{customerId}/subscriptions",
     "httpMethod": "POST",
     "description": "Creates/Transfers a subscription for the customer.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    },
    "list": {
     "id": "reseller.subscriptions.list",
     "path": "subscriptions",
     "httpMethod": "GET",
     "description": "Lists subscriptions of a reseller, optionally filtered by a customer name prefix.",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order",
      "https://www.googleapis.com/auth/apps.order.readonly"
     ]
    },
    "startPaidService": {
     "id": "reseller.subscriptions.startPaidService",
     "path": "customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
     "httpMethod": "POST",
     "description": "Starts paid service of a trial subscription",
     "scopes": [
      "https://www.googleapis.com/auth/apps.order"
     ]
    }
   }
  }
 }
}
