//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package v2

import (
	context "context"
	fmt "fmt"

	autoscalingv2 "k8s.io/api/autoscaling/v2"
	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	// type HorizontalPodAutoscaler
	scheme.AddValidationFunc(
		(*autoscalingv2.HorizontalPodAutoscaler)(nil),
		func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
			switch op.Request.SubresourcePath() {
			case "/", "/status":
				return Validate_HorizontalPodAutoscaler(
					ctx, op, nil, /* fldPath */
					obj.(*autoscalingv2.HorizontalPodAutoscaler),
					safe.Cast[*autoscalingv2.HorizontalPodAutoscaler](oldObj))
			}
			return field.ErrorList{
				field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath())),
			}
		})
	return nil
}

// Validate_CrossVersionObjectReference validates an instance of CrossVersionObjectReference according
// to declarative validation rules in the API schema.
func Validate_CrossVersionObjectReference(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.CrossVersionObjectReference) (errs field.ErrorList) {

	{ // field autoscalingv2.CrossVersionObjectReference.Kind
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.CrossVersionObjectReference) *string {
				return &oldObj.Kind
			})
		errs = append(errs, fn(fldPath.Child("kind"), &obj.Kind, oldVal, oldObj != nil)...)
	}

	{ // field autoscalingv2.CrossVersionObjectReference.Name
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.CrossVersionObjectReference) *string {
				return &oldObj.Name
			})
		errs = append(errs, fn(fldPath.Child("name"), &obj.Name, oldVal, oldObj != nil)...)
	}

	// field autoscalingv2.CrossVersionObjectReference.APIVersion has no validation
	return errs
}

// Validate_HorizontalPodAutoscaler validates an instance of HorizontalPodAutoscaler according
// to declarative validation rules in the API schema.
func Validate_HorizontalPodAutoscaler(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.HorizontalPodAutoscaler) (errs field.ErrorList) {

	// field autoscalingv2.HorizontalPodAutoscaler.TypeMeta has no validation
	// field autoscalingv2.HorizontalPodAutoscaler.ObjectMeta has no validation

	{ // field autoscalingv2.HorizontalPodAutoscaler.Spec
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.HorizontalPodAutoscalerSpec,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call the type's validation function
			errs = append(errs, Validate_HorizontalPodAutoscalerSpec(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscaler) *autoscalingv2.HorizontalPodAutoscalerSpec {
				return &oldObj.Spec
			})
		errs = append(errs, fn(fldPath.Child("spec"), &obj.Spec, oldVal, oldObj != nil)...)
	}

	{ // field autoscalingv2.HorizontalPodAutoscaler.Status
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.HorizontalPodAutoscalerStatus,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call the type's validation function
			errs = append(errs, Validate_HorizontalPodAutoscalerStatus(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscaler) *autoscalingv2.HorizontalPodAutoscalerStatus {
				return &oldObj.Status
			})
		errs = append(errs, fn(fldPath.Child("status"), &obj.Status, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_HorizontalPodAutoscalerSpec validates an instance of HorizontalPodAutoscalerSpec according
// to declarative validation rules in the API schema.
func Validate_HorizontalPodAutoscalerSpec(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.HorizontalPodAutoscalerSpec) (errs field.ErrorList) {

	{ // field autoscalingv2.HorizontalPodAutoscalerSpec.ScaleTargetRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.CrossVersionObjectReference,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call the type's validation function
			errs = append(errs, Validate_CrossVersionObjectReference(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscalerSpec) *autoscalingv2.CrossVersionObjectReference {
				return &oldObj.ScaleTargetRef
			})
		errs = append(errs, fn(fldPath.Child("scaleTargetRef"), &obj.ScaleTargetRef, oldVal, oldObj != nil)...)
	}

	{ // field autoscalingv2.HorizontalPodAutoscalerSpec.MinReplicas
		fn := func(
			fldPath *field.Path,
			obj, oldObj *int32,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.IfOption(ctx, op, fldPath, obj, oldObj, "HPAScaleToZero", true,
				func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int32) field.ErrorList {
					return validate.Minimum(ctx, op, fldPath, obj, oldObj, 0)
				}).MarkAlpha(); len(e) != 0 {
				errs = append(errs, e...)
			}
			if e := validate.IfOption(ctx, op, fldPath, obj, oldObj, "HPAScaleToZero", false,
				func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int32) field.ErrorList {
					return validate.Minimum(ctx, op, fldPath, obj, oldObj, 1)
				}).MarkAlpha(); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscalerSpec) *int32 {
				return oldObj.MinReplicas
			})
		errs = append(errs, fn(fldPath.Child("minReplicas"), obj.MinReplicas, oldVal, oldObj != nil)...)
	}

	{ // field autoscalingv2.HorizontalPodAutoscalerSpec.MaxReplicas
		fn := func(
			fldPath *field.Path,
			obj, oldObj *int32,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.Minimum(ctx, op, fldPath, obj, oldObj, 1).MarkAlpha(); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscalerSpec) *int32 {
				return &oldObj.MaxReplicas
			})
		errs = append(errs, fn(fldPath.Child("maxReplicas"), &obj.MaxReplicas, oldVal, oldObj != nil)...)
	}

	{ // field autoscalingv2.HorizontalPodAutoscalerSpec.Metrics
		fn := func(
			fldPath *field.Path,
			obj, oldObj []autoscalingv2.MetricSpec,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalSlice(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// iterate the list and call the type's validation function
			if e := validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, nil, nil, Validate_MetricSpec); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscalerSpec) []autoscalingv2.MetricSpec {
				return oldObj.Metrics
			})
		errs = append(errs, fn(fldPath.Child("metrics"), obj.Metrics, oldVal, oldObj != nil)...)
	}

	// field autoscalingv2.HorizontalPodAutoscalerSpec.Behavior has no validation
	return errs
}

// Validate_HorizontalPodAutoscalerStatus validates an instance of HorizontalPodAutoscalerStatus according
// to declarative validation rules in the API schema.
func Validate_HorizontalPodAutoscalerStatus(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.HorizontalPodAutoscalerStatus) (errs field.ErrorList) {

	// field autoscalingv2.HorizontalPodAutoscalerStatus.ObservedGeneration has no validation
	// field autoscalingv2.HorizontalPodAutoscalerStatus.LastScaleTime has no validation
	// field autoscalingv2.HorizontalPodAutoscalerStatus.CurrentReplicas has no validation
	// field autoscalingv2.HorizontalPodAutoscalerStatus.DesiredReplicas has no validation

	{ // field autoscalingv2.HorizontalPodAutoscalerStatus.CurrentMetrics
		fn := func(
			fldPath *field.Path,
			obj, oldObj []autoscalingv2.MetricStatus,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalSlice(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// iterate the list and call the type's validation function
			if e := validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, nil, nil, Validate_MetricStatus); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.HorizontalPodAutoscalerStatus) []autoscalingv2.MetricStatus {
				return oldObj.CurrentMetrics
			})
		errs = append(errs, fn(fldPath.Child("currentMetrics"), obj.CurrentMetrics, oldVal, oldObj != nil)...)
	}

	// field autoscalingv2.HorizontalPodAutoscalerStatus.Conditions has no validation
	return errs
}

// Validate_MetricSpec validates an instance of MetricSpec according
// to declarative validation rules in the API schema.
func Validate_MetricSpec(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.MetricSpec) (errs field.ErrorList) {

	// field autoscalingv2.MetricSpec.Type has no validation

	{ // field autoscalingv2.MetricSpec.Object
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.ObjectMetricSource,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.MetricSpec) *autoscalingv2.ObjectMetricSource {
				return oldObj.Object
			})
		errs = append(errs, fn(fldPath.Child("object"), obj.Object, oldVal, oldObj != nil)...)
	}

	// field autoscalingv2.MetricSpec.Pods has no validation
	// field autoscalingv2.MetricSpec.Resource has no validation
	// field autoscalingv2.MetricSpec.ContainerResource has no validation
	// field autoscalingv2.MetricSpec.External has no validation
	return errs
}

// Validate_MetricStatus validates an instance of MetricStatus according
// to declarative validation rules in the API schema.
func Validate_MetricStatus(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.MetricStatus) (errs field.ErrorList) {

	// field autoscalingv2.MetricStatus.Type has no validation

	{ // field autoscalingv2.MetricStatus.Object
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.ObjectMetricStatus,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj).MarkAlpha().MarkShortCircuit(); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.MetricStatus) *autoscalingv2.ObjectMetricStatus {
				return oldObj.Object
			})
		errs = append(errs, fn(fldPath.Child("object"), obj.Object, oldVal, oldObj != nil)...)
	}

	// field autoscalingv2.MetricStatus.Pods has no validation
	// field autoscalingv2.MetricStatus.Resource has no validation
	// field autoscalingv2.MetricStatus.ContainerResource has no validation
	// field autoscalingv2.MetricStatus.External has no validation
	return errs
}

// Validate_ObjectMetricSource validates an instance of ObjectMetricSource according
// to declarative validation rules in the API schema.
func Validate_ObjectMetricSource(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.ObjectMetricSource) (errs field.ErrorList) {

	{ // field autoscalingv2.ObjectMetricSource.DescribedObject
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.CrossVersionObjectReference,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call the type's validation function
			errs = append(errs, Validate_CrossVersionObjectReference(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.ObjectMetricSource) *autoscalingv2.CrossVersionObjectReference {
				return &oldObj.DescribedObject
			})
		errs = append(errs, fn(fldPath.Child("describedObject"), &obj.DescribedObject, oldVal, oldObj != nil)...)
	}

	// field autoscalingv2.ObjectMetricSource.Target has no validation
	// field autoscalingv2.ObjectMetricSource.Metric has no validation
	return errs
}

// Validate_ObjectMetricStatus validates an instance of ObjectMetricStatus according
// to declarative validation rules in the API schema.
func Validate_ObjectMetricStatus(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *autoscalingv2.ObjectMetricStatus) (errs field.ErrorList) {

	// field autoscalingv2.ObjectMetricStatus.Metric has no validation
	// field autoscalingv2.ObjectMetricStatus.Current has no validation

	{ // field autoscalingv2.ObjectMetricStatus.DescribedObject
		fn := func(
			fldPath *field.Path,
			obj, oldObj *autoscalingv2.CrossVersionObjectReference,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call the type's validation function
			errs = append(errs, Validate_CrossVersionObjectReference(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *autoscalingv2.ObjectMetricStatus) *autoscalingv2.CrossVersionObjectReference {
				return &oldObj.DescribedObject
			})
		errs = append(errs, fn(fldPath.Child("describedObject"), &obj.DescribedObject, oldVal, oldObj != nil)...)
	}

	return errs
}
