#!/bin/bash

[ "$IFACE" == "eth0" ] || exit 0

{% for host, ip_addrs in salt['mine.get']('roles:kubernetes-pool', 'network.ip_addrs', 'grain').items() %}
  {% set network_ipaddr = None %}
  {% if salt['network.ip_addrs']('eth0') is defined %}
    {% set network_ipaddr = salt['network.ip_addrs']('eth0')[0] %}
  {% elif salt['network.ip_addrs']('local') is defined %}
    {% set network_ipaddr = salt['network.ip_addrs']('local')[0] %}
  {% endif %}
  {% if network_ipaddr is defined and ip_addrs[0] != network_ipaddr %}
    {% set cidr = salt['mine.get'](host, 'grains.items')[host]['cbr-cidr'] %}
      route del -net {{ cidr }}
  {% endif %}
{% endfor %}
