package(default_visibility = ["//visibility:public"])

filegroup(
    name = "fixtures",
    srcs = glob([
        "**/*.yaml",
        "**/*.yml",
        "**/*.json",
    ]),
)

filegroup(
    name = "sources",
    srcs = glob([
        "**/*",
    ]),
)
