{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/plus.circles.read": {
          "description": "View your circles and the people and pages in them"
        },
        "https://www.googleapis.com/auth/plus.login": {
          "description": "View your basic profile info, including your age range and language"
        },
        "https://www.googleapis.com/auth/plus.me": {
          "description": "Associate you with your personal info on Google"
        },
        "https://www.googleapis.com/auth/plus.media.upload": {
          "description": "Send your photos and videos to Google+"
        },
        "https://www.googleapis.com/auth/plus.profiles.read": {
          "description": "View your own Google+ profile and profiles visible to you"
        },
        "https://www.googleapis.com/auth/plus.stream.read": {
          "description": "View your Google+ posts, comments, and stream"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.googleapis.com/auth/userinfo.profile": {
          "description": "See your personal info, including any personal info you've made publicly available"
        }
      }
    }
  },
  "basePath": "/plusDomains/v1/",
  "baseUrl": "https://www.googleapis.com/plusDomains/v1/",
  "batchPath": "batch/plusDomains/v1",
  "description": "Builds on top of the Google+ platform for Google Apps Domains.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/+/domains/",
  "etag": "\"VPK3KBfpaEgZ16pozGOoMYfKc0U/ANplrqN0lyV1CO8o5_Wvj5IFim0\"",
  "id": "plusDomains:v1",
  "kind": "discovery#restDescription",
  "name": "plusDomains",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "activities": {
      "methods": {
        "get": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.activities.get",
          "path": "activities/{activityId}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me",
            "https://www.googleapis.com/auth/plus.stream.read"
          ]
        },
        "list": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.activities.list",
          "path": "people/{userId}/activities/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me",
            "https://www.googleapis.com/auth/plus.stream.read"
          ]
        }
      }
    },
    "audiences": {
      "methods": {
        "list": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.audiences.list",
          "path": "people/{userId}/audiences",
          "scopes": [
            "https://www.googleapis.com/auth/plus.circles.read",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me"
          ]
        }
      }
    },
    "circles": {
      "methods": {
        "list": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.circles.list",
          "path": "people/{userId}/circles",
          "scopes": [
            "https://www.googleapis.com/auth/plus.circles.read",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me"
          ]
        }
      }
    },
    "comments": {
      "methods": {
        "get": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.comments.get",
          "path": "comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.stream.read"
          ]
        },
        "list": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.comments.list",
          "path": "activities/{activityId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.stream.read"
          ]
        }
      }
    },
    "media": {
      "methods": {
        "insert": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "POST",
          "id": "plusDomains.media.insert",
          "path": "people/{userId}/media/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me",
            "https://www.googleapis.com/auth/plus.media.upload"
          ],
          "supportsMediaUpload": true
        }
      }
    },
    "people": {
      "methods": {
        "get": {
          "description": "Get a person's profile.",
          "httpMethod": "GET",
          "id": "plusDomains.people.get",
          "path": "people/{userId}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me",
            "https://www.googleapis.com/auth/plus.profiles.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ]
        },
        "list": {
          "description": "List all of the people in the specified collection.",
          "httpMethod": "GET",
          "id": "plusDomains.people.list",
          "path": "people/{userId}/people/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.circles.read",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.me"
          ]
        },
        "listByActivity": {
          "description": "Shut down. See https://developers.google.com/+/api-shutdown for more details.",
          "httpMethod": "GET",
          "id": "plusDomains.people.listByActivity",
          "path": "activities/{activityId}/people/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/plus.stream.read"
          ]
        }
      }
    }
  },
  "revision": "20190415",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "plusDomains/v1/",
  "title": "Google+ Domains API",
  "version": "v1"
}