{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admin.datatransfer": {
          "description": "View and manage data transfers between users in your organization"
        },
        "https://www.googleapis.com/auth/admin.datatransfer.readonly": {
          "description": "View data transfers between users in your organization"
        }
      }
    }
  },
  "basePath": "/admin/datatransfer/v1/",
  "baseUrl": "https://www.googleapis.com/admin/datatransfer/v1/",
  "batchPath": "batch/admin/datatransfer_v1",
  "canonicalName": "DataTransfer",
  "description": "Transfers user data from one user to another.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/admin-sdk/data-transfer/",
  "etag": "\"F5McR9eEaw0XRpaO3M9gbIugkbs/4nXC3yxZNbcRmDAehf253f0RsHM\"",
  "id": "admin:datatransfer_v1",
  "kind": "discovery#restDescription",
  "name": "admin",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "packagePath": "admin",
  "protocol": "rest",
  "resources": {
    "applications": {
      "methods": {
        "get": {
          "description": "Retrieves information about an application for the given application ID.",
          "httpMethod": "GET",
          "id": "datatransfer.applications.get",
          "path": "applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ]
        },
        "list": {
          "description": "Lists the applications available for data transfer for a customer.",
          "httpMethod": "GET",
          "id": "datatransfer.applications.list",
          "path": "applications",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ]
        }
      }
    },
    "transfers": {
      "methods": {
        "get": {
          "description": "Retrieves a data transfer request by its resource ID.",
          "httpMethod": "GET",
          "id": "datatransfer.transfers.get",
          "path": "transfers/{dataTransferId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ]
        },
        "insert": {
          "description": "Inserts a data transfer request.",
          "httpMethod": "POST",
          "id": "datatransfer.transfers.insert",
          "path": "transfers",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer"
          ]
        },
        "list": {
          "description": "Lists the transfers for a customer by source user, destination user, or status.",
          "httpMethod": "GET",
          "id": "datatransfer.transfers.list",
          "path": "transfers",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ]
        }
      }
    }
  },
  "revision": "20190829",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "admin/datatransfer/v1/",
  "title": "Admin Data Transfer API",
  "version": "datatransfer_v1"
}