{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "View and manage your Google Docs documents"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://script.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Script",
  "description": "Manages and executes Google Apps Script projects.\n",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "fullyEncodeReservedExpansion": true,
  "id": "script:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "name": "script",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "processes": {
      "methods": {
        "list": {
          "description": "List information about processes made by or on behalf of a user,\nsuch as process type and current status.",
          "flatPath": "v1/processes",
          "httpMethod": "GET",
          "id": "script.processes.list",
          "path": "v1/processes",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ]
        },
        "listScriptProcesses": {
          "description": "List information about a script's executed processes, such as process type\nand current status.",
          "flatPath": "v1/processes:listScriptProcesses",
          "httpMethod": "GET",
          "id": "script.processes.listScriptProcesses",
          "path": "v1/processes:listScriptProcesses",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ]
        }
      }
    },
    "projects": {
      "methods": {
        "create": {
          "description": "Creates a new, empty script project with no script files and a base\nmanifest file.",
          "flatPath": "v1/projects",
          "httpMethod": "POST",
          "id": "script.projects.create",
          "path": "v1/projects",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        },
        "get": {
          "description": "Gets a script project's metadata.",
          "flatPath": "v1/projects/{scriptId}",
          "httpMethod": "GET",
          "id": "script.projects.get",
          "path": "v1/projects/{scriptId}",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ]
        },
        "getContent": {
          "description": "Gets the content of the script project, including the code source and\nmetadata for each script file.",
          "flatPath": "v1/projects/{scriptId}/content",
          "httpMethod": "GET",
          "id": "script.projects.getContent",
          "path": "v1/projects/{scriptId}/content",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ]
        },
        "getMetrics": {
          "description": "Get metrics data for scripts, such as number of executions and\nactive users.",
          "flatPath": "v1/projects/{scriptId}/metrics",
          "httpMethod": "GET",
          "id": "script.projects.getMetrics",
          "path": "v1/projects/{scriptId}/metrics",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ]
        },
        "updateContent": {
          "description": "Updates the content of the specified script project.\nThis content is stored as the HEAD version, and is used when the script is\nexecuted as a trigger, in the script editor, in add-on preview mode, or as\na web app or Apps Script API in development mode. This clears all the\nexisting files in the project.",
          "flatPath": "v1/projects/{scriptId}/content",
          "httpMethod": "PUT",
          "id": "script.projects.updateContent",
          "path": "v1/projects/{scriptId}/content",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        }
      },
      "resources": {
        "deployments": {
          "methods": {
            "create": {
              "description": "Creates a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "httpMethod": "POST",
              "id": "script.projects.deployments.create",
              "path": "v1/projects/{scriptId}/deployments",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            },
            "delete": {
              "description": "Deletes a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "DELETE",
              "id": "script.projects.deployments.delete",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            },
            "get": {
              "description": "Gets a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "GET",
              "id": "script.projects.deployments.get",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ]
            },
            "list": {
              "description": "Lists the deployments of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "httpMethod": "GET",
              "id": "script.projects.deployments.list",
              "path": "v1/projects/{scriptId}/deployments",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ]
            },
            "update": {
              "description": "Updates a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "PUT",
              "id": "script.projects.deployments.update",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            }
          }
        },
        "versions": {
          "methods": {
            "create": {
              "description": "Creates a new immutable version using the current code, with a unique\nversion number.",
              "flatPath": "v1/projects/{scriptId}/versions",
              "httpMethod": "POST",
              "id": "script.projects.versions.create",
              "path": "v1/projects/{scriptId}/versions",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ]
            },
            "get": {
              "description": "Gets a version of a script project.",
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "httpMethod": "GET",
              "id": "script.projects.versions.get",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ]
            },
            "list": {
              "description": "List the versions of a script project.",
              "flatPath": "v1/projects/{scriptId}/versions",
              "httpMethod": "GET",
              "id": "script.projects.versions.list",
              "path": "v1/projects/{scriptId}/versions",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ]
            }
          }
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "description": "Runs a function in an Apps Script project. The script project must be\ndeployed for use with the Apps Script API and the calling application must\nshare the same Cloud Platform project.\n\nThis method requires authorization with an OAuth 2.0 token that includes at\nleast one of the scopes listed in the\n[Authorization](#authorization-scopes) section; script projects that do not\nrequire authorization cannot be executed through this API. To find the\ncorrect scopes to in[...]",
          "flatPath": "v1/scripts/{scriptId}:run",
          "httpMethod": "POST",
          "id": "script.scripts.run",
          "path": "v1/scripts/{scriptId}:run",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ]
        }
      }
    }
  },
  "revision": "20200215",
  "rootUrl": "https://script.googleapis.com/",
  "servicePath": "",
  "title": "Apps Script API",
  "version": "v1"
}