{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adexchange.seller": {
          "description": "View and manage your Ad Exchange data"
        },
        "https://www.googleapis.com/auth/adexchange.seller.readonly": {
          "description": "View your Ad Exchange data"
        }
      }
    }
  },
  "basePath": "/adexchangeseller/v1.1/",
  "baseUrl": "https://www.googleapis.com/adexchangeseller/v1.1/",
  "batchPath": "batch/adexchangeseller/v1.1",
  "canonicalName": "Ad Exchange Seller",
  "description": "Accesses the inventory of Ad Exchange seller users and generates reports.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/ad-exchange/seller-rest/",
  "etag": "\"Zkyw9ACJZUvcYmlFaKGChzhmtnE/8jrsaX2ZBCjXN0ZZXy-z0sEU9bw\"",
  "id": "adexchangeseller:v1.1",
  "kind": "discovery#restDescription",
  "name": "adexchangeseller",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "accounts": {
      "methods": {
        "get": {
          "description": "Get information about the selected Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.accounts.get",
          "path": "accounts/{accountId}",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      }
    },
    "adclients": {
      "methods": {
        "list": {
          "description": "List all ad clients in this Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.adclients.list",
          "path": "adclients",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      }
    },
    "adunits": {
      "methods": {
        "get": {
          "description": "Gets the specified ad unit in the specified ad client.",
          "httpMethod": "GET",
          "id": "adexchangeseller.adunits.get",
          "path": "adclients/{adClientId}/adunits/{adUnitId}",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        },
        "list": {
          "description": "List all ad units in the specified ad client for this Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.adunits.list",
          "path": "adclients/{adClientId}/adunits",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      },
      "resources": {
        "customchannels": {
          "methods": {
            "list": {
              "description": "List all custom channels which the specified ad unit belongs to.",
              "httpMethod": "GET",
              "id": "adexchangeseller.adunits.customchannels.list",
              "path": "adclients/{adClientId}/adunits/{adUnitId}/customchannels",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.seller",
                "https://www.googleapis.com/auth/adexchange.seller.readonly"
              ]
            }
          }
        }
      }
    },
    "alerts": {
      "methods": {
        "list": {
          "description": "List the alerts for this Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.alerts.list",
          "path": "alerts",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      }
    },
    "customchannels": {
      "methods": {
        "get": {
          "description": "Get the specified custom channel from the specified ad client.",
          "httpMethod": "GET",
          "id": "adexchangeseller.customchannels.get",
          "path": "adclients/{adClientId}/customchannels/{customChannelId}",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        },
        "list": {
          "description": "List all custom channels in the specified ad client for this Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.customchannels.list",
          "path": "adclients/{adClientId}/customchannels",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      },
      "resources": {
        "adunits": {
          "methods": {
            "list": {
              "description": "List all ad units in the specified custom channel.",
              "httpMethod": "GET",
              "id": "adexchangeseller.customchannels.adunits.list",
              "path": "adclients/{adClientId}/customchannels/{customChannelId}/adunits",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.seller",
                "https://www.googleapis.com/auth/adexchange.seller.readonly"
              ]
            }
          }
        }
      }
    },
    "metadata": {
      "resources": {
        "dimensions": {
          "methods": {
            "list": {
              "description": "List the metadata for the dimensions available to this AdExchange account.",
              "httpMethod": "GET",
              "id": "adexchangeseller.metadata.dimensions.list",
              "path": "metadata/dimensions",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.seller",
                "https://www.googleapis.com/auth/adexchange.seller.readonly"
              ]
            }
          }
        },
        "metrics": {
          "methods": {
            "list": {
              "description": "List the metadata for the metrics available to this AdExchange account.",
              "httpMethod": "GET",
              "id": "adexchangeseller.metadata.metrics.list",
              "path": "metadata/metrics",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.seller",
                "https://www.googleapis.com/auth/adexchange.seller.readonly"
              ]
            }
          }
        }
      }
    },
    "preferreddeals": {
      "methods": {
        "get": {
          "description": "Get information about the selected Ad Exchange Preferred Deal.",
          "httpMethod": "GET",
          "id": "adexchangeseller.preferreddeals.get",
          "path": "preferreddeals/{dealId}",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        },
        "list": {
          "description": "List the preferred deals for this Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.preferreddeals.list",
          "path": "preferreddeals",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      }
    },
    "reports": {
      "methods": {
        "generate": {
          "description": "Generate an Ad Exchange report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
          "httpMethod": "GET",
          "id": "adexchangeseller.reports.generate",
          "path": "reports",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ],
          "supportsMediaDownload": true
        }
      },
      "resources": {
        "saved": {
          "methods": {
            "generate": {
              "description": "Generate an Ad Exchange report based on the saved report ID sent in the query parameters.",
              "httpMethod": "GET",
              "id": "adexchangeseller.reports.saved.generate",
              "path": "reports/{savedReportId}",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.seller",
                "https://www.googleapis.com/auth/adexchange.seller.readonly"
              ]
            },
            "list": {
              "description": "List all saved reports in this Ad Exchange account.",
              "httpMethod": "GET",
              "id": "adexchangeseller.reports.saved.list",
              "path": "reports/saved",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.seller",
                "https://www.googleapis.com/auth/adexchange.seller.readonly"
              ]
            }
          }
        }
      }
    },
    "urlchannels": {
      "methods": {
        "list": {
          "description": "List all URL channels in the specified ad client for this Ad Exchange account.",
          "httpMethod": "GET",
          "id": "adexchangeseller.urlchannels.list",
          "path": "adclients/{adClientId}/urlchannels",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.seller",
            "https://www.googleapis.com/auth/adexchange.seller.readonly"
          ]
        }
      }
    }
  },
  "revision": "20171101",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "adexchangeseller/v1.1/",
  "title": "Ad Exchange Seller API",
  "version": "v1.1"
}