#%RAML 0.8
baseUri: http://server/api/{version}
title: Kubernetes
version: v1beta1
mediaType: application/json
documentation:
 - title: OBSOLETE
   content: |
     We are working on new up-to-date API documentation. 
     Note for developers: do not regenerate kubernetes.html from this file.
